create extension if not exists "pgcrypto";

create table if not exists public.candidates (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text not null,
  email text not null,
  registration_date date not null default current_date,
  candidate_status text not null default 'Pendiente' check (
    candidate_status in ('Pendiente', 'Preseleccionado', 'Descartado', 'Contratado')
  ),
  job_roles text[] not null check (cardinality(job_roles) > 0),
  sport_specialties text[] not null default '{}',
  tags text[] not null default '{}',
  notes text not null default '',
  observations text not null default '',
  attachment_name text,
  attachment_path text,
  attachment_mime_type text,
  privacy_accepted boolean not null default false,
  vacancy_consent boolean not null default false,
  source text not null default 'private' check (source in ('public', 'private')),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.candidates
  add column if not exists registration_date date not null default current_date,
  add column if not exists candidate_status text not null default 'Pendiente',
  add column if not exists sport_specialties text[] not null default '{}',
  add column if not exists tags text[] not null default '{}',
  add column if not exists notes text not null default '',
  add column if not exists observations text not null default '',
  add column if not exists attachment_name text,
  add column if not exists attachment_path text,
  add column if not exists attachment_mime_type text,
  add column if not exists privacy_accepted boolean not null default false,
  add column if not exists vacancy_consent boolean not null default false,
  add column if not exists source text not null default 'private';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'candidates_candidate_status_check'
      and conrelid = 'public.candidates'::regclass
  ) then
    alter table public.candidates
      add constraint candidates_candidate_status_check
      check (candidate_status in ('Pendiente', 'Preseleccionado', 'Descartado', 'Contratado'));
  end if;
end $$;

comment on table public.candidates is 'Candidaturas registradas desde los paneles de Curriculos EDP.';

create index if not exists candidates_registration_date_created_at_idx
on public.candidates (registration_date desc, created_at desc);

create index if not exists candidates_candidate_status_idx
on public.candidates (candidate_status);

create index if not exists candidates_full_name_idx
on public.candidates (full_name);

create index if not exists candidates_job_roles_gin_idx
on public.candidates using gin (job_roles);

create index if not exists candidates_tags_gin_idx
on public.candidates using gin (tags);

create or replace function public.get_candidate_filter_options()
returns table (
  option_type text,
  option_value text
)
language sql
stable
security definer
set search_path = public
as $$
  select 'role' as option_type, role as option_value
  from (
    select distinct unnest(job_roles) as role
    from public.candidates
  ) roles
  where nullif(btrim(role), '') is not null
  union
  select 'tag' as option_type, tag as option_value
  from (
    select distinct unnest(tags) as tag
    from public.candidates
  ) tags
  where nullif(btrim(tag), '') is not null
  order by option_type, option_value;
$$;

revoke all on function public.get_candidate_filter_options() from public;
grant execute on function public.get_candidate_filter_options() to authenticated;

do $$
begin
  if to_regclass('public.programacion_conserjes') is null
     and to_regclass('public."tbl_programacionConserjes"') is not null then
    alter table public."tbl_programacionConserjes" rename to programacion_conserjes;
  elsif to_regclass('public.programacion_conserjes') is null
     and to_regclass('public.findesemana') is not null then
    alter table public.findesemana rename to programacion_conserjes;
  end if;
end $$;

create table if not exists public.programacion_conserjes (
  id bigint generated by default as identity primary key,
  personal text not null,
  instalacion text not null,
  fecha date not null,
  hora_inicio time not null,
  hora_fin time,
  hora_evento time,
  deporte text,
  actividad text,
  source_file text,
  sort_order integer not null default 0,
  tipo_programacion text not null default 'fin_semana',
  archived_at timestamp with time zone,
  created_at timestamp with time zone not null default timezone('utc', now()),
  constraint programacion_conserjes_tipo_check
    check (tipo_programacion in ('fin_semana', 'semanal'))
);

alter table public.programacion_conserjes
  add column if not exists tipo_programacion text not null default 'fin_semana',
  add column if not exists archived_at timestamp with time zone,
  add column if not exists created_at timestamp with time zone not null default timezone('utc', now());

drop index if exists idx_findesemana_loaded_at;
drop index if exists idx_findesemana_fecha;
drop index if exists idx_findesemana_instalacion;
drop index if exists idx_findesemana_personal;
drop index if exists idx_findesemana_archived_at;

alter table public.programacion_conserjes
drop column if exists loaded_at;

alter table public.programacion_conserjes
drop constraint if exists programacion_conserjes_tipo_check;

alter table public.programacion_conserjes
add constraint programacion_conserjes_tipo_check
check (tipo_programacion in ('fin_semana', 'semanal'));

update public.programacion_conserjes
set tipo_programacion = 'semanal'
where source_file = 'planning_completo_revisado.csv';

create index if not exists idx_programacion_conserjes_tipo_fecha
on public.programacion_conserjes (tipo_programacion, fecha);

create index if not exists idx_programacion_conserjes_instalacion
on public.programacion_conserjes (instalacion);

create index if not exists idx_programacion_conserjes_personal
on public.programacion_conserjes (personal);

create index if not exists idx_programacion_conserjes_archived_at
on public.programacion_conserjes (archived_at);

do $$
begin
  if to_regclass('public.personal') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'personal'
         and column_name = 'id_personal'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'personal'
         and column_name = 'id'
     ) then
    alter table public.personal rename column id_personal to id;
  end if;
end $$;

do $$
begin
  if to_regclass('public.instalaciones') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'instalaciones'
         and column_name = 'id_instalacion'
     )
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'instalaciones'
         and column_name = 'id'
     ) then
    alter table public.instalaciones rename column id_instalacion to id;
  end if;
end $$;

create table if not exists public.programming_personnel (
  id bigint generated by default as identity primary key,
  name text not null,
  personal_id integer,
  dni text,
  pin text,
  created_at timestamp with time zone not null default timezone('utc', now()),
  constraint programming_personnel_name_not_blank check (btrim(name) <> ''),
  constraint programming_personnel_pin_format check (pin is null or pin ~ '^[0-9]{8}$'),
  constraint programming_personnel_name_unique unique (name)
);

alter table public.programming_personnel
  add column if not exists pin text;

alter table public.programming_personnel
  add column if not exists personal_id integer;

alter table public.programming_personnel
  add column if not exists dni text;

do $$
begin
  if to_regclass('public.personal') is not null
     and not exists (
       select 1
       from pg_constraint
       where conname = 'programming_personnel_personal_id_fkey'
         and conrelid = 'public.programming_personnel'::regclass
     ) then
    alter table public.programming_personnel
      add constraint programming_personnel_personal_id_fkey
      foreign key (personal_id)
      references public.personal (id)
      on delete set null;
  end if;
end $$;

alter table public.programming_personnel
  drop constraint if exists programming_personnel_pin_format;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'programming_personnel_pin_format'
      and conrelid = 'public.programming_personnel'::regclass
  ) then
    alter table public.programming_personnel
      add constraint programming_personnel_pin_format
      check (pin is null or pin ~ '^[0-9]{8}$');
  end if;
end $$;

create index if not exists idx_programming_personnel_name
on public.programming_personnel (name);

create unique index if not exists idx_programming_personnel_personal_id_unique
on public.programming_personnel (personal_id)
where personal_id is not null;

create unique index if not exists idx_programming_personnel_pin_unique
on public.programming_personnel (pin)
where pin is not null;

create table if not exists public.programming_installations (
  id bigint generated by default as identity primary key,
  installation_id integer,
  name text not null,
  created_at timestamp with time zone not null default timezone('utc', now()),
  constraint programming_installations_name_not_blank check (btrim(name) <> ''),
  constraint programming_installations_name_unique unique (name)
);

alter table public.programming_installations
  add column if not exists installation_id integer;

do $$
begin
  if to_regclass('public.instalaciones') is not null
     and not exists (
       select 1
       from pg_constraint
       where conname = 'programming_installations_installation_id_fkey'
         and conrelid = 'public.programming_installations'::regclass
     ) then
    alter table public.programming_installations
      add constraint programming_installations_installation_id_fkey
      foreign key (installation_id)
      references public.instalaciones (id)
      on delete set null;
  end if;
end $$;

create index if not exists idx_programming_installations_name
on public.programming_installations (name);

create unique index if not exists idx_programming_installations_installation_id_unique
on public.programming_installations (installation_id)
where installation_id is not null;

drop function if exists public.get_programming_personal_for_pin(text);

create or replace function public.get_programming_personnel_for_pin(access_pin text)
returns table(name text)
language sql
stable
security definer
set search_path = public
as $$
  select programming_personnel.name
  from public.programming_personnel
  where programming_personnel.pin = btrim(access_pin)
    and programming_personnel.pin ~ '^[0-9]{8}$'
  order by programming_personnel.name
  limit 1
$$;

revoke all on function public.get_programming_personnel_for_pin(text) from public;
grant execute on function public.get_programming_personnel_for_pin(text) to anon, authenticated;

notify pgrst, 'reload schema';

alter table public.candidates enable row level security;

drop policy if exists "anon_can_insert_public_candidates" on public.candidates;
create policy "anon_can_insert_public_candidates"
on public.candidates
for insert
to anon
with check (
  source = 'public'
  and privacy_accepted = true
);

drop policy if exists "authenticated_can_read_candidates" on public.candidates;
create policy "authenticated_can_read_candidates"
on public.candidates
for select
to authenticated
using (true);

drop policy if exists "authenticated_can_insert_candidates" on public.candidates;
create policy "authenticated_can_insert_candidates"
on public.candidates
for insert
to authenticated
with check (true);

drop policy if exists "authenticated_can_update_candidates" on public.candidates;
create policy "authenticated_can_update_candidates"
on public.candidates
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated_can_delete_candidates" on public.candidates;
create policy "authenticated_can_delete_candidates"
on public.candidates
for delete
to authenticated
using (true);

alter table public.programacion_conserjes enable row level security;

drop policy if exists "authenticated_can_read_programacion_conserjes" on public.programacion_conserjes;
create policy "authenticated_can_read_programacion_conserjes"
on public.programacion_conserjes
for select
to authenticated
using (true);

drop policy if exists "anon_can_read_programacion_conserjes" on public.programacion_conserjes;
create policy "anon_can_read_programacion_conserjes"
on public.programacion_conserjes
for select
to anon
using (true);

drop policy if exists "authenticated_can_insert_programacion_conserjes" on public.programacion_conserjes;
create policy "authenticated_can_insert_programacion_conserjes"
on public.programacion_conserjes
for insert
to authenticated
with check (true);

drop policy if exists "authenticated_can_update_programacion_conserjes" on public.programacion_conserjes;
create policy "authenticated_can_update_programacion_conserjes"
on public.programacion_conserjes
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated_can_delete_programacion_conserjes" on public.programacion_conserjes;
create policy "authenticated_can_delete_programacion_conserjes"
on public.programacion_conserjes
for delete
to authenticated
using (true);

alter table public.programming_personnel enable row level security;

drop policy if exists "authenticated_can_read_programming_personnel" on public.programming_personnel;
create policy "authenticated_can_read_programming_personnel"
on public.programming_personnel
for select
to authenticated
using (true);

drop policy if exists "authenticated_can_insert_programming_personnel" on public.programming_personnel;
create policy "authenticated_can_insert_programming_personnel"
on public.programming_personnel
for insert
to authenticated
with check (true);

drop policy if exists "authenticated_can_update_programming_personnel" on public.programming_personnel;
create policy "authenticated_can_update_programming_personnel"
on public.programming_personnel
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated_can_delete_programming_personnel" on public.programming_personnel;
create policy "authenticated_can_delete_programming_personnel"
on public.programming_personnel
for delete
to authenticated
using (true);

alter table public.programming_installations enable row level security;

drop policy if exists "authenticated_can_read_programming_installations" on public.programming_installations;
create policy "authenticated_can_read_programming_installations"
on public.programming_installations
for select
to authenticated
using (true);

drop policy if exists "authenticated_can_insert_programming_installations" on public.programming_installations;
create policy "authenticated_can_insert_programming_installations"
on public.programming_installations
for insert
to authenticated
with check (true);

drop policy if exists "authenticated_can_update_programming_installations" on public.programming_installations;
create policy "authenticated_can_update_programming_installations"
on public.programming_installations
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated_can_delete_programming_installations" on public.programming_installations;
create policy "authenticated_can_delete_programming_installations"
on public.programming_installations
for delete
to authenticated
using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'candidate-cvs',
  'candidate-cvs',
  false,
  10485760,
  array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.oasis.opendocument.text',
    'application/rtf',
    'text/plain',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do nothing;

drop policy if exists "anon_can_upload_candidate_cvs" on storage.objects;
create policy "anon_can_upload_candidate_cvs"
on storage.objects
for insert
to anon
with check (bucket_id = 'candidate-cvs');

drop policy if exists "authenticated_can_manage_candidate_cvs" on storage.objects;
create policy "authenticated_can_manage_candidate_cvs"
on storage.objects
for all
to authenticated
using (bucket_id = 'candidate-cvs')
with check (bucket_id = 'candidate-cvs');
