insert into public.personal (id, activo, pert_empresa, vinculacion_id, personal, genero, antiguedad, dni, fecha_nacimiento, ss, email, movil, telefono, direccion, codigo_postal, localidad, municipio, provincia, cuenta_corriente, foto, contrato_id, observacion, desplazamiento, enviar, carpeta, pago, cv, da, ds, prev_riesgos, epi, titulos, ig_ac, uniforme, med_emerg, ens, com_antiguedad_04, com_absorbible_18, porcent_complemento_18, prorrateo_pagas, num_pagas_extra, tipo_contrato, grupo, nivel, grupo_cotizacion, contacto_urgencia, telefono_urgencia, persona, irpf, nombre, apellido)
select id, activo, pert_empresa, vinculacion_id, personal, genero, antiguedad, dni, fecha_nacimiento, ss, email, movil, telefono, direccion, codigo_postal, localidad, municipio, provincia, cuenta_corriente, foto, contrato_id, observacion, desplazamiento, enviar, carpeta, pago, cv, da, ds, prev_riesgos, epi, titulos, ig_ac, uniforme, med_emerg, ens, com_antiguedad_04, com_absorbible_18, porcent_complemento_18, prorrateo_pagas, num_pagas_extra, tipo_contrato, grupo, nivel, grupo_cotizacion, contacto_urgencia, telefono_urgencia, persona, irpf, nombre, apellido
from jsonb_to_recordset($personal$
[
  {
    "id": 1705,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Sara Andrada Carballeira",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": null,
    "fecha_nacimiento": null,
    "ss": null,
    "email": "saraandrada39@gmail.com",
    "movil": "644495235",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "ˋ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Sara Andrada Carballeira - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Sara",
    "apellido": "Andrada Carballeira"
  },
  {
    "id": 1706,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Olaya Casado Secades",
    "genero": null,
    "antiguedad": "2026-06-22",
    "dni": "71789832R",
    "fecha_nacimiento": "2006-10-30",
    "ss": "281579779524",
    "email": "olayitacs@gmail.com",
    "movil": "623039813",
    "telefono": null,
    "direccion": "Calle Marcelino Fernandez 7",
    "codigo_postal": 33010,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES6601824802440201559031",
    "foto": null,
    "contrato_id": "ˌ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Olaya Casado Secades - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": true,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": true,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Olaya",
    "apellido": "Casado Secades"
  },
  {
    "id": 1707,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Alejandra Moreno García",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71976333H",
    "fecha_nacimiento": "1999-08-04",
    "ss": "331061568882",
    "email": "alejandramg81@gmail.com",
    "movil": "633408437",
    "telefono": null,
    "direccion": "Plaza Valladolid N3 IZQ",
    "codigo_postal": 33404,
    "localidad": "Las Vegas",
    "municipio": "Corvera",
    "provincia": "Asturias",
    "cuenta_corriente": "ES1900494415222710069855",
    "foto": null,
    "contrato_id": "ˍ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Alejandra Moreno García - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Alejandra",
    "apellido": "Moreno García"
  },
  {
    "id": 1708,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Alejandra Cocaña Menendez",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": null,
    "fecha_nacimiento": "1993-02-04",
    "ss": null,
    "email": "cmenendezalejandra@gmail.com",
    "movil": "600012861",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "ˎ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Alejandra Cocaña - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Alejandra",
    "apellido": "Cocaña Menendez"
  },
  {
    "id": 1709,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Laura Gómez Martínez",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "34293737R",
    "fecha_nacimiento": "2001-03-31",
    "ss": "141039994560",
    "email": "laurigm2001@gmail.com",
    "movil": "691235460",
    "telefono": null,
    "direccion": "Barrio el Torreón, nº 4, 1º D",
    "codigo_postal": 339902,
    "localidad": "El condado",
    "municipio": "Laviana",
    "provincia": "Asturias",
    "cuenta_corriente": "ES5421005995600100032939",
    "foto": null,
    "contrato_id": "ˏ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Laura Gómez Martínez - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Laura",
    "apellido": "Gómez Martínez"
  },
  {
    "id": 1710,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Diego Jesús Álvarez",
    "genero": "H",
    "antiguedad": "2026-06-22",
    "dni": "71737996F",
    "fecha_nacimiento": "2003-08-24",
    "ss": "33/1063509670",
    "email": "diegoj2003.dja@gmail.com",
    "movil": "620942592",
    "telefono": null,
    "direccion": "Calle Manolo Ponteo 2, 4°E",
    "codigo_postal": 33011,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES2600815299860006434954",
    "foto": null,
    "contrato_id": "ː",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Diego Jesús Álvarez - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Diego Jesús",
    "apellido": "Álvarez"
  },
  {
    "id": 1711,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Paula Torres Hernández",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71730156-X",
    "fecha_nacimiento": "2001-06-12",
    "ss": "33/10623760-83",
    "email": "paulaatorreshernandez@gmail.com",
    "movil": "647686046",
    "telefono": null,
    "direccion": "Camín de Pumares, 16",
    "codigo_postal": 33188,
    "localidad": "Argüelles",
    "municipio": "Siero",
    "provincia": "Asturias",
    "cuenta_corriente": "ES4614650360171764163263",
    "foto": null,
    "contrato_id": "ˑ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Paula Torres Hernández - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Paula",
    "apellido": "Torres Hernández"
  },
  {
    "id": 1712,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Cecilia Pruneda Serrata",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71737648G",
    "fecha_nacimiento": "2005-04-30",
    "ss": "331057291061",
    "email": "cprunedasrta16@gmail.com",
    "movil": "623159310",
    "telefono": null,
    "direccion": "Avenida Torrelavega, n° 66 , 4ºL",
    "codigo_postal": 33010,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES1121004599880200194792",
    "foto": null,
    "contrato_id": "˒",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Cecilia Pruneda Serrata - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": true,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Cecilia",
    "apellido": "Pruneda Serrata"
  },
  {
    "id": 1713,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Ana González Sánchez",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71965145P",
    "fecha_nacimiento": "1998-10-10",
    "ss": "331049875110",
    "email": "anagonzalezzsanchezz8@gmail.com",
    "movil": "685824866",
    "telefono": null,
    "direccion": "Hernan Cortes, N4 bajo C",
    "codigo_postal": 33403,
    "localidad": "Avilés",
    "municipio": "Avilés",
    "provincia": "Asturias",
    "cuenta_corriente": "ES5221037041510030006294",
    "foto": null,
    "contrato_id": "˓",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Ana González Sánchez - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Ana",
    "apellido": "González Sánchez"
  },
  {
    "id": 1714,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Carmen María García Vidal",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": null,
    "fecha_nacimiento": "1999-01-15",
    "ss": null,
    "email": "cmgv150199@gmail.com",
    "movil": "662312532",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "˔",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Carmen María García Vidal - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Carmen María",
    "apellido": "García Vidal"
  },
  {
    "id": 1715,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Paula García Fernández",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "34294682A",
    "fecha_nacimiento": "2004-11-15",
    "ss": "331076995704",
    "email": "paulagarciafernand@gmail.com",
    "movil": "691548845",
    "telefono": null,
    "direccion": "Calle Langreo n9 5B",
    "codigo_postal": 33960,
    "localidad": "Blimea",
    "municipio": "San Martín del Rey Aurelio",
    "provincia": "Asturias",
    "cuenta_corriente": "ES7521037432750010032157",
    "foto": null,
    "contrato_id": "˕",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Paula García - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Paula",
    "apellido": "García Fernández"
  },
  {
    "id": 1716,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Shirley Gabriela Luna Pillaguango",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71677887C",
    "fecha_nacimiento": "2002-11-26",
    "ss": "331049734458",
    "email": "gabrielalunapillaguango@gmail.com",
    "movil": "659226391",
    "telefono": null,
    "direccion": "Jose Maria Martinez Cachero 3 5C",
    "codigo_postal": 33013,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES9630590066603915995520",
    "foto": null,
    "contrato_id": "˖",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Shirley Gabriela Luna Pillaguango - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Shirley Gabriela",
    "apellido": "Luna Pillaguango"
  },
  {
    "id": 1717,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Jennifer García Díez",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71802708C",
    "fecha_nacimiento": "2000-06-03",
    "ss": "33 1053956483",
    "email": "garciadiezjennifer@gmail.com",
    "movil": "640236250",
    "telefono": null,
    "direccion": "C/ Soto del Barco n°2 esc B 1°D",
    "codigo_postal": 33012,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES0500815308150006251733",
    "foto": null,
    "contrato_id": "˗",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Jennifer García Díez - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Jennifer",
    "apellido": "García Díez"
  },
  {
    "id": 1718,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Lucía Campo Fernández",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71732033R",
    "fecha_nacimiento": "1996-04-26",
    "ss": "33-1055887389",
    "email": "luciacampofernandez@gmail.com",
    "movil": "600205578",
    "telefono": null,
    "direccion": "Calle Salas N4 5H",
    "codigo_postal": 33012,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES3230590065183045519810",
    "foto": null,
    "contrato_id": "˘",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Lucía Campo Fernández - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": true,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Lucía",
    "apellido": "Campo Fernández"
  },
  {
    "id": 1719,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Marta Bermejo Pampliega",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71730494A",
    "fecha_nacimiento": "1996-11-03",
    "ss": "331071879154",
    "email": "bermejomarta2@gmail.com",
    "movil": "645325881",
    "telefono": null,
    "direccion": "C/ Monte Naranco, 9, 2D",
    "codigo_postal": 33420,
    "localidad": "Lugones",
    "municipio": "Siero",
    "provincia": "Asturias",
    "cuenta_corriente": "ES7420480090893000093901",
    "foto": null,
    "contrato_id": "˙",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Marta Bermejo Pampliega - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Marta",
    "apellido": "Bermejo Pampliega"
  },
  {
    "id": 1720,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Noelia Díaz Fernández",
    "genero": null,
    "antiguedad": "2026-06-22",
    "dni": null,
    "fecha_nacimiento": "2003-11-12",
    "ss": null,
    "email": "645325881",
    "movil": "693330323",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "˚",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Noelia Díaz Fernández - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Noelia",
    "apellido": "Díaz Fernández"
  },
  {
    "id": 1721,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Paulo Silva de Morais",
    "genero": "H",
    "antiguedad": "2026-06-22",
    "dni": null,
    "fecha_nacimiento": "1999-02-04",
    "ss": null,
    "email": "paulosdm10@gmail.com",
    "movil": "656878605",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "˛",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Paulo Silva de Morais - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Paulo Silva",
    "apellido": "de Morais"
  },
  {
    "id": 1722,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Sofía Felicitas González Martínez",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71786923J",
    "fecha_nacimiento": "2003-07-15",
    "ss": "33-1072322324",
    "email": "sofiafelicitas2003@gmail.com",
    "movil": "684637700",
    "telefono": null,
    "direccion": "C/Aranjuez, N18, 1-G",
    "codigo_postal": 33100,
    "localidad": "Trubia",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES1300815510170006220633",
    "foto": null,
    "contrato_id": "˜",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Sofía Felicitas González Martínez - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": true,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Sofía Felicitas",
    "apellido": "González Martínez"
  },
  {
    "id": 1723,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Carla Guzmán",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": null,
    "fecha_nacimiento": "2006-01-28",
    "ss": null,
    "email": "carlaguzman215@gmail.com",
    "movil": "640147137",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "˝",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Carla Guzmán - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Carla",
    "apellido": "Guzmán"
  },
  {
    "id": 1724,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Belén Fernández García",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": null,
    "fecha_nacimiento": "1998-12-16",
    "ss": null,
    "email": "belefdezg@gmail.com",
    "movil": "644039360",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "˞",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Belén Fernández García - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Belén",
    "apellido": "Fernández García"
  },
  {
    "id": 1725,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "María Bolaños",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": null,
    "fecha_nacimiento": "2003-02-14",
    "ss": null,
    "email": "Mariuqui14@gmail.com",
    "movil": "637175684",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "˟",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\María Bolaños - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "María",
    "apellido": "Bolaños"
  },
  {
    "id": 1726,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Ainara Fernández Moral",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "58481319R",
    "fecha_nacimiento": "2004-11-16",
    "ss": "331065840502",
    "email": "ainarafdezmoral@gmail.com",
    "movil": "722549419",
    "telefono": null,
    "direccion": "Calle alonso quintanilla n22 3°D",
    "codigo_postal": 33213,
    "localidad": "Gijón",
    "municipio": "Gijón",
    "provincia": "Asturias",
    "cuenta_corriente": "ES6600496124882616040966",
    "foto": null,
    "contrato_id": "ˠ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Ainara Fernández Moral - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Ainara",
    "apellido": "Fernández Moral"
  },
  {
    "id": 1727,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Leticia Suárez Fernández",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": null,
    "fecha_nacimiento": "1993-05-16",
    "ss": null,
    "email": "leticiasuafer@hotmail.com",
    "movil": "675192064",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "ˡ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Leticia Suárez Fernández - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Leticia",
    "apellido": "Suárez Fernández"
  },
  {
    "id": 1728,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Aurea Fernández Quintana",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": null,
    "fecha_nacimiento": "1983-04-05",
    "ss": null,
    "email": "avi_9119@hotmail.com",
    "movil": "655989232",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "ˢ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Aurea Fernández - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Aurea",
    "apellido": "Fernández Quintana"
  },
  {
    "id": 1729,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Nuria Monteserín Ballesteros",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "70957757C",
    "fecha_nacimiento": "2005-06-29",
    "ss": "281572345785",
    "email": "nuriamonba@gmail.com",
    "movil": "693775047",
    "telefono": null,
    "direccion": "La Riera, 4, 4°B",
    "codigo_postal": 33011,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES5421037431270010023685",
    "foto": null,
    "contrato_id": "ˣ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Nuria Monteserín Ballesteros - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Nuria",
    "apellido": "Monteserín Ballesteros"
  },
  {
    "id": 1730,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Sergio Garrido Ledesma",
    "genero": "H",
    "antiguedad": "2026-06-22",
    "dni": "78990546J",
    "fecha_nacimiento": "2001-01-26",
    "ss": "291081407753",
    "email": "sergiogarridoledesma@gmail.com",
    "movil": "638392509",
    "telefono": null,
    "direccion": "Calle Severo Ochoa, 9 1ºD",
    "codigo_postal": 33690,
    "localidad": "Lugo de llanera",
    "municipio": "Llanera",
    "provincia": "Asturias",
    "cuenta_corriente": "ES1930230402776271338318",
    "foto": null,
    "contrato_id": "ˤ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Sergio Garrido Ledesma - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Sergio",
    "apellido": "Garrido Ledesma"
  },
  {
    "id": 1731,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Isabel González Labrador",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71788453W",
    "fecha_nacimiento": "2004-07-24",
    "ss": "28/15728616-06",
    "email": "isabelgonzalezlabrador@gmail.com\r\n@gmail.com",
    "movil": "619850863",
    "telefono": null,
    "direccion": "Martínez Marina N°17 4°F\r\nMarina, Nº17, 4ºF",
    "codigo_postal": 33009,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES1300491517112010202292",
    "foto": null,
    "contrato_id": "˥",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Isabel González Labrador - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Isabel",
    "apellido": "González Labrador"
  },
  {
    "id": 1732,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Nuria María Álvarez Alonso",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71904115C",
    "fecha_nacimiento": "1991-08-05",
    "ss": "331042705901",
    "email": "nury.368@gmail.com",
    "movil": "662530760",
    "telefono": null,
    "direccion": "CALLE REGLA 2ºA Derecha",
    "codigo_postal": 33009,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES0830590024812861154215",
    "foto": null,
    "contrato_id": "˦",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Nuria María Álvarez Alonso - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Nuria María",
    "apellido": "Álvarez Alonso"
  },
  {
    "id": 1733,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Paula Jesús Álvarez",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71737997P",
    "fecha_nacimiento": "2006-11-16",
    "ss": "331079191540",
    "email": "paula1611061212@gmail.com",
    "movil": "684639058",
    "telefono": null,
    "direccion": "Calle Manolo Ponteo 2, 4°E",
    "codigo_postal": 33011,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES8800815299870006435050",
    "foto": null,
    "contrato_id": "˧",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Paula Jesús Álvarez - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Paula Jesús",
    "apellido": "Álvarez"
  },
  {
    "id": 1734,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Alejandro Iglesias Rodríguez",
    "genero": "H",
    "antiguedad": "2026-06-22",
    "dni": "71735636Q",
    "fecha_nacimiento": "1998-04-11",
    "ss": "331056652073",
    "email": "alexigleguez@gmail.com",
    "movil": "634922741",
    "telefono": null,
    "direccion": "Avenida de Atenas 3/ 8º J",
    "codigo_postal": 33011,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES2921005768070100018915",
    "foto": null,
    "contrato_id": "˨",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Alejandro Iglesias Rodríguez - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": true,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Alejandro",
    "apellido": "Iglesias Rodríguez"
  },
  {
    "id": 1735,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Ana Merayo Martín",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "51492231S",
    "fecha_nacimiento": "1996-09-06",
    "ss": "33-1053933346",
    "email": "ani.meramar@gmail.com",
    "movil": "609217780",
    "telefono": null,
    "direccion": null,
    "codigo_postal": 33204,
    "localidad": "Caso",
    "municipio": "Gijón",
    "provincia": "Asturias",
    "cuenta_corriente": "ES4300495525532312604568",
    "foto": null,
    "contrato_id": "˩",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Ana Merayo Martín - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": true,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": true,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Ana",
    "apellido": "Merayo Martín"
  },
  {
    "id": 1736,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Andrea Estrada Álvarez",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71824248D",
    "fecha_nacimiento": "2003-04-09",
    "ss": "331064517258",
    "email": "andreatrubia03@gmail.com",
    "movil": "633903400",
    "telefono": null,
    "direccion": "Calle Coronel Esteban nº 13",
    "codigo_postal": 33100,
    "localidad": "Trubia",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES3000815320110001463250",
    "foto": null,
    "contrato_id": "˪",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Andrea Estrada Álvarez - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Andrea",
    "apellido": "Estrada Álvarez"
  },
  {
    "id": 1737,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Isabel Domingo González",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71743865B",
    "fecha_nacimiento": "2002-03-05",
    "ss": "331059842767",
    "email": "isabeelglez@gmail.com",
    "movil": "622208519",
    "telefono": null,
    "direccion": "Calle Mayorazu 18 6ºG",
    "codigo_postal": 33010,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES7521037031850010161618",
    "foto": null,
    "contrato_id": "˫",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Isabel Domingo - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Isabel",
    "apellido": "Domingo González"
  },
  {
    "id": 1738,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Laura González Balbona",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "58434964Z",
    "fecha_nacimiento": "1995-03-21",
    "ss": "331045314591",
    "email": "laurabalbona@gmail.com",
    "movil": "628798899",
    "telefono": null,
    "direccion": "Avenida de Portugal, nº 36, 1º derecha",
    "codigo_postal": 33207,
    "localidad": "Gijón",
    "municipio": "Gijón",
    "provincia": "Astuiras",
    "cuenta_corriente": "ES2501824937220201555843",
    "foto": null,
    "contrato_id": "ˬ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Laura González Balbona - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": true,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0.00",
    "com_absorbible_18": "0.00",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.02",
    "nombre": "Laura",
    "apellido": "González Balbona"
  }
]
$personal$::jsonb) as source (
  id integer,
  activo boolean,
  pert_empresa boolean,
  vinculacion_id integer,
  personal text,
  genero text,
  antiguedad date,
  dni text,
  fecha_nacimiento date,
  ss text,
  email text,
  movil text,
  telefono text,
  direccion text,
  codigo_postal integer,
  localidad text,
  municipio text,
  provincia text,
  cuenta_corriente text,
  foto text,
  contrato_id text,
  observacion text,
  desplazamiento boolean,
  enviar boolean,
  carpeta text,
  pago boolean,
  cv boolean,
  da boolean,
  ds boolean,
  prev_riesgos date,
  epi boolean,
  titulos boolean,
  ig_ac boolean,
  uniforme boolean,
  med_emerg boolean,
  ens boolean,
  com_antiguedad_04 numeric,
  com_absorbible_18 numeric,
  porcent_complemento_18 numeric,
  prorrateo_pagas boolean,
  num_pagas_extra integer,
  tipo_contrato integer,
  grupo integer,
  nivel integer,
  grupo_cotizacion text,
  contacto_urgencia text,
  telefono_urgencia text,
  persona boolean,
  irpf numeric,
  nombre text,
  apellido text
)
on conflict (id) do update set
  activo = excluded.activo,
  pert_empresa = excluded.pert_empresa,
  vinculacion_id = excluded.vinculacion_id,
  personal = excluded.personal,
  genero = excluded.genero,
  antiguedad = excluded.antiguedad,
  dni = excluded.dni,
  fecha_nacimiento = excluded.fecha_nacimiento,
  ss = excluded.ss,
  email = excluded.email,
  movil = excluded.movil,
  telefono = excluded.telefono,
  direccion = excluded.direccion,
  codigo_postal = excluded.codigo_postal,
  localidad = excluded.localidad,
  municipio = excluded.municipio,
  provincia = excluded.provincia,
  cuenta_corriente = excluded.cuenta_corriente,
  foto = excluded.foto,
  contrato_id = excluded.contrato_id,
  observacion = excluded.observacion,
  desplazamiento = excluded.desplazamiento,
  enviar = excluded.enviar,
  carpeta = excluded.carpeta,
  pago = excluded.pago,
  cv = excluded.cv,
  da = excluded.da,
  ds = excluded.ds,
  prev_riesgos = excluded.prev_riesgos,
  epi = excluded.epi,
  titulos = excluded.titulos,
  ig_ac = excluded.ig_ac,
  uniforme = excluded.uniforme,
  med_emerg = excluded.med_emerg,
  ens = excluded.ens,
  com_antiguedad_04 = excluded.com_antiguedad_04,
  com_absorbible_18 = excluded.com_absorbible_18,
  porcent_complemento_18 = excluded.porcent_complemento_18,
  prorrateo_pagas = excluded.prorrateo_pagas,
  num_pagas_extra = excluded.num_pagas_extra,
  tipo_contrato = excluded.tipo_contrato,
  grupo = excluded.grupo,
  nivel = excluded.nivel,
  grupo_cotizacion = excluded.grupo_cotizacion,
  contacto_urgencia = excluded.contacto_urgencia,
  telefono_urgencia = excluded.telefono_urgencia,
  persona = excluded.persona,
  irpf = excluded.irpf,
  nombre = excluded.nombre,
  apellido = excluded.apellido;
