truncate table public."programacion_conserjes" restart identity;
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Marta G', 'POLIDEPORTIVO LA CARISA �Yago Lamela�', '2026-04-25', '11:00', '12:30', '11:15', 'BALONMANO', 'Base Oviedo � Bosco Aviles', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Marta G', 'POLIDEPORTIVO LA CARISA �Yago Lamela�', '2026-04-25', '12:15', '13:30', '12:30', 'F�TBOL SALA', 'S.Juan Carisa �A� � Colloto', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Marta G', 'POLIDEPORTIVO LA CARISA �Yago Lamela�', '2026-04-25', '13:30', '15:00', '13:45', 'F�TBOL SALA', 'La Corredoria �A� � Vallobin', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Marta G', 'POLIDEPORTIVO LA CARISA �Yago Lamela�', '2026-04-25', '15:00', '17:00', '16:00', 'F�TBOL SALA', 'S.Juan Carisa �A� � Astur CF.', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Marta G', 'POLIDEPORTIVO LA CARISA �Yago Lamela�', '2026-04-25', '17:00', '19:00', '17:30', 'FUTBOL AMERICANO', 'Jornada de la Liga Sub -11 Flag F�tbol
Oviedo Phoenix �P. Confirmar', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Marta G', 'POLIDEPORTIVO LA CARISA �Yago Lamela�', '2026-04-25', '19:00', '21:00', '19:30', 'F�TBOL SALA', 'La Corredoria � P. B. Tur�n', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Marta G', 'POLIDEPORTIVO LA CARISA �Yago Lamela�', '2026-04-26', '11:00', '14:00', '12:00', 'F�TBOL SALA', 'C.D. Ovifem �A� � Santiago Aller', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Javier D.', 'POLIDEPORTIVO PUMARIN �Luis Riera�', '2026-04-25', '9:00', '11:30', '10:00', 'BALONCESTO', 'Oviedo Baloncesto � G. Covado.', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Javier D.', 'POLIDEPORTIVO PUMARIN �Luis Riera�', '2026-04-25', '11:30', '12:45', '12:00', 'BALONCESTO', 'Oviedo Baloncesto � Navia
Oviedo Baloncesto � Navia
Oviedo Baloncesto � Laviana', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Javier D.', 'POLIDEPORTIVO PUMARIN �Luis Riera�', '2026-04-25', '13:15', '15:30', '13:30', 'BALONCESTO', 'Oviedo Baloncesto � B. Lena 
Oviedo Baloncesto � Artchivo', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Javier D.', 'POLIDEPORTIVO PUMARIN �Luis Riera�', '2026-04-26', '9:00', '11:30', '10:00', 'BALONCESTO', 'Oviedo Baloncesto � G. Covad.', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Javier D.', 'POLIDEPORTIVO PUMARIN �Luis Riera�', '2026-04-26', '11:30', '14:30', '12:00', 'BALONCESTO', 'Oviedo Baloncesto � Auseva', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Javier D.', 'POLIDEPORTIVO PUMARIN �Luis Riera�', '2026-04-26', '15:00', '17:30', '16:00', 'BALONCESTO', 'Oviedo Baloncesto � Arbeyal', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Javier D.', 'POLIDEPORTIVO PUMARIN �Luis Riera�', '2026-04-26', '17:30', '20:30', '18:00', 'BALONCESTO', 'Oviedo Baloncesto � Artchivo', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Ivone', 'POLIDEPORTIVO SAN CLAUDIO �J. Ram�n Su�rez�', '2026-04-24', '19:45', '23:00', '20:30', 'BALONCESTO', 'C.D. Art-Chivo � C.B. Siero', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Nahikari', 'POLIDEPORTIVO SAN CLAUDIO �J. Ram�n Su�rez�', '2026-04-25', '8:30', '10:45', '9:30', 'BALONCESTO', 'C.D. Art-Chivo � C.D.B Aviles Sur A', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('David Emilio', 'POLIDEPORTIVO SAN CLAUDIO �J. Ram�n Su�rez�', '2026-04-25', '10:45', '12:45', '11:00', 'BALONCESTO', 'C.D. Art-Chivo � Asturiana Basket', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('David Emilio', 'POLIDEPORTIVO SAN CLAUDIO �J. Ram�n Su�rez�', '2026-04-25', '12:45', '15:00', '13:15', 'F�TBOL SALA', 'San Claudio �A� � Colegio Loyola-Pp. Escolapios "A"', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('David Emilio', 'POLIDEPORTIVO SAN CLAUDIO �J. Ram�n Su�rez�', '2026-04-25', '17:00', '21:00', '18:00', 'BALONCESTO', 'C.D. Art-Chivo � C�rculo Gij�n', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Ivone', 'POLIDEPORTIVO SAN CLAUDIO �J. Ram�n Su�rez�', '2026-04-26', '15:00', '17:30', '16:00', 'BALONCESTO', 'C.D. Art-Chivo � C.B. Llanes', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Ivone', 'POLIDEPORTIVO SAN CLAUDIO �J. Ram�n Su�rez�', '2026-04-26', '17:30', '21:00', '18:00', 'BALONCESTO', 'C.D. Art-Chivo � Costa Artabra', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Ivone', 'POLIDEPORTIVO SAN CLAUDIO �J. Ram�n Su�rez�', '2026-04-26', '19:30', '23:00', '20:00', 'BALONCESTO', 'C.D. Art-Chivo � C�rculo Gij�n Baloncesto', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Ana Blanca', 'POLIDEPORTIVO TUDELA AG�ERIA �Manuel Novo�', '2026-04-21', '20:00', '22:00', '20:00', 'BALONCESTO', 'Entrenamiento Palmer Mallorca
Es necesario Marcador general y marcadores de posesi�n', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Ana Blanca', 'POLIDEPORTIVO TUDELA AG�ERIA �Manuel Novo�', '2026-04-24', '20:00', '21:30', '20:00', 'PATINAJE ART�STICO', 'MONTAJE Copa Plata Federaci.
Organiza: Ovetus Patinaje Club', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Ana Blanca', 'POLIDEPORTIVO TUDELA AG�ERIA �Manuel Novo�', '2026-04-25', '9:00', '20:00', '10:00', 'PATINAJE ART�STICO', 'Copa Plata Federaci�n
Organiza: Ovetus Patinaje Club', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Ana Blanca', 'POLIDEPORTIVO TUDELA AG�ERIA �Manuel Novo�', '2026-04-26', '9:00', '15:00', '10:00', 'PATINAJE ART�STICO', 'Copa Oro Federaci�n
Organiza: Ovetus Patinaje Club', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Segundo Enrique P.', 'POLIDEPORTIVO VALLOBIN �J. Emilio Fariza�', '2026-04-25', '9:00', '12:30', '10:00', 'BALONMANO', 'Base Oviedo �', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Segundo Enrique P.', 'POLIDEPORTIVO VALLOBIN �J. Emilio Fariza�', '2026-04-25', '13:30', '15:00', '13:45', 'F�TBOL SALA', 'Astur CF.�B� � C.D. Covadonga-Casta�ales "C"', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Segundo Enrique P.', 'POLIDEPORTIVO VALLOBIN �J. Emilio Fariza�', '2026-04-25', '15:00', '18:00', '16:00', 'BALONMANO', 'Base Oviedo � Semifinal CTO', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Segundo Enrique P.', 'POLIDEPORTIVO VALLOBIN �J. Emilio Fariza�', '2026-04-25', '18:00', '19:45', '18:30', 'BALONMANO', 'Base Oviedo � BM Soria
(Divisi�n Honor Plata)
MONTAJE COMPLETO.
 Facilitar la salida por la escalera y acceso auxiliar como posible v�a de evacuaci�n.
NECESARIO VIDEO-MARCADOR', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Segundo Enrique P.', 'POLIDEPORTIVO VALLOBIN �J. Emilio Fariza�', '2026-04-25', '19:45', '23:30', '20:30', 'BALONMANO', 'Base Oviedo � Semifinal CTO', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Segundo Enrique P.', 'POLIDEPORTIVO VALLOBIN �J. Emilio Fariza�', '2026-04-26', '10:00', '12:30', '11:00', 'BALONMANO', 'Base Oviedo �  3� y 4� cto asturias', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Segundo Enrique P.', 'POLIDEPORTIVO VALLOBIN �J. Emilio Fariza�', '2026-04-26', '12:30', '15:00', '13:00', 'BALONMANO', 'Base Oviedo �  Final cto', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Segundo Enrique P.', 'POLIDEPORTIVO VALLOBIN �J. Emilio Fariza�', '2026-04-26', '15:00', '19:00', '16:00', 'BALONCESTO', 'Balonc. Arga�osa � CDB Aviles Sur', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Segundo Enrique P.', 'POLIDEPORTIVO VALLOBIN �J. Emilio Fariza�', '2026-04-26', '19:00', '23:00', '20:00', 'BALONCESTO', 'Balonc. Arga�osa � CDB Aviles Sur', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Segundo Enrique P.', 'POLIDEPORTIVO VENTANIELLES �H.  Cecchini�', '2026-04-25', '9:00', '11:00', '10:00', 'F�TBOL SALA', 'Grujoan �A�� C. Loyola', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Jos� Luis C.', 'POLIDEPORTIVO VENTANIELLES �H.  Cecchini�', '2026-04-25', '11:00', '12:15', '11:15', 'F�TBOL SALA', 'Grujoan �D�� C. Loyola', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Jos� Luis C.', 'POLIDEPORTIVO VENTANIELLES �H.  Cecchini�', '2026-04-25', '12:15', '13:30', '12:30', 'F�TBOL SALA', 'CD. Ovifem �A�� Mieresala', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Jos� Luis C.', 'POLIDEPORTIVO VENTANIELLES �H.  Cecchini�', '2026-04-25', '13:30', '15:30', '13:45', 'F�TBOL SALA', 'Grujoan �A�� F. Teresiana', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Jos� Luis C.', 'POLIDEPORTIVO VENTANIELLES �H.  Cecchini�', '2026-04-25', '15:30', '17:00', '16:00', 'F�TBOL SALA', 'Grujoan �B�� Atl. Lugones', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Jos� Luis C.', 'POLIDEPORTIVO VENTANIELLES �H.  Cecchini�', '2026-04-25', '17:00', '19:30', '17:30', 'F�TBOL SALA', 'A.  Manzaneda F.S. �A� � Alto Aller ( 3� Divisi�n) 
ES NECESARIO MARCADOR', 'programacion.csv');
insert into public."programacion_conserjes" (personal, instalacion, fecha, hora_inicio, hora_fin, hora_evento, deporte, actividad, source_file) values ('Jos� Luis C.', 'POLIDEPORTIVO VENTANIELLES �H.  Cecchini�', '2026-04-25', '19:30', '22:00', '20:00', 'F�TBOL SALA', 'A.  Manzaneda �B� � C. Arbes�', 'programacion.csv');
