-- ============================================================================
--  Sistema de Avisos: mensajería entre miembros de Coordinación, con
--  adjuntos y un motor genérico de avisos automáticos (ver avisos_motor.sql).
-- ----------------------------------------------------------------------------
--  `avisos_reglas` vive aquí (y no en avisos_motor.sql) porque `avisos.regla_id`
--  la referencia por FK y necesita existir primero.
--
--  Modelo de destinatarios: un aviso es o bien para "todos" (difusion='todos',
--  sin filas en avisos_destinatarios) o para una lista concreta de usuarios
--  (difusion='usuarios', una fila por destinatario en avisos_destinatarios).
--  No hay alcance por contrato: quien tiene la pestaña ve su bandeja según
--  a quién se dirigió el aviso, no según los contratos que gestiona.
--
--  `avisos.origen` distingue manual (creado por un usuario, autor_id
--  obligatorio) de automatico (creado por el motor de reglas, autor_id nulo,
--  regla_id obligatorio) — ver el constraint avisos_origen_consistency.
--
--  Adjuntos: se reutiliza el mismo bucket de Storage que ya usa Candidaturas
--  (`candidate-cvs`, ver curriculos/config.js y coordinacion/config.js) bajo
--  el prefijo `avisos/<aviso_id>/...`, igual que Candidaturas ya namespacea
--  por `<source>/<candidateId>/...` dentro del mismo bucket. La policy de
--  Storage `authenticated_can_manage_candidate_cvs` (supabase/schema.sql) ya
--  da acceso de lectura/escritura a cualquier authenticated en todo el
--  bucket, así que no hace falta ninguna policy de Storage nueva.
--
--  Requiere: coordinacion_roles.sql (is_coordinacion_admin,
--            coordinacion_usuarios), contratos.sql, personal.sql.
-- ============================================================================

create table if not exists public.avisos_reglas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  tabla_origen text not null,
  activo boolean not null default true,
  plantilla_titulo text not null,
  plantilla_cuerpo text not null,
  difusion text not null default 'usuarios',
  destinatarios_usuario_ids uuid[] not null default '{}',
  rol text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint avisos_reglas_nombre_unique unique (nombre),
  constraint avisos_reglas_tabla_origen_check
    check (tabla_origen in ('personal_bajas', 'personal_permisos')),
  constraint avisos_reglas_difusion_check
    check (difusion in ('todos', 'usuarios', 'rol')),
  constraint avisos_reglas_rol_check
    check (rol is null or rol in ('admin', 'coordinator', 'area_coordinator', 'viewer'))
);

comment on table public.avisos_reglas is
  'Motor genérico de avisos automáticos: qué tablas origen disparan un aviso, con qué texto (placeholders {{clave}} resueltos desde el contexto que arma cada trigger) y a quién. Añadir una tabla origen nueva exige un trigger de código (avisos_motor.sql); editar destinatarios/texto de una tabla ya conectada no.';
comment on column public.avisos_reglas.tabla_origen is
  'Tabla que dispara la regla. Lista cerrada: cada valor nuevo requiere también su trigger en avisos_motor.sql.';
comment on column public.avisos_reglas.destinatarios_usuario_ids is
  'Solo se usa cuando difusion=usuarios.';
comment on column public.avisos_reglas.rol is
  'Solo se usa cuando difusion=rol: se avisa a todos los coordinacion_usuarios activos con ese rol.';

create index if not exists avisos_reglas_tabla_origen_idx
on public.avisos_reglas (tabla_origen, activo);

create or replace function public.set_avisos_reglas_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_avisos_reglas_updated_at on public.avisos_reglas;
create trigger set_avisos_reglas_updated_at
before update on public.avisos_reglas
for each row
execute function public.set_avisos_reglas_updated_at();

-- ---------------------------------------------------------------------------
--  avisos
-- ---------------------------------------------------------------------------
create table if not exists public.avisos (
  id bigint generated by default as identity primary key,
  autor_id uuid references auth.users (id),
  origen text not null default 'manual',
  regla_id bigint references public.avisos_reglas (id),
  titulo text not null,
  cuerpo text,
  difusion text not null default 'usuarios',
  contrato_id integer references public.contratos (id),
  personal_id integer references public.personal (id),
  creado_en timestamptz not null default now(),
  constraint avisos_origen_check check (origen in ('manual', 'automatico')),
  constraint avisos_difusion_check check (difusion in ('todos', 'usuarios')),
  constraint avisos_origen_consistency check (
    (origen = 'manual' and autor_id is not null and regla_id is null)
    or (origen = 'automatico' and autor_id is null and regla_id is not null)
  )
);

comment on table public.avisos is
  'Mensaje/aviso, manual o generado por avisos_reglas. contrato_id/personal_id son opcionales, solo para asociar el aviso a algo concreto y poder filtrar.';
comment on column public.avisos.difusion is
  'todos = visible para cualquier usuario con la pestaña; usuarios = solo para quien esté en avisos_destinatarios.';

create index if not exists avisos_creado_en_idx on public.avisos (creado_en desc);
create index if not exists avisos_contrato_id_idx on public.avisos (contrato_id);
create index if not exists avisos_personal_id_idx on public.avisos (personal_id);
create index if not exists avisos_autor_id_idx on public.avisos (autor_id);

-- ---------------------------------------------------------------------------
--  avisos_destinatarios
-- ---------------------------------------------------------------------------
create table if not exists public.avisos_destinatarios (
  aviso_id bigint not null references public.avisos (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (aviso_id, user_id)
);

create index if not exists avisos_destinatarios_user_id_idx
on public.avisos_destinatarios (user_id);

-- ---------------------------------------------------------------------------
--  avisos_lecturas
-- ---------------------------------------------------------------------------
create table if not exists public.avisos_lecturas (
  aviso_id bigint not null references public.avisos (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  leido_en timestamptz not null default now(),
  primary key (aviso_id, user_id)
);

-- ---------------------------------------------------------------------------
--  avisos_adjuntos
-- ---------------------------------------------------------------------------
create table if not exists public.avisos_adjuntos (
  id bigint generated by default as identity primary key,
  aviso_id bigint not null references public.avisos (id) on delete cascade,
  nombre_archivo text not null,
  ruta_storage text not null,
  tipo_mime text,
  tamano_bytes bigint,
  subido_en timestamptz not null default now()
);

create index if not exists avisos_adjuntos_aviso_id_idx
on public.avisos_adjuntos (aviso_id);

-- ---------------------------------------------------------------------------
--  Directorio mínimo de usuarios (para el selector de destinatarios).
--  `coordinacion_usuarios` solo se puede leer la fila propia o si eres admin
--  (coordinacion_roles.sql); esta vista expone id+nombre+activo a cualquier
--  authenticated sin pasar por esa RLS (no lleva security_invoker=true a
--  propósito, corre con los privilegios del owner). No expone `rol`.
-- ---------------------------------------------------------------------------
drop view if exists public.coordinacion_usuarios_directorio;
create view public.coordinacion_usuarios_directorio as
select user_id, nombre, activo
from public.coordinacion_usuarios;

comment on view public.coordinacion_usuarios_directorio is
  'Directorio de usuarios (id+nombre+activo, sin rol) visible para cualquier authenticated, para selectores de destinatarios en Avisos. Bypassa deliberadamente la RLS de coordinacion_usuarios.';

grant select on public.coordinacion_usuarios_directorio to authenticated;

-- ---------------------------------------------------------------------------
--  avisos_detalle: vista de listado. security_invoker=true a propósito: la
--  visibilidad de fila la decide la RLS de avisos/avisos_lecturas, no esta
--  vista. El nombre del autor sale del directorio (bypassa RLS de
--  coordinacion_usuarios); contrato/personal si el visor no tiene alcance
--  sobre ellos salen a NULL (misma prudencia que el resto de la app).
-- ---------------------------------------------------------------------------
drop view if exists public.avisos_detalle;
create or replace view public.avisos_detalle as
select
  a.id,
  a.autor_id,
  au.nombre as autor_nombre,
  a.origen,
  a.regla_id,
  ar.nombre as regla_nombre,
  a.titulo,
  a.cuerpo,
  a.difusion,
  a.contrato_id,
  c.contrato as contrato_nombre,
  a.personal_id,
  p.personal as personal_nombre,
  a.creado_en,
  (l.user_id is not null) as leido,
  l.leido_en,
  exists (
    select 1 from public.avisos_adjuntos ad where ad.aviso_id = a.id
  ) as tiene_adjuntos
from public.avisos a
left join public.coordinacion_usuarios_directorio au on au.user_id = a.autor_id
left join public.avisos_reglas ar on ar.id = a.regla_id
left join public.contratos c on c.id = a.contrato_id
left join public.personal p on p.id = a.personal_id
left join public.avisos_lecturas l on l.aviso_id = a.id and l.user_id = auth.uid();

alter view public.avisos_detalle set (security_invoker = true);

grant select on public.avisos_detalle to authenticated;
