-- ============================================================================
--  Preparaciones de facturacion: calculo guardado y versionado, y su vinculo
--  con los registros (horas) que lo componen y con la factura real emitida.
-- ----------------------------------------------------------------------------
--  Requiere contratos_facturacion.sql, contratos_funciones_servicio.sql,
--  registros.sql y coordinacion_contrato_id_sets.sql.
--
--  Una preparacion es un "Calcular" guardado de la pestaña Preparacion de
--  facturas: fija que registros entraron, con que tarifa, y el total
--  resultante. Volver a calcular el mismo contrato+agrupacion+periodo no pisa
--  la anterior: la sustituye dejando rastro (estado 'anulada', sustituye_a),
--  igual que nominas.emitir_nomina.
--
--  Granularidad (contratos_facturacion_preparaciones.servicio_ids/funcion_id):
--    servicio_ids vacio/null   -> el contrato completo (todos los servicios)
--    servicio_ids con 1+ ids   -> un grupo de servicios, todas sus funciones
--                                  juntas (caso normal: una factura por
--                                  servicio). Puede haber varios ids porque
--                                  una funcion compartida entre servicios los
--                                  fusiona (ver contratos_funciones_servicio.sql):
--                                  esos servicios se agrupan siempre juntos,
--                                  las horas no se reparten entre ellos.
--    servicio_ids + funcion_id -> una funcion separada dentro de su(s) servicio(s)
--
--  Una factura nunca cruza contratos: contrato_id es unico y obligatorio.
-- ============================================================================

create table if not exists public.contratos_facturacion_preparaciones (
  id bigint generated by default as identity primary key,
  contrato_id integer not null references public.contratos (id) on update cascade on delete restrict,
  servicio_ids bigint[],
  funcion_id integer references public.funciones (id) on update cascade on delete restrict,
  fecha_desde date not null,
  fecha_hasta date not null,
  estado text not null default 'vigente',
  sustituye_a bigint references public.contratos_facturacion_preparaciones (id) on update cascade on delete set null,
  anulada_motivo text,
  anulada_en timestamptz,
  contrato_facturacion_id bigint references public.contratos_facturacion (id) on update cascade on delete set null,
  base_imponible numeric(14, 2) not null default 0,
  iva numeric(14, 2) not null default 0,
  total numeric(14, 2) not null default 0,
  horas_diurnas numeric(10, 2) not null default 0,
  horas_nocturnas numeric(10, 2) not null default 0,
  observacion text,
  generada_por_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contratos_facturacion_preparaciones_estado_chk
    check (estado in ('vigente', 'anulada')),
  constraint contratos_facturacion_preparaciones_rango_chk
    check (fecha_hasta >= fecha_desde),
  constraint contratos_facturacion_preparaciones_funcion_requiere_servicio_chk
    check (funcion_id is null or coalesce(array_length(servicio_ids, 1), 0) > 0)
);

comment on table public.contratos_facturacion_preparaciones is
  'Calculo de "Preparacion de facturas" guardado y congelado. Volver a calcular el mismo contrato+agrupacion+periodo no pisa la anterior: queda anulada (sustituye_a) y la nueva la referencia, con rastro completo. estado: vigente = la version actual; anulada = reemplazada al regenerar o anulada a mano (conserva sus lineas como historico).';
comment on column public.contratos_facturacion_preparaciones.servicio_ids is
  'Vacio/nulo = preparacion de todo el contrato. Con ids = preparacion de ese grupo de servicios (todas sus funciones, salvo que funcion_id tambien se informe). Normalizado (distinct, ordenado) para poder comparar por igualdad al detectar regeneraciones.';
comment on column public.contratos_facturacion_preparaciones.contrato_facturacion_id is
  'Factura real a la que dio lugar esta preparacion, cuando existe. Nulo mientras solo es un calculo guardado (fase de "crear factura desde preparacion" pendiente).';

create table if not exists public.contratos_facturacion_lineas (
  id bigint generated by default as identity primary key,
  contrato_id integer not null references public.contratos (id) on update cascade on delete restrict,
  preparacion_id bigint references public.contratos_facturacion_preparaciones (id) on update cascade on delete cascade,
  contrato_facturacion_id bigint references public.contratos_facturacion (id) on update cascade on delete set null,
  registro_id bigint not null references public.registros (id) on update cascade on delete restrict,
  instalacion_id integer references public.instalaciones (id) on update cascade on delete set null,
  funcion_id integer references public.funciones (id) on update cascade on delete set null,
  horas_diurnas numeric(10, 2) not null default 0,
  horas_nocturnas numeric(10, 2) not null default 0,
  precio_01 numeric(14, 4),
  precio_02 numeric(14, 4),
  tipo_precio text,
  importe numeric(14, 2),
  created_at timestamptz not null default now(),
  constraint contratos_facturacion_lineas_origen_chk
    check (preparacion_id is not null or contrato_facturacion_id is not null)
);

comment on table public.contratos_facturacion_lineas is
  'Vinculo atomico registro (jornada) <-> preparacion/factura. Es la trazabilidad que sustituye a registros.factura: por cada registro se sabe en que preparacion y, en su caso, en que factura entro. Un registro solo puede estar "activo" (preparacion vigente o factura real) en una linea a la vez; lo blinda el trigger validate_contratos_facturacion_lineas_unicidad y no un UNIQUE simple, porque el historico de preparaciones anuladas debe conservar sus lineas.';
comment on column public.contratos_facturacion_lineas.importe is
  'Importe de esta linea en el momento de generarse. Nulo en los vinculos migrados desde el antiguo registros.factura, donde no se conserva el desglose por registro.';

create index if not exists contratos_facturacion_preparaciones_contrato_idx
on public.contratos_facturacion_preparaciones (contrato_id, fecha_desde, fecha_hasta);
create index if not exists contratos_facturacion_preparaciones_estado_idx
on public.contratos_facturacion_preparaciones (estado);
create index if not exists contratos_facturacion_preparaciones_factura_idx
on public.contratos_facturacion_preparaciones (contrato_facturacion_id);

create index if not exists contratos_facturacion_lineas_contrato_idx
on public.contratos_facturacion_lineas (contrato_id);
create index if not exists contratos_facturacion_lineas_preparacion_idx
on public.contratos_facturacion_lineas (preparacion_id);
create index if not exists contratos_facturacion_lineas_factura_idx
on public.contratos_facturacion_lineas (contrato_facturacion_id);
create index if not exists contratos_facturacion_lineas_registro_idx
on public.contratos_facturacion_lineas (registro_id);

drop trigger if exists set_contratos_facturacion_preparaciones_updated_at on public.contratos_facturacion_preparaciones;
create trigger set_contratos_facturacion_preparaciones_updated_at before update on public.contratos_facturacion_preparaciones
for each row execute function public.set_contratos_facturacion_updated_at();

-- Un registro solo puede estar "activo" (vinculado a una preparacion vigente
-- o a una factura real) en una linea a la vez. Las lineas de preparaciones
-- anuladas no cuentan: quedan como historico, libres para una nueva.
create or replace function public.validate_contratos_facturacion_lineas_unicidad()
returns trigger
language plpgsql
as $$
declare
  v_conflicto record;
begin
  select l.id, l.preparacion_id, l.contrato_facturacion_id
    into v_conflicto
  from public.contratos_facturacion_lineas l
  left join public.contratos_facturacion_preparaciones p on p.id = l.preparacion_id
  where l.registro_id = new.registro_id
    and l.id is distinct from new.id
    and (l.contrato_facturacion_id is not null or p.estado = 'vigente')
  limit 1;

  if found then
    if v_conflicto.contrato_facturacion_id is not null then
      raise exception 'El registro % ya está vinculado a la factura #%.',
        new.registro_id, v_conflicto.contrato_facturacion_id;
    else
      raise exception 'El registro % ya está incluido en la preparación vigente #%.',
        new.registro_id, v_conflicto.preparacion_id;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists validate_contratos_facturacion_lineas_unicidad on public.contratos_facturacion_lineas;
create trigger validate_contratos_facturacion_lineas_unicidad
before insert or update of registro_id, preparacion_id, contrato_facturacion_id
on public.contratos_facturacion_lineas
for each row
execute function public.validate_contratos_facturacion_lineas_unicidad();

alter table public.contratos_facturacion_preparaciones enable row level security;
alter table public.contratos_facturacion_lineas enable row level security;

grant select, insert, update, delete on public.contratos_facturacion_preparaciones to authenticated;
grant select, insert, update, delete on public.contratos_facturacion_lineas to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "contratos_facturacion_preparaciones_read" on public.contratos_facturacion_preparaciones;
create policy "contratos_facturacion_preparaciones_read" on public.contratos_facturacion_preparaciones for select to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_readable_contrato_ids())
);
drop policy if exists "contratos_facturacion_preparaciones_write" on public.contratos_facturacion_preparaciones;
create policy "contratos_facturacion_preparaciones_write" on public.contratos_facturacion_preparaciones for all to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
)
with check (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
);

drop policy if exists "contratos_facturacion_lineas_read" on public.contratos_facturacion_lineas;
create policy "contratos_facturacion_lineas_read" on public.contratos_facturacion_lineas for select to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_readable_contrato_ids())
);
drop policy if exists "contratos_facturacion_lineas_write" on public.contratos_facturacion_lineas;
create policy "contratos_facturacion_lineas_write" on public.contratos_facturacion_lineas for all to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
)
with check (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
);

-- ----------------------------------------------------------------------------
--  guardar_preparacion_facturacion: persiste un calculo de "Preparacion de
--  facturas". Si ya existe una preparacion vigente identica (mismo contrato,
--  agrupacion y periodo), exige p_reemplazar=true para regenerar: la anterior
--  queda anulada (con rastro) y la nueva la referencia via sustituye_a.
--  security invoker: el RLS de ambas tablas ya limita a los contratos que el
--  usuario puede gestionar.
-- ----------------------------------------------------------------------------
drop function if exists public.guardar_preparacion_facturacion(
  integer, date, date, jsonb, numeric, numeric, numeric, bigint, integer, boolean, text, numeric, numeric
);

create or replace function public.guardar_preparacion_facturacion(
  p_contrato_id integer,
  p_fecha_desde date,
  p_fecha_hasta date,
  p_lineas jsonb,
  p_base_imponible numeric,
  p_iva numeric,
  p_total numeric,
  p_servicio_ids bigint[] default null,
  p_funcion_id integer default null,
  p_reemplazar boolean default false,
  p_observacion text default null,
  p_horas_diurnas numeric default 0,
  p_horas_nocturnas numeric default 0
)
returns bigint
language plpgsql
volatile
security invoker
set search_path = public
as $$
declare
  v_id bigint;
  v_previa bigint;
  v_previa_facturada boolean;
  v_ajenos integer;
  v_servicio_ids bigint[];
begin
  if p_fecha_desde is null or p_fecha_hasta is null then
    raise exception 'La preparación necesita un periodo (desde y hasta).';
  end if;
  if p_fecha_hasta < p_fecha_desde then
    raise exception 'La fecha hasta no puede ser anterior a la fecha desde.';
  end if;
  if jsonb_typeof(p_lineas) is distinct from 'array' or jsonb_array_length(p_lineas) = 0 then
    raise exception 'La preparación no tiene registros que facturar.';
  end if;

  -- Normalizado (distinct + orden) para que la comparacion de igualdad al
  -- buscar una preparacion previa idéntica sea estable sin importar el orden
  -- en que llegue el array.
  v_servicio_ids := coalesce((
    select array_agg(distinct x order by x)
    from unnest(coalesce(p_servicio_ids, '{}'::bigint[])) as x
    where x is not null
  ), '{}'::bigint[]);
  if array_length(v_servicio_ids, 1) is null then
    v_servicio_ids := null;
  end if;

  if p_funcion_id is not null and v_servicio_ids is null then
    raise exception 'Para separar por función hace falta indicar también el servicio.';
  end if;

  -- Una factura nunca cruza contratos: ningun registro de las lineas puede
  -- facturarse en otro contrato distinto del indicado. Se compara contra el
  -- contrato facturable (propio, salvo redireccion en
  -- registros_facturacion_destino), no contra registros.contrato_id a secas,
  -- para permitir facturar en el contrato B horas trabajadas en el A.
  select count(*) into v_ajenos
  from jsonb_array_elements(p_lineas) as l
  join public.registros r on r.id = (l ->> 'registro_id')::bigint
  left join public.registros_facturacion_destino rfd on rfd.registro_id = r.id
  where coalesce(rfd.contrato_id, r.contrato_id) is distinct from p_contrato_id;

  if v_ajenos > 0 then
    raise exception 'Hay % registro(s) que no pertenecen al contrato indicado.', v_ajenos;
  end if;

  select p.id, p.contrato_facturacion_id is not null
    into v_previa, v_previa_facturada
  from public.contratos_facturacion_preparaciones p
  where p.contrato_id = p_contrato_id
    and coalesce(p.servicio_ids, '{}'::bigint[]) = coalesce(v_servicio_ids, '{}'::bigint[])
    and coalesce(p.funcion_id, 0) = coalesce(p_funcion_id, 0)
    and p.fecha_desde = p_fecha_desde
    and p.fecha_hasta = p_fecha_hasta
    and p.estado = 'vigente';

  if v_previa is not null then
    if not p_reemplazar then
      raise exception 'Ya hay una preparación vigente para este contrato, agrupación y periodo (#%). Regenérala explícitamente para sustituirla.', v_previa;
    end if;
    if v_previa_facturada then
      raise exception 'La preparación #% ya está vinculada a una factura real; no se puede regenerar automáticamente.', v_previa;
    end if;
    update public.contratos_facturacion_preparaciones
    set estado = 'anulada', anulada_en = now(),
        anulada_motivo = coalesce(anulada_motivo, 'Reemplazada al regenerar la preparación')
    where id = v_previa;
  end if;

  insert into public.contratos_facturacion_preparaciones (
    contrato_id, servicio_ids, funcion_id, fecha_desde, fecha_hasta,
    sustituye_a, base_imponible, iva, total, horas_diurnas, horas_nocturnas,
    observacion, generada_por_email
  ) values (
    p_contrato_id, v_servicio_ids, p_funcion_id, p_fecha_desde, p_fecha_hasta,
    v_previa, coalesce(p_base_imponible, 0), coalesce(p_iva, 0), coalesce(p_total, 0),
    coalesce(p_horas_diurnas, 0), coalesce(p_horas_nocturnas, 0),
    p_observacion,
    nullif(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'email', '')
  )
  returning id into v_id;

  insert into public.contratos_facturacion_lineas (
    contrato_id, preparacion_id, registro_id, instalacion_id, funcion_id,
    horas_diurnas, horas_nocturnas, precio_01, precio_02, tipo_precio, importe
  )
  select
    p_contrato_id, v_id,
    (l ->> 'registro_id')::bigint,
    nullif(l ->> 'instalacion_id', '')::integer,
    nullif(l ->> 'funcion_id', '')::integer,
    coalesce((l ->> 'horas_diurnas')::numeric, 0),
    coalesce((l ->> 'horas_nocturnas')::numeric, 0),
    nullif(l ->> 'precio_01', '')::numeric,
    nullif(l ->> 'precio_02', '')::numeric,
    l ->> 'tipo_precio',
    nullif(l ->> 'importe', '')::numeric
  from jsonb_array_elements(p_lineas) as l;

  return v_id;
end;
$$;

revoke all on function public.guardar_preparacion_facturacion(
  integer, date, date, jsonb, numeric, numeric, numeric, bigint[], integer, boolean, text, numeric, numeric
) from public;
grant execute on function public.guardar_preparacion_facturacion(
  integer, date, date, jsonb, numeric, numeric, numeric, bigint[], integer, boolean, text, numeric, numeric
) to authenticated;

-- ----------------------------------------------------------------------------
--  anular_preparacion_facturacion: anula a mano una preparacion vigente que
--  no ha llegado a convertirse en factura (o aunque lo haya hecho, para
--  corregir un error). No borra: deja rastro, igual que anular_nomina.
-- ----------------------------------------------------------------------------
create or replace function public.anular_preparacion_facturacion(p_id bigint, p_motivo text default null)
returns void
language plpgsql
volatile
security invoker
set search_path = public
as $$
begin
  update public.contratos_facturacion_preparaciones
  set estado = 'anulada', anulada_en = now(),
      anulada_motivo = coalesce(nullif(trim(p_motivo), ''), 'Anulada a mano')
  where id = p_id
    and estado = 'vigente';

  if not found then
    raise exception 'La preparación #% no existe o ya estaba anulada.', p_id;
  end if;
end;
$$;

revoke all on function public.anular_preparacion_facturacion(bigint, text) from public;
grant execute on function public.anular_preparacion_facturacion(bigint, text) to authenticated;

-- ----------------------------------------------------------------------------
--  eliminar_preparacion_facturacion: borrado real (no deja rastro), a
--  diferencia de anular. Solo para preparaciones que nunca llegaron a
--  convertirse en factura -si contrato_facturacion_id esta informado, se
--  bloquea, para no romper el rastro de una factura real ya emitida-.
--  contratos_facturacion_lineas se limpia solo via el ON DELETE CASCADE de
--  preparacion_id. security invoker: el RLS de escritura ya limita a los
--  contratos que el usuario puede gestionar.
-- ----------------------------------------------------------------------------
create or replace function public.eliminar_preparacion_facturacion(p_id bigint)
returns void
language plpgsql
volatile
security invoker
set search_path = public
as $$
declare
  v_factura bigint;
begin
  select contrato_facturacion_id into v_factura
  from public.contratos_facturacion_preparaciones
  where id = p_id;

  if not found then
    raise exception 'La preparación #% no existe.', p_id;
  end if;

  if v_factura is not null then
    raise exception 'La preparación #% está vinculada a la factura #%; no se puede eliminar, solo anular.', p_id, v_factura;
  end if;

  delete from public.contratos_facturacion_preparaciones where id = p_id;
end;
$$;

revoke all on function public.eliminar_preparacion_facturacion(bigint) from public;
grant execute on function public.eliminar_preparacion_facturacion(bigint) to authenticated;
