-- Facturacion de contratos: periodos, presupuestos, estados y facturas.
-- Requiere contratos.sql y coordinacion_contrato_id_sets.sql.

create table if not exists public.contratos_estado_facturas (
  id integer generated by default as identity primary key,
  registro integer,
  estado text not null unique,
  descripcion text
);

insert into public.contratos_estado_facturas (id, registro, estado, descripcion)
values
  (1, 1000, 'Remitida', null),
  (2, 1200, 'REC', 'Registrada en el registro electronico REC'),
  (3, 1300, 'RCF', 'Registrada en RCF'),
  (4, 2400, 'Contabilizada', 'Contabilizada la obligacion reconocida'),
  (5, 2500, 'Pagada', 'Factura pagada'),
  (6, 9000, 'Rechazada', 'Factura rechazada'),
  (7, 9100, 'F. Rectificativa', 'Factura rectificativa')
on conflict (id) do update set
  registro = excluded.registro,
  estado = excluded.estado,
  descripcion = excluded.descripcion;

select setval(
  pg_get_serial_sequence('public.contratos_estado_facturas', 'id'),
  coalesce((select max(id) from public.contratos_estado_facturas), 1),
  true
);

create table if not exists public.contratos_fechas (
  id bigint generated by default as identity primary key,
  contrato_id integer not null references public.contratos(id) on update cascade on delete restrict,
  fecha_inicio date not null,
  fecha_fin date not null,
  concepto text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contratos_fechas_rango_check check (fecha_fin >= fecha_inicio)
);

create table if not exists public.contratos_presupuestos (
  id bigint generated by default as identity primary key,
  contrato_id integer not null references public.contratos(id) on update cascade on delete restrict,
  periodo text not null,
  presupuesto numeric(14, 2) not null default 0,
  fecha_inicio date not null,
  fecha_fin date not null,
  observacion text,
  porcentaje_iva numeric(7, 4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contratos_presupuestos_importe_check check (presupuesto >= 0),
  constraint contratos_presupuestos_rango_check check (fecha_fin >= fecha_inicio),
  constraint contratos_presupuestos_iva_check
    check (porcentaje_iva is null or porcentaje_iva between 0 and 1)
);

create table if not exists public.contratos_funciones (
  id bigint generated by default as identity primary key,
  contrato_id integer not null references public.contratos(id) on update cascade on delete restrict,
  funcion_id integer references public.funciones(id) on update cascade on delete restrict,
  modalidad_id integer references public.modalidades(id) on update cascade on delete restrict,
  observacion text,
  grupo text,
  precio_01 numeric(14, 4),
  precio_02 numeric(14, 4),
  tipo_precio text,
  activo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contratos_facturacion (
  id bigint generated by default as identity primary key,
  fecha date not null,
  tipo integer,
  serie text,
  n_documento text,
  referencia text,
  base_imponible numeric(14, 2) not null default 0,
  iva numeric(14, 2) not null default 0,
  total numeric(14, 2) not null default 0,
  moneda text not null default 'EURO',
  cod_cliente text,
  cliente text,
  contrato_estado_factura_id integer references public.contratos_estado_facturas(id)
    on update cascade on delete set null,
  contrato_id integer not null references public.contratos(id) on update cascade on delete restrict,
  tipo_iva numeric(7, 4),
  cobrada boolean not null default false,
  fecha_cobro date,
  observacion text,
  presupuesto_id bigint references public.contratos_presupuestos(id)
    on update cascade on delete set null,
  unidades numeric(14, 4),
  precio_unitario numeric(14, 4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contratos_facturacion_iva_check check (tipo_iva is null or tipo_iva between 0 and 1),
  constraint contratos_facturacion_cobro_check check (not cobrada or fecha_cobro is not null)
);

-- Los Excel historicos contienen presupuestos aun sin importe/fechas y cinco
-- facturas anteriores a la asignacion de contrato. Se conservan como pendientes
-- de clasificar en lugar de inventar valores.
alter table public.contratos_presupuestos alter column presupuesto drop not null;
alter table public.contratos_presupuestos alter column fecha_inicio drop not null;
alter table public.contratos_presupuestos alter column fecha_fin drop not null;
alter table public.contratos_facturacion alter column contrato_id drop not null;

create index if not exists contratos_fechas_contrato_rango_idx
on public.contratos_fechas (contrato_id, fecha_inicio, fecha_fin);
create index if not exists contratos_presupuestos_contrato_rango_idx
on public.contratos_presupuestos (contrato_id, fecha_inicio, fecha_fin);
create index if not exists contratos_funciones_contrato_idx
on public.contratos_funciones (contrato_id);
create index if not exists contratos_facturacion_contrato_fecha_idx
on public.contratos_facturacion (contrato_id, fecha desc);
create index if not exists contratos_facturacion_presupuesto_idx
on public.contratos_facturacion (presupuesto_id);
create index if not exists contratos_facturacion_estado_idx
on public.contratos_facturacion (contrato_estado_factura_id);

create or replace function public.set_contratos_facturacion_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_contratos_fechas_updated_at on public.contratos_fechas;
create trigger set_contratos_fechas_updated_at before update on public.contratos_fechas
for each row execute function public.set_contratos_facturacion_updated_at();
drop trigger if exists set_contratos_presupuestos_updated_at on public.contratos_presupuestos;
create trigger set_contratos_presupuestos_updated_at before update on public.contratos_presupuestos
for each row execute function public.set_contratos_facturacion_updated_at();
drop trigger if exists set_contratos_funciones_updated_at on public.contratos_funciones;
create trigger set_contratos_funciones_updated_at before update on public.contratos_funciones
for each row execute function public.set_contratos_facturacion_updated_at();
drop trigger if exists set_contratos_facturacion_updated_at on public.contratos_facturacion;
create trigger set_contratos_facturacion_updated_at before update on public.contratos_facturacion
for each row execute function public.set_contratos_facturacion_updated_at();

alter table public.contratos_estado_facturas enable row level security;
alter table public.contratos_fechas enable row level security;
alter table public.contratos_presupuestos enable row level security;
alter table public.contratos_funciones enable row level security;
alter table public.contratos_facturacion enable row level security;

grant select, insert, update, delete on public.contratos_estado_facturas to authenticated;
grant select, insert, update, delete on public.contratos_fechas to authenticated;
grant select, insert, update, delete on public.contratos_presupuestos to authenticated;
grant select, insert, update, delete on public.contratos_funciones to authenticated;
grant select, insert, update, delete on public.contratos_facturacion to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "contratos_estado_facturas_read" on public.contratos_estado_facturas;
create policy "contratos_estado_facturas_read" on public.contratos_estado_facturas
for select to authenticated using (true);
drop policy if exists "contratos_estado_facturas_admin_write" on public.contratos_estado_facturas;
create policy "contratos_estado_facturas_admin_write" on public.contratos_estado_facturas
for all to authenticated
using ((select public.is_coordinacion_admin()))
with check ((select public.is_coordinacion_admin()));

drop policy if exists "contratos_fechas_read" on public.contratos_fechas;
create policy "contratos_fechas_read" on public.contratos_fechas for select to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_readable_contrato_ids())
);
drop policy if exists "contratos_fechas_write" on public.contratos_fechas;
create policy "contratos_fechas_write" on public.contratos_fechas for all to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
)
with check (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
);

drop policy if exists "contratos_presupuestos_read" on public.contratos_presupuestos;
create policy "contratos_presupuestos_read" on public.contratos_presupuestos for select to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_readable_contrato_ids())
);
drop policy if exists "contratos_presupuestos_write" on public.contratos_presupuestos;
create policy "contratos_presupuestos_write" on public.contratos_presupuestos for all to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
)
with check (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
);

drop policy if exists "contratos_funciones_read" on public.contratos_funciones;
create policy "contratos_funciones_read" on public.contratos_funciones for select to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_readable_contrato_ids())
);
drop policy if exists "contratos_funciones_write" on public.contratos_funciones;
create policy "contratos_funciones_write" on public.contratos_funciones for all to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
)
with check (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
);

drop policy if exists "contratos_facturacion_read" on public.contratos_facturacion;
create policy "contratos_facturacion_read" on public.contratos_facturacion for select to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_readable_contrato_ids())
);
drop policy if exists "contratos_facturacion_write" on public.contratos_facturacion;
create policy "contratos_facturacion_write" on public.contratos_facturacion for all to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
)
with check (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
);
