-- ============================================================================
--  contratos_funciones_servicios — asocia cada tarifa (contrato+funcion) con
--  uno o VARIOS servicios, para poder agrupar "Preparación de facturas" por
--  servicio.
-- ----------------------------------------------------------------------------
--  registros.servicio_id casi nunca esta relleno (solo llega via actividad:
--  ~2% de los registros, incluso en contratos con varios servicios dados de
--  alta), asi que la agrupacion por servicio no puede apoyarse en el registro
--  individual. Se resuelve aqui, en la tarifa, que es donde vive de forma
--  estable la relacion "estas funciones son de este servicio".
--
--  Es N:M (no una FK unica) porque una misma funcion puede compartirse entre
--  varios servicios (p.ej. "Monitorado Deportivo" en salas y en piscinas). En
--  ese caso NO se reparten las horas por servicio: los servicios etiquetados
--  en una misma funcion se agrupan siempre juntos en la misma preparacion, y
--  esa union se contagia (si otra funcion enlaza dos de esos servicios con un
--  tercero, los tres acaban en la misma preparacion). La resolucion de estos
--  "componentes conexos" vive en el cliente (facturacion.js), no aqui.
--
--  Requiere contratos_facturacion.sql, servicios.sql y contrato_servicios.sql.
-- ============================================================================

drop trigger if exists validate_contratos_funciones_servicio on public.contratos_funciones;
drop function if exists public.validate_contratos_funciones_servicio_contrato();

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'contratos_funciones' and column_name = 'servicio_id'
  ) then
    alter table public.contratos_funciones drop column servicio_id;
  end if;
end $$;

create table if not exists public.contratos_funciones_servicios (
  id bigint generated by default as identity primary key,
  contrato_funcion_id bigint not null references public.contratos_funciones (id) on update cascade on delete cascade,
  contrato_id integer not null references public.contratos (id) on update cascade on delete restrict,
  servicio_id bigint not null references public.servicios (id) on update cascade on delete restrict,
  created_at timestamptz not null default now(),
  constraint contratos_funciones_servicios_unica unique (contrato_funcion_id, servicio_id)
);

comment on table public.contratos_funciones_servicios is
  'Etiquetas de servicio de cada tarifa (contratos_funciones). Una tarifa puede tener 0, 1 o varias etiquetas; con varias, esos servicios se agrupan siempre juntos al preparar la facturacion (no se reparten horas entre ellos).';

create index if not exists contratos_funciones_servicios_contrato_funcion_idx
on public.contratos_funciones_servicios (contrato_funcion_id);
create index if not exists contratos_funciones_servicios_contrato_idx
on public.contratos_funciones_servicios (contrato_id);
create index if not exists contratos_funciones_servicios_servicio_idx
on public.contratos_funciones_servicios (servicio_id);

-- servicios es un catalogo global (ver servicios.sql): la fuente de verdad de
-- que servicio esta habilitado en que contrato es contrato_servicios, no una
-- columna en servicios.
create or replace function public.validate_contratos_funciones_servicios_contrato()
returns trigger
language plpgsql
as $$
declare
  v_tarifa_contrato_id integer;
begin
  select cf.contrato_id into v_tarifa_contrato_id
  from public.contratos_funciones cf
  where cf.id = new.contrato_funcion_id;

  if v_tarifa_contrato_id is null then
    raise exception 'La tarifa indicada no existe.';
  end if;
  if new.contrato_id is distinct from v_tarifa_contrato_id then
    raise exception 'El contrato indicado no coincide con el de la tarifa.';
  end if;

  if not exists (
    select 1 from public.contrato_servicios cs
    where cs.contrato_id = v_tarifa_contrato_id
      and cs.servicio_id = new.servicio_id
  ) then
    raise exception 'El servicio indicado no esta habilitado en el contrato de la tarifa.';
  end if;

  return new;
end;
$$;

drop trigger if exists validate_contratos_funciones_servicios on public.contratos_funciones_servicios;
create trigger validate_contratos_funciones_servicios
before insert or update of contrato_funcion_id, contrato_id, servicio_id on public.contratos_funciones_servicios
for each row
execute function public.validate_contratos_funciones_servicios_contrato();

alter table public.contratos_funciones_servicios enable row level security;

grant select, insert, update, delete on public.contratos_funciones_servicios to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "contratos_funciones_servicios_read" on public.contratos_funciones_servicios;
create policy "contratos_funciones_servicios_read" on public.contratos_funciones_servicios for select to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_readable_contrato_ids())
);
drop policy if exists "contratos_funciones_servicios_write" on public.contratos_funciones_servicios;
create policy "contratos_funciones_servicios_write" on public.contratos_funciones_servicios for all to authenticated
using (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
)
with check (
  (select public.is_coordinacion_admin())
  or contrato_id in (select public.coordinacion_manageable_contrato_ids())
);
