-- Catalogo de convenios colectivos y categorias laborales (fuente: tbl_convenios.xlsx),
-- con su tabla salarial historica por fecha (mismo patron que puestos_salarios).
--
-- puestos.convenio_grupo_nivel ya contenia ids que coinciden exactamente con el Id de
-- este Excel: se renombra a convenio_id y se referencia a convenios_categorias(id).
--
-- convenios_categorias es un catalogo (identidad: nombre del convenio + nivel/categoria),
-- legible por cualquier autenticado como el resto de catalogos (puestos, funciones...).
-- convenios_categorias_salarios son las tarifas reales del convenio en el tiempo:
-- confidencial, admin-only, igual que puestos_salarios.

create table if not exists public.convenios_categorias (
  id integer primary key,
  convenio text not null,
  nivel text,
  grupo_nivel text,
  enlace text,
  activo boolean not null default true
);

comment on table public.convenios_categorias is
  'Categorias/niveles salariales de cada convenio colectivo (identidad estable). Las tarifas viven en convenios_categorias_salarios.';
comment on column public.convenios_categorias.nivel is
  'Descripcion textual de la categoria/nivel dentro del convenio (equivalente a la categoria laboral).';
comment on column public.convenios_categorias.grupo_nivel is
  'Codigo de grupo y nivel tal como aparece en el convenio (p.ej. "4.2 Instalaciones").';

create table if not exists public.convenios_categorias_salarios (
  id bigint generated by default as identity primary key,
  convenio_categoria_id integer not null references public.convenios_categorias (id),
  vigente_desde date not null,
  salario_mensual numeric(12, 2),
  salario_anual numeric(12, 2),
  pagas_anuales numeric(4, 1),
  hora_complementaria numeric(10, 4),
  plus_transporte numeric(10, 2),
  hora_montaje numeric(10, 4),
  plus_hora_nocturna numeric(10, 4),
  complemento_movilidad_pct numeric(6, 4),
  complemento_dedicacion numeric(12, 2),
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint convenios_categorias_salarios_vigencia_unique
    unique (convenio_categoria_id, vigente_desde)
);

comment on table public.convenios_categorias_salarios is
  'Tarifas salariales del convenio por categoria, con vigencia por fecha. La tarifa vigente en una fecha es la de mayor vigente_desde <= esa fecha.';
comment on column public.convenios_categorias_salarios.complemento_movilidad_pct is
  'Complemento de movilidad como fraccion (0.10 = 10%), no importe fijo.';
comment on column public.convenios_categorias_salarios.complemento_dedicacion is
  'Complemento de dedicacion como importe fijo en euros.';

create index if not exists convenios_categorias_salarios_categoria_idx
on public.convenios_categorias_salarios (convenio_categoria_id, vigente_desde desc);

create or replace function public.set_convenios_categorias_salarios_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_convenios_categorias_salarios_updated_at on public.convenios_categorias_salarios;
create trigger set_convenios_categorias_salarios_updated_at
before update on public.convenios_categorias_salarios
for each row
execute function public.set_convenios_categorias_salarios_updated_at();

-- Tarifa de convenio vigente de una categoria en una fecha dada.
create or replace function public.get_convenio_salario_vigente(
  p_convenio_categoria_id integer,
  p_fecha date default current_date
)
returns public.convenios_categorias_salarios
language sql
stable
set search_path = public
as $$
  select cs.*
  from public.convenios_categorias_salarios cs
  where cs.convenio_categoria_id = p_convenio_categoria_id
    and cs.vigente_desde <= p_fecha
  order by cs.vigente_desde desc
  limit 1;
$$;

revoke all on function public.get_convenio_salario_vigente(integer, date) from public;
grant execute on function public.get_convenio_salario_vigente(integer, date) to authenticated;

-- ============================================================================
-- Seed de datos: tbl_convenios.xlsx (21 categorias).
-- Vigencia 2026-01-01: columnas base del Excel (las vigentes actualmente).
-- Vigencia 2025-01-01 (solo ids 1-7, "IV Convenio... instalaciones deportivas"):
-- columnas "Salario anual 2025" / "Salario mensual 2025" del Excel, que eran
-- mas bajas que las columnas base -> es la tarifa anterior, no una subida futura.
-- Los demas conceptos (pluses, hora_complementaria...) no se conocen para esa
-- vigencia anterior y se dejan en NULL a proposito.
-- ============================================================================

insert into public.convenios_categorias (id, convenio, nivel, grupo_nivel, enlace) values
(1, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Nivel II: Se incluyen en este grupo todas aquellas actividades correspondientes a las siguientes categorías: auxiliares administrativos, telefonistas, control de acceso, portero, esteticista.', '4.2 Instalaciones', '#https://www.boe.es/diario_boe/txt.php?id=BOE-A-2024-1506#'),
(2, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Nivel I: Se incluyen en este grupo todas aquellas actividades correspondientes a las siguientes categorías: masajista, oficial de 2.ª de mantenimiento de instalaciones, oficial administrativo 2.ª, recepcionista, taquillero, socorrista, monitor unidisciplinar, dependiente tienda propia dentro de las instalaciones deportivas, encargado de limpieza.', '4.1 Instalaciones', '#https://www.boe.es/diario_boe/txt.php?id=BOE-A-2024-1506#'),
(3, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Nivel II: Se incluye en este grupo todas aquellas actividades correspondientes a las siguientes categorías: monitor multidisciplinar. Se entiende como tal el trabajador que imparte más de una disciplina o actividad dirigida diferentes, independientemente de la instalación o medio donde se imparta, incluyendo los socorristas y/o monitores de sala, que también impartan otra disciplina o actividad dirigida.', '3.2 Instalaciones', '#https://www.boe.es/diario_boe/txt.php?id=BOE-A-2024-1506#'),
(4, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Nivel I: Se incluye en este grupo todas aquellas actividades correspondientes a las siguientes categorías: coordinador fitness, actividades aeróbicas, de piscina, de raqueta, de clases colectivas, de mantenimiento de instalaciones, oficial administrativo 1.ª, oficial de 1.ª de mantenimiento de instalaciones, coordinador recepción.', '3.1 Instalaciones', '#https://www.boe.es/diario_boe/txt.php?id=BOE-A-2024-1506#'),
(5, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Nivel II: Se incluyen en este nivel todas aquellas actividades correspondientes a las categorías: Fisioterapeutas, DUE, Contable, Secretaria/o de Dirección, Jefe de Mantenimiento, etc.', '2.2 Instalaciones', '#https://www.boe.es/diario_boe/txt.php?id=BOE-A-2024-1506#'),
(6, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Nivel I: Se incluyen en este nivel todas aquellas actividades correspondientes a los siguientes puestos de trabajo: directores de departamento, tales como financiero, recursos humanos, comercial, marketing, de actividades técnicas, así como, médico, etc.', '2.1 Instalaciones', '#https://www.boe.es/diario_boe/txt.php?id=BOE-A-2024-1506#'),
(7, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Se incluyen en este Grupo, los Directores Generales, Gerentes de los Gimnasios o Centros de Actividad Físico-Deportiva.', '1 Instalaciones', '#https://www.boe.es/diario_boe/txt.php?id=BOE-A-2024-1506#'),
(8, 'Convenio Colectivo de Sector de OCIO EDUCATIVO Y ANIMACION SOCIOCULTURAL (99100055012011', 'Monitor/a de ocio educativo y tiempo libre: Es la persona que, con la titulación académica requerida por la legislación vigente y/o experiencia acreditada en la actividad, dinamiza el desarrollo de los programas de ocio educativo y/o tiempo libre, dentro del marco pedagógico establecido por la actividad de acuerdo con la legislación vigente, transmitiendo sus conocimientos, métodos y estrategias, dirigidos al desarrollo grupal e individual de sus componentes.', '4.2 Ocio educativo', '#https://www.iberley.es/convenios/sector/convenio-colectivo-ocio-educativo-animacion-sociocultural-estatal-1601239#'),
(9, 'Convenio Colectivo de Sector de OCIO EDUCATIVO Y ANIMACION SOCIOCULTURAL (99100055012011', 'Coordinador/a de proyectos pedagógicos, de ocio y tiempo libre: Es quien supervisa los coordinadores/as de los diferentes centros de trabajo y los proyectos de su área asignada, en el marco pedagógico establecido por la empresa y / o entidad, así como el seguimiento de contactos con los clientes, organizar reuniones, controlar y gestionar el material, y elaborar las memorias.

Titulado de Grado: Es quien reuniendo el requisito de titulado de grado, realiza tareas complejas y de impacto, desarrolla programas y aplicaciones técnicas de producción, servicios o administración que exijan titulación específica de grado, de acuerdo con lo especificado en las normas administrativas que las regulan. Se le exige evidenciar un alto nivel de competencias en materia de planificación y programación, desarrollo de otras personas y toma de decisiones, además de las competencias transversales comunes al sector.

Técnico/a de Gestión: Es quien tiene a su cargo el diseño y la organización de proyectos educativos, pedagógicos, de la empresa o entidad. Dependiendo de él, las diversas funciones de diseño y ejecución, estando al tanto de la legislación y las disposiciones oficiales. Así mismo, será responsable de las tareas administrativas y de gestión para dar cobertura al diseño y organización de dichos proyectos.', '2.3 Ocio educativo', '#https://www.iberley.es/convenios/sector/convenio-colectivo-ocio-educativo-animacion-sociocultural-estatal-1601239#'),
(11, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Se incluyen en este Grupo, los Directores Generales, Gerentes de los Gimnasios o Centros de Actividad Físico-Deportiva.', '1.2 Instalaciones', '#https://www.boe.es/eli/es/res/2018/05/29/(2)#'),
(12, 'Oficinas', null, 'ofi 4', null),
(13, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Se incluyen en este Grupo, los Directores Generales, Gerentes de los Gimnasios o Centros de Actividad Físico-Deportiva.', '0 Instalaciones', '#https://www.boe.es/eli/es/res/2018/05/29/(2)#'),
(14, 'Autonoma', null, 'autonoma', null),
(15, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Nivel I: Se incluyen en este grupo todas aquellas actividades correspondientes a las siguientes categorías: masajista, oficial de 2.ª de mantenimiento de instalaciones, oficial administrativo 2.ª, recepcionista, taquillero, socorrista, monitor unidisciplinar, dependiente tienda propia dentro de las instalaciones deportivas, encargado de limpieza.', 'socant', '#https://www.boe.es/eli/es/res/2018/05/29/(2)#'),
(16, 'Convenio Colectivo de Sector de OCIO EDUCATIVO Y ANIMACION SOCIOCULTURAL (99100055012011', 'Coordinador/a de actividades y proyectos de centro: Es la persona que con la titulación requerida y/o experiencia acreditada, coordina el equipo de monitores/as de ocio educativo en el conjunto de sus funciones en el centro de trabajo: organiza reuniones con el equipo de monitores/as de ocio educativo, la dirección del centro, las familias de los usuarios; controla y gestiona el presupuesto y el material; elabora las memorias y asegura la correcta coordinación entre el proyecto pedagógico de la actividad a su cargo y el proyecto pedagógico de centro, teniendo presencia continuada en el mismo y/o en el espacio físico donde se desarrolla la actividad.', '4.1 Ocio educativo', '#https://www.iberley.es/convenios/sector/convenio-colectivo-ocio-educativo-animacion-sociocultural-estatal-1601239#'),
(17, 'Convenio Colectivo de Sector de OCIO EDUCATIVO Y ANIMACION SOCIOCULTURAL (99100055012011', 'Técnico especialista', '3.1 Ocio educativo', '#https://www.iberley.es/convenios/sector/convenio-colectivo-ocio-educativo-animacion-sociocultural-estatal-1601239#'),
(18, 'Convenio Colectivo de Sector de OCIO EDUCATIVO Y ANIMACION SOCIOCULTURAL (99100055012011', 'Coordinador/a de proyectos pedagógicos, de ocio y tiempo libre: Es quien supervisa los coordinadores/as de los diferentes centros de trabajo y los proyectos de su área asignada, en el marco pedagógico establecido por la empresa y / o entidad, así como el seguimiento de contactos con los clientes, organizar reuniones, controlar y gestionar el material, y elaborar las memorias.

Titulado de Grado: Es quien reuniendo el requisito de titulado de grado, realiza tareas complejas y de impacto, desarrolla programas y aplicaciones técnicas de producción, servicios o administración que exijan titulación específica de grado, de acuerdo con lo especificado en las normas administrativas que las regulan. Se le exige evidenciar un alto nivel de competencias en materia de planificación y programación, desarrollo de otras personas y toma de decisiones, además de las competencias transversales comunes al sector.

Técnico/a de Gestión: Es quien tiene a su cargo el diseño y la organización de proyectos educativos, pedagógicos, de la empresa o entidad. Dependiendo de él, las diversas funciones de diseño y ejecución, estando al tanto de la legislación y las disposiciones oficiales. Así mismo, será responsable de las tareas administrativas y de gestión para dar cobertura al diseño y organización de dichos proyectos.', 'OBS-2.3 Ocio educativo', '#https://www.iberley.es/convenios/sector/convenio-colectivo-ocio-educativo-animacion-sociocultural-estatal-1601239#'),
(19, 'Convenio Colectivo de Sector de OCIO EDUCATIVO Y ANIMACION SOCIOCULTURAL (99100055012011', 'Técnico especialista', 'OBS-3.1 Ocio educativo', '#https://www.iberley.es/convenios/sector/convenio-colectivo-ocio-educativo-animacion-sociocultural-estatal-1601239#'),
(20, 'Convenio Colectivo de Sector de OCIO EDUCATIVO Y ANIMACION SOCIOCULTURAL (99100055012011', 'Coordinador/a de actividades y proyectos de centro: Es la persona que con la titulación requerida y/o experiencia acreditada, coordina el equipo de monitores/as de ocio educativo en el conjunto de sus funciones en el centro de trabajo: organiza reuniones con el equipo de monitores/as de ocio educativo, la dirección del centro, las familias de los usuarios; controla y gestiona el presupuesto y el material; elabora las memorias y asegura la correcta coordinación entre el proyecto pedagógico de la actividad a su cargo y el proyecto pedagógico de centro, teniendo presencia continuada en el mismo y/o en el espacio físico donde se desarrolla la actividad.', 'OBS-4.1 Ocio educativo', '#https://www.iberley.es/convenios/sector/convenio-colectivo-ocio-educativo-animacion-sociocultural-estatal-1601239#'),
(21, 'Convenio Colectivo de Sector de OCIO EDUCATIVO Y ANIMACION SOCIOCULTURAL (99100055012011', 'Monitor/a de ocio educativo y tiempo libre: Es la persona que, con la titulación académica requerida por la legislación vigente y/o experiencia acreditada en la actividad, dinamiza el desarrollo de los programas de ocio educativo y/o tiempo libre, dentro del marco pedagógico establecido por la actividad de acuerdo con la legislación vigente, transmitiendo sus conocimientos, métodos y estrategias, dirigidos al desarrollo grupal e individual de sus componentes.', 'OBS-4.2 Ocio educativo', '#https://www.iberley.es/convenios/sector/convenio-colectivo-ocio-educativo-animacion-sociocultural-estatal-1601239#'),
(22, 'IV Convenio colectivo estatal de instalaciones deportivas y gimnasios.', 'Se incluyen en este Grupo, los Directores Generales, Gerentes de los Gimnasios o Centros de Actividad Físico-Deportiva.', '1.3 Instalaciones', '#https://www.boe.es/eli/es/res/2018/05/29/(2)#')
on conflict (id) do update set
  convenio = excluded.convenio,
  nivel = excluded.nivel,
  grupo_nivel = excluded.grupo_nivel,
  enlace = excluded.enlace;

insert into public.convenios_categorias_salarios
  (convenio_categoria_id, vigente_desde, salario_mensual, salario_anual, pagas_anuales, hora_complementaria, plus_transporte, hora_montaje, plus_hora_nocturna, complemento_movilidad_pct, complemento_dedicacion)
values
(1, '2026-01-01', 1221.003, null, 14.0, 9.76, 3.1, 10.44, 1.456, 0.1, null),
(2, '2026-01-01', 1221.00, null, 14.0, 9.76, 3.1, 10.44, 1.46, 0.1, null),
(3, '2026-01-01', 1232.00, null, 14.0, 9.84, 3.1, 10.44, 1.48, 0.1, null),
(4, '2026-01-01', 1261.62, null, 14.0, 10.08, 3.1, 10.44, 1.51, 0.1, null),
(5, '2026-01-01', 1306.40, null, 14.0, 10.44, 3.1, 10.44, 1.57, 0.1, null),
(6, '2026-01-01', 1348.43, null, 14.0, 10.78, 3.1, 10.44, 1.62, 0.1, null),
(7, '2026-01-01', 1471.02, null, 14.0, 11.75, 3.1, 10.44, 1.76, 0.1, null),
(8, '2026-01-01', 1250.21, 17502.89, 14.0, 10.05, null, 10.10, null, null, null),
(9, '2026-01-01', 1474.08, 20637.15, 14.0, 11.85, null, 10.10, null, null, null),
(11, '2026-01-01', 2600.00, null, null, 11.75, 3.1, 10.44, 1.76, 0.1, null),
(12, '2026-01-01', 1654.42, null, null, null, null, null, null, null, null),
(13, '2026-01-01', 4956.14, null, null, null, null, null, null, null, null),
(14, '2026-01-01', 1000.00, null, null, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
(15, '2026-01-01', 1184.00, null, null, 9.46, 2.9, 9.80, 1.34, 0.1, null),
(16, '2026-01-01', 1303.75, 18252.54, 14.0, 10.48, null, 10.10, null, null, null),
(17, '2026-01-01', 1419.49, 19872.81, 14.0, 11.41, null, 10.40, null, null, null),
(18, '2026-01-01', 1343.43, null, null, 10.79, null, 10.10, null, null, null),
(19, '2026-01-01', 1293.68, null, null, 10.40, null, 10.40, null, null, null),
(20, '2026-01-01', 1255.04, null, null, 10.09, null, 10.10, null, null, null),
(21, '2026-01-01', 1184.00, null, null, 9.52, null, 10.10, null, null, 36.29),
(22, '2026-01-01', 2154.00, null, null, 11.75, 3.1, 10.44, 1.76, 0.1, null),
(1, '2025-01-01', 1184.00, 16576.00, null, null, null, null, null, null, null),
(2, '2025-01-01', 1184.00, 16576.00, null, null, null, null, null, null, null),
(3, '2025-01-01', 1191.49, 16680.87, null, null, null, null, null, null, null),
(4, '2025-01-01', 1220.13, 17081.85, null, null, null, null, null, null, null),
(5, '2025-01-01', 1263.45, 17688.26, null, null, null, null, null, null, null),
(6, '2025-01-01', 1304.09, 18257.32, null, null, null, null, null, null, null),
(7, '2025-01-01', 1422.65, 19917.08, null, null, null, null, null, null, null)
on conflict (convenio_categoria_id, vigente_desde) do update set
  salario_mensual = excluded.salario_mensual,
  salario_anual = excluded.salario_anual,
  pagas_anuales = excluded.pagas_anuales,
  hora_complementaria = excluded.hora_complementaria,
  plus_transporte = excluded.plus_transporte,
  hora_montaje = excluded.hora_montaje,
  plus_hora_nocturna = excluded.plus_hora_nocturna,
  complemento_movilidad_pct = excluded.complemento_movilidad_pct,
  complemento_dedicacion = excluded.complemento_dedicacion;

comment on column public.convenios_categorias_salarios.pagas_anuales is
  'Numero de pagas anuales (12 o 14). NULL en filas donde el Excel origen no lo especificaba.';

-- ============================================================================
-- Integracion con puestos: convenio_grupo_nivel -> convenio_id (FK real).
-- ============================================================================

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'puestos' and column_name = 'convenio_grupo_nivel'
  )
  and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'puestos' and column_name = 'convenio_id'
  ) then
    alter table public.puestos rename column convenio_grupo_nivel to convenio_id;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'puestos_convenio_id_fkey'
  ) then
    alter table public.puestos
      add constraint puestos_convenio_id_fkey
      foreign key (convenio_id) references public.convenios_categorias (id);
  end if;
end $$;

-- Precio/hora efectivo: ahora tambien cae al convenio (hora_complementaria/hora_montaje)
-- cuando el puesto no tiene tarifa propia ni override, ademas de puestos_salarios.
create or replace function public.get_puesto_precio_hora(
  p_puesto_id integer,
  p_tipo_hora_id integer,
  p_fecha date default current_date
)
returns numeric
language sql
stable
set search_path = public
as $$
  select coalesce(
    (
      select t.precio_hora
      from public.puestos_tarifas_hora t
      where t.puesto_id = p_puesto_id
        and t.tipo_hora_id = p_tipo_hora_id
        and t.vigente_desde <= p_fecha
      order by t.vigente_desde desc
      limit 1
    ),
    (
      select s.precio_hora * th.multiplicador
      from public.puestos_salarios s
      cross join public.tipo_horas th
      where s.puesto_id = p_puesto_id
        and th.id = p_tipo_hora_id
        and s.precio_hora is not null
        and s.vigente_desde <= p_fecha
      order by s.vigente_desde desc
      limit 1
    ),
    (
      select case p_tipo_hora_id
        when 2 then cs.hora_complementaria
        when 3 then cs.hora_montaje
        else null
      end
      from public.puestos p
      join public.convenios_categorias_salarios cs
        on cs.convenio_categoria_id = p.convenio_id
       and cs.vigente_desde <= p_fecha
      where p.id = p_puesto_id
      order by cs.vigente_desde desc
      limit 1
    )
  );
$$;

-- Salario mensual/anual efectivo: tarifa propia del puesto (puestos_salarios) si existe,
-- si no la del convenio asociado (convenios_categorias_salarios).
create or replace function public.get_puesto_salario_efectivo(
  p_puesto_id integer,
  p_fecha date default current_date
)
returns table (
  salario_mensual numeric,
  salario_anual numeric,
  origen text
)
language sql
stable
set search_path = public
as $$
  select
    coalesce(pr.salario_mensual, cr.salario_mensual) as salario_mensual,
    coalesce(pr.salario_anual, cr.salario_anual) as salario_anual,
    case when pr.salario_mensual is not null or pr.salario_anual is not null
      then 'puesto' else 'convenio' end as origen
  from (select 1) d
  left join public.get_puesto_salario_vigente(p_puesto_id, p_fecha) pr on true
  left join public.puestos p on p.id = p_puesto_id
  left join lateral (
    select ccs.salario_mensual, ccs.salario_anual
    from public.convenios_categorias_salarios ccs
    where ccs.convenio_categoria_id = p.convenio_id
      and ccs.vigente_desde <= p_fecha
    order by ccs.vigente_desde desc
    limit 1
  ) cr on true;
$$;

revoke all on function public.get_puesto_salario_efectivo(integer, date) from public;
grant execute on function public.get_puesto_salario_efectivo(integer, date) to authenticated;

-- ============================================================================
-- RLS: convenios_categorias es catalogo legible por cualquier autenticado
-- (igual que puestos/funciones/modalidades), escritura solo admin.
-- convenios_categorias_salarios es confidencial (tarifas reales): admin-only.
-- ============================================================================

alter table public.convenios_categorias enable row level security;
alter table public.convenios_categorias_salarios enable row level security;

grant select on public.convenios_categorias to authenticated;
grant insert, update, delete on public.convenios_categorias to authenticated;
grant select, insert, update, delete on public.convenios_categorias_salarios to authenticated;
grant usage, select on sequence public.convenios_categorias_salarios_id_seq to authenticated;

drop policy if exists "authenticated_can_read_convenios_categorias" on public.convenios_categorias;
create policy "authenticated_can_read_convenios_categorias"
on public.convenios_categorias
for select
to authenticated
using (true);

drop policy if exists "authenticated_can_insert_convenios_categorias" on public.convenios_categorias;
create policy "authenticated_can_insert_convenios_categorias"
on public.convenios_categorias
for insert
to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "authenticated_can_update_convenios_categorias" on public.convenios_categorias;
create policy "authenticated_can_update_convenios_categorias"
on public.convenios_categorias
for update
to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "authenticated_can_delete_convenios_categorias" on public.convenios_categorias;
create policy "authenticated_can_delete_convenios_categorias"
on public.convenios_categorias
for delete
to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "convenios_categorias_salarios_admin_can_read" on public.convenios_categorias_salarios;
create policy "convenios_categorias_salarios_admin_can_read"
on public.convenios_categorias_salarios
for select
to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "convenios_categorias_salarios_admin_can_insert" on public.convenios_categorias_salarios;
create policy "convenios_categorias_salarios_admin_can_insert"
on public.convenios_categorias_salarios
for insert
to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "convenios_categorias_salarios_admin_can_update" on public.convenios_categorias_salarios;
create policy "convenios_categorias_salarios_admin_can_update"
on public.convenios_categorias_salarios
for update
to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "convenios_categorias_salarios_admin_can_delete" on public.convenios_categorias_salarios;
create policy "convenios_categorias_salarios_admin_can_delete"
on public.convenios_categorias_salarios
for delete
to authenticated
using (public.is_coordinacion_admin());

select setval(
  pg_get_serial_sequence('public.convenios_categorias_salarios', 'id'),
  coalesce((select max(id) from public.convenios_categorias_salarios), 1),
  true
);
