-- ============================================================================
--  Topes de cotizacion a la Seguridad Social por grupo de cotizacion.
-- ----------------------------------------------------------------------------
--  Fuente: BOE anual (Orden/Real Decreto de cotizacion), articulo "Bases
--  maximas y minimas de cotizacion". Los grupos 1-7 cotizan en base MENSUAL
--  (€/mes); los grupos 8-11 cotizan en base DIARIA (€/dia) -- son unidades
--  distintas, no una misma columna con dos escalas. `unidad` dice cual de los
--  dos pares de columnas aplica; el otro par queda a null.
--
--  El grupo de cotizacion de cada historial vive en
--  historiales_laborales.grupo_cotizacion (campo ya existente, importado del
--  Access original). A 2026-08-14, el 60% de los historiales VIGENTES lo
--  tienen a null -- hace falta rellenarlo antes de poder aplicar el tope a
--  esas personas (dato que solo puede aportar el usuario/gestoria).
--
--  Aplicacion (conectada en nomina_calculo_persona.sql, 2026-08-28): las
--  bases de comunes/MEI/desempleo/formacion se ajustan a este intervalo
--  (subir al minimo, recortar al maximo) DESPUES de sumar los devengos y
--  ANTES de aplicar los tipos de cotizacion. La base de IRPF NUNCA se topa.
--
--  TIEMPO PARCIAL (columnas tiempo_parcial_*, 2026-08-31): para un contrato a
--  tiempo parcial, el minimo NO es el mensual prorrateado por la jornada --
--  la SS fija una tarifa minima propia por HORA (y por dia, "Cooperativas"
--  aparte, sin usar todavia). nomina_calculo_persona.sql usa
--  tiempo_parcial_hora x horas_teoricas_jornada() del periodo, redondeadas al
--  entero mas cercano. Verificado al centimo contra el a3nom real de la
--  empresa con tres personas del grupo 6 (Vanesa Garcia Isidro 32h x 8,58 =
--  274,56€; Santiago Puerta 120h x 8,58 = 1.029,60€; Maria Eugenia de
--  Ugarriza 134h x 8,58 = 1.149,72€), 2026-08-31.
-- ============================================================================
create table if not exists public.cotizacion_topes (
  id bigint generated by default as identity primary key,
  grupo_cotizacion smallint not null check (grupo_cotizacion between 1 and 11),
  categorias_profesionales text not null,
  unidad text not null check (unidad in ('mensual', 'diaria')),
  vigente_desde date not null,
  base_minima_mensual numeric(12, 2),
  base_maxima_mensual numeric(12, 2),
  base_minima_diaria numeric(12, 2),
  base_maxima_diaria numeric(12, 2),
  -- Tarifas de tiempo parcial (BOE, columna "Tiempo Parcial"): NO son la
  -- misma escala mensual/diaria de arriba prorrateada, son una tarifa minima
  -- propia. Ver comentario de cabecera.
  tiempo_parcial_dia numeric(12, 2),
  tiempo_parcial_hora numeric(12, 2),
  tiempo_parcial_cooperativas numeric(12, 2),
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cotizacion_topes_unidad_columnas_chk check (
    (unidad = 'mensual' and base_minima_mensual is not null and base_maxima_mensual is not null
       and base_minima_diaria is null and base_maxima_diaria is null)
    or
    (unidad = 'diaria' and base_minima_diaria is not null and base_maxima_diaria is not null
       and base_minima_mensual is null and base_maxima_mensual is null)
  ),
  unique (grupo_cotizacion, vigente_desde)
);

comment on table public.cotizacion_topes is
  'Bases minima/maxima de cotizacion por grupo (1-11) y fecha de vigencia. Grupos 1-7 en €/mes, 8-11 en €/dia. Fuente: BOE anual.';

comment on column public.cotizacion_topes.tiempo_parcial_hora is
  'Tarifa minima por hora para contratos a tiempo parcial (BOE). Se usa en vez de prorratear base_minima_mensual por el coeficiente de jornada: verificado al centimo contra el a3nom real (Vanesa Garcia Isidro, Santiago Puerta, Maria Eugenia de Ugarriza, agosto 2026).';

-- Admin-only, mismo patron que convenios_categorias_salarios / puestos_salarios.
alter table public.cotizacion_topes enable row level security;

drop policy if exists cotizacion_topes_admin_all on public.cotizacion_topes;
create policy cotizacion_topes_admin_all on public.cotizacion_topes
  for all
  using (public.is_coordinacion_admin())
  with check (public.is_coordinacion_admin());

revoke all on public.cotizacion_topes from public;
grant select, insert, update, delete on public.cotizacion_topes to authenticated;

create or replace function public.set_cotizacion_topes_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_cotizacion_topes_updated_at on public.cotizacion_topes;
create trigger trg_cotizacion_topes_updated_at
  before update on public.cotizacion_topes
  for each row execute function public.set_cotizacion_topes_updated_at();

-- Resuelve el tope vigente de un grupo en una fecha (el mas reciente con
-- vigente_desde <= fecha). SECURITY INVOKER: solo un admin obtiene fila, igual
-- que el resto de tablas salariales.
create or replace function public.get_cotizacion_tope_vigente(
  p_grupo_cotizacion smallint,
  p_fecha date
)
returns public.cotizacion_topes
language sql
stable
security invoker
set search_path = public
as $$
  select t.*
  from public.cotizacion_topes t
  where t.grupo_cotizacion = p_grupo_cotizacion
    and t.vigente_desde <= p_fecha
  order by t.vigente_desde desc
  limit 1;
$$;

revoke all on function public.get_cotizacion_tope_vigente(smallint, date) from public;
grant execute on function public.get_cotizacion_tope_vigente(smallint, date) to authenticated;

-- Bases maximas y minimas de cotizacion desde el 01/01/2026 (BOE-A-2026-7296).
-- Las columnas tiempo_parcial_* son la tabla "Tiempo Parcial: Dia/Hora/
-- Cooperativas" del a3nom real de la empresa (mismo BOE), no un derivado de
-- las columnas mensuales/diarias.
insert into public.cotizacion_topes
  (grupo_cotizacion, categorias_profesionales, unidad, vigente_desde, base_minima_mensual, base_maxima_mensual,
   tiempo_parcial_dia, tiempo_parcial_hora, tiempo_parcial_cooperativas)
values
  (1, 'Ingenieros y Licenciados. Personal de alta dirección no incluido en el artículo 1.3.c) del Estatuto de los Trabajadores.', 'mensual', '2026-01-01', 1989.30, 5101.20, 66.31, 11.98, 895.20),
  (2, 'Ingenieros Técnicos, Peritos y Ayudantes Titulados.', 'mensual', '2026-01-01', 1649.70, 5101.20, 54.99, 9.94, 660.00),
  (3, 'Jefes Administrativos y de Taller.', 'mensual', '2026-01-01', 1435.20, 5101.20, 47.84, 8.65, 574.20),
  (4, 'Ayudantes no Titulados.', 'mensual', '2026-01-01', 1424.40, 5101.20, 47.58, 8.58, 569.70),
  (5, 'Oficiales Administrativos.', 'mensual', '2026-01-01', 1424.40, 5101.20, 47.58, 8.58, 569.70),
  (6, 'Subalternos.', 'mensual', '2026-01-01', 1424.40, 5101.20, 47.58, 8.58, 569.70),
  (7, 'Auxiliares Administrativos.', 'mensual', '2026-01-01', 1424.40, 5101.20, 47.58, 8.58, 569.70)
on conflict (grupo_cotizacion, vigente_desde) do nothing;

insert into public.cotizacion_topes
  (grupo_cotizacion, categorias_profesionales, unidad, vigente_desde, base_minima_diaria, base_maxima_diaria,
   tiempo_parcial_dia, tiempo_parcial_hora, tiempo_parcial_cooperativas)
values
  (8, 'Oficiales de primera y segunda.', 'diaria', '2026-01-01', 47.48, 170.04, 47.58, 8.58, 569.70),
  (9, 'Oficiales de tercera y Especialistas.', 'diaria', '2026-01-01', 47.48, 170.04, 47.58, 8.58, 569.70),
  (10, 'Peones.', 'diaria', '2026-01-01', 47.48, 170.04, 47.58, 8.58, 569.70),
  (11, 'Personas trabajadoras menores de dieciocho años, cualquiera que sea su categoría profesional.', 'diaria', '2026-01-01', 47.48, 170.04, 47.58, 8.58, 569.70)
on conflict (grupo_cotizacion, vigente_desde) do nothing;
