create table if not exists public.historiales_laborales_modalidades_pago (
  id integer primary key,
  modalidad_pago text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.historiales_laborales_modalidades_pago (id, modalidad_pago) values
  (1, 'Jornada'),
  (2, 'Horas totales'),
  (3, 'Horas brutas'),
  (4, 'Horas liquidas')
on conflict (id) do update set
  modalidad_pago = excluded.modalidad_pago;

create table if not exists public.historiales_laborales_tipos_contratacion (
  id integer primary key,
  tipo_contratacion text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.historiales_laborales_tipos_contratacion (id, tipo_contratacion) values
  (1, 'Nueva contratacion'),
  (2, 'Subrogacion'),
  (3, 'Llamamiento'),
  (4, 'Variacion'),
  (5, 'Reincorporacion excedencia'),
  (6, 'Otra actividad')
on conflict (id) do update set
  tipo_contratacion = excluded.tipo_contratacion;

create table if not exists public.historiales_laborales_motivos_baja (
  id integer primary key,
  motivo_baja text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.historiales_laborales_motivos_baja (id, motivo_baja) values
  (1, 'Fin Servicio FD'),
  (2, 'Reincoporacion Titular puesto'),
  (3, 'Finalizacion produccion'),
  (4, 'Baja voluntaria'),
  (5, 'Despido objetivo'),
  (6, 'Despido improcedente'),
  (7, 'Despido disciplinario'),
  (8, 'Finalizacion contrato'),
  (9, 'Jubilacion'),
  (10, 'Excedencia'),
  (11, 'Variacion contrato'),
  (12, 'No superar periodo de prueba')
on conflict (id) do update set
  motivo_baja = excluded.motivo_baja;

create table if not exists public.historiales_laborales (
  id bigint generated by default as identity primary key,
  activo boolean,
  enviado boolean not null default false,
  gestionado boolean not null default false,
  tramitado boolean not null default false,
  personal_id integer,
  empresa_id integer,
  jornada numeric(8, 4),
  jornada_maxima numeric(8, 4),
  contrato_laboral_id integer,
  modalidad_pago_id integer,
  fecha_alta date,
  fecha_baja date,
  dias_periodo integer,
  puesto_id integer,
  coeficiente_temporalidad_miles integer,
  tipo_contratacion_id integer,
  motivo_baja_id integer,
  horarios text,
  observaciones text,
  salario_jornada_completa numeric(12, 2),
  importe_horas_complementarias numeric(12, 2),
  tiene_complemento_movilidad boolean,
  tiene_complemento_dedicacion boolean,
  tiene_plus_transporte boolean,
  tiene_nocturnidad boolean,
  tiene_antiguedad boolean,
  tiene_complemento boolean,
  complemento numeric(12, 2),
  notas text,
  grupo_cotizacion smallint,
  movimiento varchar(25),
  puesto_texto text,
  cotizacion_comunes_pct numeric(8, 6),
  cotizacion_mei_pct numeric(8, 6),
  cotizacion_formacion_pct numeric(8, 6),
  cotizacion_desempleo_pct numeric(8, 6),
  lenguaje_inclusivo boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint historiales_laborales_fechas_validas
    check (fecha_baja is null or fecha_alta is null or fecha_baja >= fecha_alta)
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'tipo_contrato_id'
  )
  and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'contrato_laboral_id'
  ) then
    alter table public.historiales_laborales
      rename column tipo_contrato_id to contrato_laboral_id;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'historial_laboral_pago_id'
  )
  and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'modalidad_pago_id'
  ) then
    alter table public.historiales_laborales
      rename column historial_laboral_pago_id to modalidad_pago_id;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'dias_cotizados'
  )
  and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'dias_periodo'
  ) then
    alter table public.historiales_laborales
      rename column dias_cotizados to dias_periodo;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'contratacion_id'
  )
  and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'tipo_contratacion_id'
  ) then
    alter table public.historiales_laborales
      rename column contratacion_id to tipo_contratacion_id;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'baja_id'
  )
  and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'motivo_baja_id'
  ) then
    alter table public.historiales_laborales
      rename column baja_id to motivo_baja_id;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'coeficiente_temporalidad'
  )
  and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'historiales_laborales'
      and column_name = 'coeficiente_temporalidad_miles'
  ) then
    alter table public.historiales_laborales
      rename column coeficiente_temporalidad to coeficiente_temporalidad_miles;
  end if;
end $$;

alter table public.historiales_laborales
add column if not exists created_at timestamptz not null default now();

alter table public.historiales_laborales
add column if not exists updated_at timestamptz not null default now();

alter table public.historiales_laborales
add column if not exists enviado boolean not null default false;

alter table public.historiales_laborales
add column if not exists gestionado boolean not null default false;

alter table public.historiales_laborales
add column if not exists tramitado boolean not null default false;

alter table public.historiales_laborales
alter column personal_id type integer using personal_id::integer,
alter column empresa_id type integer using empresa_id::integer,
alter column contrato_laboral_id type integer using contrato_laboral_id::integer,
alter column modalidad_pago_id type integer using modalidad_pago_id::integer,
alter column puesto_id type integer using puesto_id::integer,
alter column tipo_contratacion_id type integer using tipo_contratacion_id::integer,
alter column motivo_baja_id type integer using motivo_baja_id::integer;

alter table public.historiales_laborales
alter column coeficiente_temporalidad_miles type integer
using case
  when coeficiente_temporalidad_miles is null then null
  when abs(coeficiente_temporalidad_miles) <= 10 then trunc(coeficiente_temporalidad_miles * 1000)::integer
  else trunc(coeficiente_temporalidad_miles)::integer
end;

update public.historiales_laborales
set dias_periodo = (fecha_baja - fecha_alta) + 1
where fecha_alta is not null
  and fecha_baja is not null
  and dias_periodo is distinct from ((fecha_baja - fecha_alta) + 1);

comment on table public.historiales_laborales is
  'Historial laboral/contractual de cada persona, migrado desde Access tbl_vida_laboral.';

comment on column public.historiales_laborales.id is 'Campo Access original: Id';
comment on column public.historiales_laborales.activo is 'Campo Access original: activa';
comment on column public.historiales_laborales.personal_id is 'Campo Access original: personal_id';
comment on column public.historiales_laborales.empresa_id is 'Campo Access original: empresa_id';
comment on column public.historiales_laborales.jornada is 'Campo Access original: Jornada';
comment on column public.historiales_laborales.jornada_maxima is 'Campo Access original: Jornada_max';
comment on column public.historiales_laborales.contrato_laboral_id is 'Campo Access original: tipo_contrato. Referencia a historiales_laborales_contratos.';
comment on column public.historiales_laborales.modalidad_pago_id is 'Campo Access original: vida_laboral_pagos_id. Referencia a historiales_laborales_modalidades_pago.';
comment on column public.historiales_laborales.fecha_alta is 'Campo Access original: fecha_alta';
comment on column public.historiales_laborales.fecha_baja is 'Campo Access original: fecha_baja';
comment on column public.historiales_laborales.dias_periodo is 'Dias naturales del periodo, calculados de fecha_alta a fecha_baja inclusive cuando fecha_baja existe. Campo Access original: dias_cot.';
comment on column public.historiales_laborales.puesto_id is 'Campo Access original: puesto_id. Referencia a puestos.';
comment on column public.historiales_laborales.coeficiente_temporalidad_miles is 'Coeficiente de temporalidad en milesimos: jornada / jornada_maxima * 1000 sin decimales. Campo Access original: coeficiente_temporalidad.';
comment on column public.historiales_laborales.tipo_contratacion_id is 'Campo Access original: vida_laboral_contratacion_id. Referencia a historiales_laborales_tipos_contratacion.';
comment on column public.historiales_laborales.motivo_baja_id is 'Campo Access original: vida_laboral_baja_id. Referencia a historiales_laborales_motivos_baja.';
comment on column public.historiales_laborales.horarios is 'Campo Access original: horarios';
comment on column public.historiales_laborales.observaciones is 'Campo Access original: observaciones';
comment on column public.historiales_laborales.salario_jornada_completa is 'Campo Access original: 01_Salario_JC';
comment on column public.historiales_laborales.importe_horas_complementarias is 'Campo Access original: 67_HC';
comment on column public.historiales_laborales.tiene_complemento_movilidad is 'Campo Access original: 11_have_complemento_movilidad';
comment on column public.historiales_laborales.tiene_complemento_dedicacion is 'Campo Access original: 65_have_Complemento_dedicacion';
comment on column public.historiales_laborales.tiene_plus_transporte is 'Campo Access original: 398_have_plus_transporte';
comment on column public.historiales_laborales.tiene_nocturnidad is 'Campo Access original: 53_have_nocturnidad';
comment on column public.historiales_laborales.tiene_antiguedad is 'Campo Access original: 04_have_antiguedad';
comment on column public.historiales_laborales.tiene_complemento is 'Campo Access original: 18_have_complemento';
comment on column public.historiales_laborales.complemento is 'Campo Access original: 18_complemento';
comment on column public.historiales_laborales.notas is 'Campo Access original: notas';
comment on column public.historiales_laborales.grupo_cotizacion is 'Campo Access original: grupo_cotizacion';
comment on column public.historiales_laborales.movimiento is 'Campo Access original: MOVIMIENTO';
comment on column public.historiales_laborales.puesto_texto is 'Campo Access original: puestos';
comment on column public.historiales_laborales.cotizacion_comunes_pct is 'Campo Access original: Dto_Cot_comunes';
comment on column public.historiales_laborales.cotizacion_mei_pct is 'Campo Access original: Dto_mei';
comment on column public.historiales_laborales.cotizacion_formacion_pct is 'Campo Access original: Dto_Cot_formacion';
comment on column public.historiales_laborales.cotizacion_desempleo_pct is 'Campo Access original: Dto_Cot_Desempleo';
comment on column public.historiales_laborales.lenguaje_inclusivo is 'Campo Access original: lenguaje_inclusivo';

create index if not exists historiales_laborales_personal_id_idx
on public.historiales_laborales (personal_id);

create index if not exists historiales_laborales_empresa_id_idx
on public.historiales_laborales (empresa_id);

create index if not exists historiales_laborales_puesto_id_idx
on public.historiales_laborales (puesto_id);

create index if not exists historiales_laborales_contrato_laboral_id_idx
on public.historiales_laborales (contrato_laboral_id);

create index if not exists historiales_laborales_modalidad_pago_id_idx
on public.historiales_laborales (modalidad_pago_id);

create index if not exists historiales_laborales_fecha_alta_idx
on public.historiales_laborales (fecha_alta);

create index if not exists historiales_laborales_fecha_baja_idx
on public.historiales_laborales (fecha_baja);

create index if not exists historiales_laborales_activo_idx
on public.historiales_laborales (activo);

create index if not exists historiales_laborales_movimiento_idx
on public.historiales_laborales (movimiento);

create index if not exists historiales_laborales_tipo_contratacion_id_idx
on public.historiales_laborales (tipo_contratacion_id);

create index if not exists historiales_laborales_motivo_baja_id_idx
on public.historiales_laborales (motivo_baja_id);

create index if not exists historiales_laborales_updated_at_idx
on public.historiales_laborales (updated_at);

drop index if exists public.historiales_laborales_tipo_contrato_id_idx;
drop index if exists public.historiales_laborales_pago_id_idx;
drop index if exists public.historiales_laborales_contratacion_id_idx;
drop index if exists public.historiales_laborales_baja_id_idx;

create or replace function public.set_historiales_laborales_updated_at()
returns trigger
language plpgsql
as $$
begin
  if new.fecha_alta is not null and new.fecha_baja is not null then
    new.dias_periodo = (new.fecha_baja - new.fecha_alta) + 1;
  end if;

  if new.jornada is not null and new.jornada_maxima is not null and new.jornada_maxima <> 0 then
    new.coeficiente_temporalidad_miles = trunc((new.jornada / new.jornada_maxima) * 1000)::integer;
  end if;

  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_historiales_laborales_updated_at on public.historiales_laborales;
create trigger set_historiales_laborales_updated_at
before insert or update on public.historiales_laborales
for each row
execute function public.set_historiales_laborales_updated_at();

alter table public.historiales_laborales enable row level security;
alter table public.historiales_laborales_modalidades_pago enable row level security;
alter table public.historiales_laborales_tipos_contratacion enable row level security;
alter table public.historiales_laborales_motivos_baja enable row level security;

grant select, insert, update, delete on public.historiales_laborales to authenticated;
grant select on public.historiales_laborales_modalidades_pago to authenticated;
grant select on public.historiales_laborales_tipos_contratacion to authenticated;
grant select on public.historiales_laborales_motivos_baja to authenticated;
grant usage, select on sequence public.historiales_laborales_id_seq to authenticated;

drop policy if exists "authenticated_can_read_historiales_laborales" on public.historiales_laborales;
create policy "authenticated_can_read_historiales_laborales"
on public.historiales_laborales
for select
to authenticated
using (true);

drop policy if exists "authenticated_can_insert_historiales_laborales" on public.historiales_laborales;
create policy "authenticated_can_insert_historiales_laborales"
on public.historiales_laborales
for insert
to authenticated
with check (true);

drop policy if exists "authenticated_can_update_historiales_laborales" on public.historiales_laborales;
create policy "authenticated_can_update_historiales_laborales"
on public.historiales_laborales
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated_can_delete_historiales_laborales" on public.historiales_laborales;
create policy "authenticated_can_delete_historiales_laborales"
on public.historiales_laborales
for delete
to authenticated
using (true);

drop policy if exists "authenticated_can_read_historiales_laborales_modalidades_pago" on public.historiales_laborales_modalidades_pago;
create policy "authenticated_can_read_historiales_laborales_modalidades_pago"
on public.historiales_laborales_modalidades_pago
for select
to authenticated
using (true);

drop policy if exists "authenticated_can_read_historiales_laborales_tipos_contratacion" on public.historiales_laborales_tipos_contratacion;
create policy "authenticated_can_read_historiales_laborales_tipos_contratacion"
on public.historiales_laborales_tipos_contratacion
for select
to authenticated
using (true);

drop policy if exists "authenticated_can_read_historiales_laborales_motivos_baja" on public.historiales_laborales_motivos_baja;
create policy "authenticated_can_read_historiales_laborales_motivos_baja"
on public.historiales_laborales_motivos_baja
for select
to authenticated
using (true);

drop view if exists public.historiales_laborales_detalle;

create or replace view public.historiales_laborales_detalle as
select
  h.id,
  h.activo,
  h.enviado,
  h.gestionado,
  h.tramitado,
  h.personal_id,
  p.personal,
  p.dni,
  case when public.is_coordinacion_admin() then pc.ss end as ss,
  h.empresa_id,
  e.empresa,
  h.jornada,
  h.jornada_maxima,
  h.contrato_laboral_id,
  cl.clave as contrato_laboral_clave,
  cl.duracion as contrato_laboral_duracion,
  cl.jornada as contrato_laboral_jornada,
  cl.descripcion as contrato_laboral_descripcion,
  h.modalidad_pago_id,
  mp.modalidad_pago,
  h.fecha_alta,
  h.fecha_baja,
  h.dias_periodo,
  h.puesto_id,
  pu.puesto,
  h.coeficiente_temporalidad_miles,
  h.tipo_contratacion_id,
  tc.tipo_contratacion,
  h.motivo_baja_id,
  mb.motivo_baja,
  h.horarios,
  h.observaciones,
  h.salario_jornada_completa,
  h.importe_horas_complementarias,
  h.tiene_complemento_movilidad,
  h.tiene_complemento_dedicacion,
  h.tiene_plus_transporte,
  h.tiene_nocturnidad,
  h.tiene_antiguedad,
  h.tiene_complemento,
  h.complemento,
  h.notas,
  h.grupo_cotizacion,
  h.movimiento,
  h.puesto_texto,
  h.cotizacion_comunes_pct,
  h.cotizacion_mei_pct,
  h.cotizacion_formacion_pct,
  h.cotizacion_desempleo_pct,
  h.lenguaje_inclusivo,
  h.created_at,
  h.updated_at
from public.historiales_laborales h
left join public.personal p
  on p.id = h.personal_id
left join public.personal_confidencial pc
  on pc.personal_id = p.id
left join public.empresas e
  on e.id = h.empresa_id
left join public.historiales_laborales_contratos cl
  on cl.id = h.contrato_laboral_id
left join public.historiales_laborales_modalidades_pago mp
  on mp.id = h.modalidad_pago_id
left join public.puestos pu
  on pu.id = h.puesto_id
left join public.historiales_laborales_tipos_contratacion tc
  on tc.id = h.tipo_contratacion_id
left join public.historiales_laborales_motivos_baja mb
  on mb.id = h.motivo_baja_id;

alter view public.historiales_laborales_detalle set (security_invoker = true);

grant select on public.historiales_laborales_detalle to authenticated;

insert into public.puestos (id, puesto)
values (30, 'RRHH')
on conflict (id) do update set
  puesto = excluded.puesto;

update public.historiales_laborales
set puesto_id = 2
where puesto_id in (21, 22);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'historiales_laborales_contrato_laboral_id_fkey'
  )
  and not exists (
    select 1
    from public.historiales_laborales h
    left join public.historiales_laborales_contratos c
      on c.id = h.contrato_laboral_id
    where h.contrato_laboral_id is not null
      and c.id is null
  ) then
    alter table public.historiales_laborales
      add constraint historiales_laborales_contrato_laboral_id_fkey
      foreign key (contrato_laboral_id) references public.historiales_laborales_contratos (id);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'historiales_laborales_modalidad_pago_id_fkey'
  ) then
    alter table public.historiales_laborales
      add constraint historiales_laborales_modalidad_pago_id_fkey
      foreign key (modalidad_pago_id) references public.historiales_laborales_modalidades_pago (id);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'historiales_laborales_puesto_id_fkey'
  )
  and not exists (
    select 1
    from public.historiales_laborales h
    left join public.puestos p
      on p.id = h.puesto_id
    where h.puesto_id is not null
      and p.id is null
  ) then
    alter table public.historiales_laborales
      add constraint historiales_laborales_puesto_id_fkey
      foreign key (puesto_id) references public.puestos (id);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'historiales_laborales_tipo_contratacion_id_fkey'
  ) then
    alter table public.historiales_laborales
      add constraint historiales_laborales_tipo_contratacion_id_fkey
      foreign key (tipo_contratacion_id) references public.historiales_laborales_tipos_contratacion (id);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'historiales_laborales_motivo_baja_id_fkey'
  ) then
    alter table public.historiales_laborales
      add constraint historiales_laborales_motivo_baja_id_fkey
      foreign key (motivo_baja_id) references public.historiales_laborales_motivos_baja (id);
  end if;
end $$;

select setval(
  pg_get_serial_sequence('public.historiales_laborales', 'id'),
  coalesce((select max(id) from public.historiales_laborales), 1),
  true
);
