-- ============================================================================
-- Configuracion de informes PDF para Historial laboral
-- ----------------------------------------------------------------------------
-- Define:
--   1) Datos documentales por empresa: logo, firmante y pie.
--   2) Plantillas editables por tipo de documento: llamamiento, variacion,
--      subrogacion u otros documentos laborales.
--
-- Las plantillas usan placeholders {{variable}} que el frontend sustituira con
-- datos del historial laboral, personal, empresa y actividades activas en la
-- fecha de comienzo del movimiento.
-- ============================================================================

create or replace function public.can_manage_coordinacion_historial_laboral(
  p_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.is_coordinacion_admin(p_user_id), false)
    or (
      public.get_coordinacion_user_role(p_user_id) in ('coordinator', 'area_coordinator')
      and public.can_access_coordinacion_pestana('historial', p_user_id)
    );
$$;

revoke all on function public.can_manage_coordinacion_historial_laboral(uuid) from public;
grant execute on function public.can_manage_coordinacion_historial_laboral(uuid) to authenticated;

alter table public.empresas
  add column if not exists logo_url text,
  add column if not exists logo_data_url text,
  add column if not exists logo_alt text,
  add column if not exists firma_data_url text,
  add column if not exists firmante_nombre text,
  add column if not exists firmante_dni text,
  add column if not exists firmante_cargo text,
  add column if not exists ciudad_firma text not null default 'Oviedo',
  add column if not exists direccion_pie text,
  add column if not exists telefono_pie text,
  add column if not exists email_pie text,
  add column if not exists web_pie text,
  add column if not exists notas text;

do $$
begin
  if to_regclass('public.empresa_documentos_config') is not null then
    execute 'alter table public.empresa_documentos_config add column if not exists logo_data_url text';
    execute 'alter table public.empresa_documentos_config add column if not exists firma_data_url text';

    execute $migrate$
      update public.empresas e
      set
        logo_url = coalesce(e.logo_url, c.logo_url),
        logo_data_url = coalesce(e.logo_data_url, c.logo_data_url),
        logo_alt = coalesce(e.logo_alt, c.logo_alt),
        firma_data_url = coalesce(e.firma_data_url, c.firma_data_url),
        firmante_nombre = coalesce(e.firmante_nombre, c.firmante_nombre),
        firmante_dni = coalesce(e.firmante_dni, c.firmante_dni),
        firmante_cargo = coalesce(e.firmante_cargo, c.firmante_cargo),
        ciudad_firma = coalesce(e.ciudad_firma, c.ciudad_firma, 'Oviedo'),
        direccion_pie = coalesce(e.direccion_pie, c.direccion_pie),
        telefono_pie = coalesce(e.telefono_pie, c.telefono_pie),
        email_pie = coalesce(e.email_pie, c.email_pie),
        web_pie = coalesce(e.web_pie, c.web_pie),
        notas = coalesce(e.notas, c.notas)
      from public.empresa_documentos_config c
      where c.empresa_id = e.id
    $migrate$;
  end if;
end $$;

drop view if exists public.empresa_documentos_config_detalle;
drop table if exists public.empresa_documentos_config;
drop function if exists public.set_empresa_documentos_config_updated_at();

create table if not exists public.historial_laboral_informe_plantillas (
  id bigint generated by default as identity primary key,
  codigo text not null,
  nombre text not null,
  tipo_documento text not null,
  tipo_contratacion_id integer references public.historiales_laborales_tipos_contratacion (id),
  activo boolean not null default true,
  orden integer not null default 100,
  titulo text,
  saludo text,
  texto_intro text,
  texto_movimiento text,
  texto_condiciones text,
  texto_legal text,
  texto_recibido text,
  tabla_actividades_titulo text not null default 'Horario',
  incluir_tabla_actividades boolean not null default true,
  incluir_opciones_respuesta boolean not null default false,
  opciones_respuesta_texto text,
  pie_observaciones text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint historial_laboral_informe_plantillas_codigo_unique unique (codigo),
  constraint historial_laboral_informe_plantillas_tipo_check
    check (tipo_documento in ('llamamiento', 'variacion', 'subrogacion', 'otro'))
);

comment on table public.historial_laboral_informe_plantillas is
  'Plantillas editables para generar documentos PDF desde registros de historial laboral.';
comment on column public.historial_laboral_informe_plantillas.codigo is
  'Identificador estable usado por el frontend. Ej.: llamamiento_fd, variacion_jornada.';
comment on column public.historial_laboral_informe_plantillas.tipo_contratacion_id is
  'Tipo de contratacion sugerido para elegir automaticamente la plantilla desde el historial.';
comment on column public.historial_laboral_informe_plantillas.texto_movimiento is
  'Bloque principal donde se describe fecha de comienzo, jornada, puesto y horarios.';
comment on column public.historial_laboral_informe_plantillas.opciones_respuesta_texto is
  'Texto multilínea para opciones de respuesta del trabajador, si aplica.';

create index if not exists historial_laboral_informe_plantillas_tipo_idx
on public.historial_laboral_informe_plantillas (tipo_documento, activo, orden);

create index if not exists historial_laboral_informe_plantillas_tipo_contratacion_idx
on public.historial_laboral_informe_plantillas (tipo_contratacion_id)
where tipo_contratacion_id is not null;

create or replace function public.set_historial_laboral_informe_plantillas_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_historial_laboral_informe_plantillas_updated_at
on public.historial_laboral_informe_plantillas;
create trigger set_historial_laboral_informe_plantillas_updated_at
before update on public.historial_laboral_informe_plantillas
for each row
execute function public.set_historial_laboral_informe_plantillas_updated_at();

alter table public.historial_laboral_informe_plantillas enable row level security;

grant select, insert, update, delete on public.historial_laboral_informe_plantillas to authenticated;
grant usage, select on sequence public.historial_laboral_informe_plantillas_id_seq to authenticated;

drop policy if exists "historial_docs_plantillas_can_read" on public.historial_laboral_informe_plantillas;
create policy "historial_docs_plantillas_can_read"
on public.historial_laboral_informe_plantillas
for select
to authenticated
using (public.can_access_coordinacion_pestana('historial'));

drop policy if exists "historial_docs_plantillas_can_insert" on public.historial_laboral_informe_plantillas;
create policy "historial_docs_plantillas_can_insert"
on public.historial_laboral_informe_plantillas
for insert
to authenticated
with check (public.can_manage_coordinacion_historial_laboral());

drop policy if exists "historial_docs_plantillas_can_update" on public.historial_laboral_informe_plantillas;
create policy "historial_docs_plantillas_can_update"
on public.historial_laboral_informe_plantillas
for update
to authenticated
using (public.can_manage_coordinacion_historial_laboral())
with check (public.can_manage_coordinacion_historial_laboral());

drop policy if exists "historial_docs_plantillas_can_delete" on public.historial_laboral_informe_plantillas;
create policy "historial_docs_plantillas_can_delete"
on public.historial_laboral_informe_plantillas
for delete
to authenticated
using (public.can_manage_coordinacion_historial_laboral());

-- Plantillas base. Se pueden editar desde la aplicacion sin tocar SQL.
insert into public.historial_laboral_informe_plantillas (
  codigo,
  nombre,
  tipo_documento,
  tipo_contratacion_id,
  activo,
  orden,
  titulo,
  saludo,
  texto_intro,
  texto_movimiento,
  texto_condiciones,
  texto_legal,
  texto_recibido,
  tabla_actividades_titulo,
  incluir_tabla_actividades,
  incluir_opciones_respuesta,
  opciones_respuesta_texto
) values
  (
    'llamamiento_fd',
    'Llamamiento fijo discontinuo',
    'llamamiento',
    3,
    true,
    10,
    null,
    'Estimado/a {{personal_nombre}}',
    'Por la presente ponemos en su conocimiento que, teniendo usted suscrito contrato de trabajo como personal fijo discontinuo con esta empresa, le notificamos que esta prevista la reanudacion del mismo, sin perjuicio de su posterior interrupcion o modificacion de horarios (por necesidades del Servicio), de acuerdo con lo legal y convencionalmente establecido.',
    'Fecha de comienzo: {{fecha_comienzo_larga}}\n\nJornada laboral de {{jornada_horas}} horas a la semana como {{puesto}}. {{horarios}}',
    null,
    'Lo que le comunicamos a los efectos legales oportunos, de conformidad con lo establecido en el articulo 16 del Real Decreto Legislativo 2/2015, de 23 de octubre por el que se aprueba el texto refundido de la Ley del Estatuto de los Trabajadores, asi como lo dispuesto en el convenio colectivo aplicable y en las demas disposiciones vigentes.',
    'RECIBIDO\n\nFdo.: {{personal_nombre}}\n{{personal_dni}}',
    'Horario',
    true,
    true,
    'Estoy de acuerdo\nNo deseo incorporarme\nAñada algun comentario debajo si lo cree conveniente:'
  ),
  (
    'variacion_jornada',
    'Variacion de jornada',
    'variacion',
    4,
    true,
    20,
    null,
    null,
    '{{firmante_nombre}} con DNI {{firmante_dni}} como {{firmante_cargo}} de {{empresa_razon_social}} y {{personal_nombre}}, con DNI {{personal_dni}} en su condicion de trabajador/a de la misma.',
    'ACUERDAN\n\nModificar la jornada laboral desde el {{fecha_comienzo_corta}}, pasando a ser esta a {{jornada_horas}} horas a la semana como {{puesto}}. {{horarios}}',
    'Respetando el resto de obligaciones y condiciones pactadas en el contrato.\n\nComo prueba de la conformidad del presente pacto, ambas partes firman este escrito, en el lugar y fechas señalados, quedando unido al contrato de trabajo que vincula a ambas partes.',
    null,
    'RECIBIDO\n\nFdo.: {{personal_nombre}}\n{{personal_dni}}',
    'Horario',
    true,
    false,
    null
  ),
  (
    'subrogacion_llamamiento',
    'Subrogacion y llamamiento',
    'subrogacion',
    2,
    true,
    30,
    null,
    'Estimado/a {{personal_nombre}}',
    'Por la presente ponemos en su conocimiento que la empresa {{empresa_razon_social}} va a proceder a la subrogacion del contrato de trabajo que tiene firmado con la empresa anterior.\n\nEl Servicio que venia prestando tiene prevista su reanudacion sin perjuicio de su posterior interrupcion o modificacion de horarios por necesidades del mismo y de acuerdo con lo legal y convencionalmente establecido.',
    'Fecha de comienzo: {{fecha_comienzo_larga}}\n\nJornada laboral de {{jornada_horas}} horas a la semana como {{puesto}}. {{horarios}}',
    'Respetando el resto de obligaciones y condiciones pactadas en el contrato anterior.',
    'Por la presente, le comunicamos lo anterior a los efectos legales correspondientes, de conformidad con lo establecido en el articulo 16 del Real Decreto Legislativo 2/2015, de 23 de octubre, que aprueba el texto refundido de la Ley del Estatuto de los Trabajadores, asi como en cumplimiento del convenio colectivo aplicable y demas normativas vigentes.',
    'RECIBIDO\n\nFdo.: {{personal_nombre}}\n{{personal_dni}}',
    'Horario',
    true,
    true,
    'Estoy de acuerdo\nNo deseo incorporarme\nAñada algun comentario debajo si lo cree conveniente:'
  )
on conflict (codigo) do update set
  nombre = excluded.nombre,
  tipo_documento = excluded.tipo_documento,
  tipo_contratacion_id = excluded.tipo_contratacion_id,
  activo = excluded.activo,
  orden = excluded.orden,
  titulo = excluded.titulo,
  saludo = excluded.saludo,
  texto_intro = excluded.texto_intro,
  texto_movimiento = excluded.texto_movimiento,
  texto_condiciones = excluded.texto_condiciones,
  texto_legal = excluded.texto_legal,
  texto_recibido = excluded.texto_recibido,
  tabla_actividades_titulo = excluded.tabla_actividades_titulo,
  incluir_tabla_actividades = excluded.incluir_tabla_actividades,
  incluir_opciones_respuesta = excluded.incluir_opciones_respuesta,
  opciones_respuesta_texto = excluded.opciones_respuesta_texto,
  updated_at = now();

-- Configuracion inicial para empresas existentes con CIF EDP; se puede ajustar
-- posteriormente desde la UI de Configuracion > Empresas.
update public.empresas e
set
  logo_url = coalesce(e.logo_url, './EDP.jpg'),
  logo_alt = coalesce(e.logo_alt, 'EDP'),
  firmante_nombre = coalesce(e.firmante_nombre, 'Isabel Cortavitarte Mediavilla'),
  firmante_dni = coalesce(e.firmante_dni, '11.395.827-V'),
  firmante_cargo = coalesce(e.firmante_cargo, 'Directora-Gerente de Educación Deportiva del Principado'),
  ciudad_firma = coalesce(e.ciudad_firma, 'Oviedo'),
  direccion_pie = coalesce(e.direccion_pie, 'C/ González del Valle 14 2º izq 33004 Oviedo'),
  telefono_pie = coalesce(e.telefono_pie, '985 96 63 88'),
  email_pie = coalesce(e.email_pie, 'edp@edpsl.es')
where upper(coalesce(e.cif, '')) = 'B-33383928';
