-- Fase 2 del modulo de nominas: catalogo configurable de complementos.
--
-- Define el TIPO de complemento y sus reglas (fijo/porcentaje, unidad, sobre que
-- bases se aplica un porcentaje, si prorratea en pagas extra). La adjudicacion a
-- una persona concreta (con su importe/porcentaje real y vigencia) es la Fase 3,
-- todavia no implementada: esta tabla no tiene ninguna relacion con personal.

create table if not exists public.nomina_complementos_catalogo (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  tipo text not null,
  unidad text,
  medida_horas text,
  bases_aplicables text[],
  orden_calculo integer not null default 100,
  prorratea_en_extra boolean not null default false,
  activo boolean not null default true,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nomina_complementos_tipo_chk
    check (tipo in ('fijo', 'porcentaje')),
  constraint nomina_complementos_unidad_chk
    check (unidad is null or unidad in ('mensual', 'diario', 'por_hora')),
  constraint nomina_complementos_medida_horas_chk
    check (unidad is distinct from 'por_hora' or medida_horas is not null),
  constraint nomina_complementos_bases_validas_chk
    check (
      bases_aplicables is null
      or bases_aplicables <@ array['salario_base', 'pluses', 'complementos']::text[]
    ),
  constraint nomina_complementos_coherencia_chk
    check (
      (tipo = 'fijo' and unidad is not null and bases_aplicables is null)
      or
      (tipo = 'porcentaje' and unidad is null and medida_horas is null
        and bases_aplicables is not null and cardinality(bases_aplicables) > 0)
    )
);

comment on table public.nomina_complementos_catalogo is
  'Catalogo configurable de tipos de complemento salarial. La asignacion a personas (Fase 3) vive en una tabla aparte, todavia no creada.';
comment on column public.nomina_complementos_catalogo.tipo is
  'fijo: importe en euros (por unidad). porcentaje: fraccion aplicada sobre bases_aplicables.';
comment on column public.nomina_complementos_catalogo.unidad is
  'Solo para tipo=fijo: mensual (importe tal cual), diario (x dias trabajados en el periodo), por_hora (x horas de medida_horas).';
comment on column public.nomina_complementos_catalogo.medida_horas is
  'Solo para unidad=por_hora: que medida de horas del periodo multiplica el importe (p.ej. "horas_nocturnas"). Se resuelve contra registros en la Fase 5 (motor de calculo), no esta ligado aqui a una columna concreta porque el modelo de horas todavia esta en evolucion (ver memoria modelo-horas-apuntes).';
comment on column public.nomina_complementos_catalogo.bases_aplicables is
  'Solo para tipo=porcentaje: sobre que categorias se calcula el %. Subconjunto de {salario_base, pluses, complementos}.';
comment on column public.nomina_complementos_catalogo.orden_calculo is
  'Orden de evaluacion cuando un complemento porcentual depende de "complementos" ya calculados (menor = se calcula antes). Sin uso real todavia con los 6 sembrados (ninguno depende de otro).';
comment on column public.nomina_complementos_catalogo.prorratea_en_extra is
  'Si su importe (ya calculado, fijo o porcentual) suma en el prorrateo de pagas extra.';

create or replace function public.set_nomina_complementos_catalogo_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_nomina_complementos_catalogo_updated_at on public.nomina_complementos_catalogo;
create trigger set_nomina_complementos_catalogo_updated_at
before update on public.nomina_complementos_catalogo
for each row
execute function public.set_nomina_complementos_catalogo_updated_at();

-- ============================================================================
-- Sembrado: los 6 complementos con fuente de datos real conocida hoy
-- (convenios_categorias_salarios y personal_confidencial). prorratea_en_extra
-- se deja en false por defecto en los 6 -- pendiente de revision caso a caso,
-- no es una regla legal verificada por complemento.
-- ============================================================================

insert into public.nomina_complementos_catalogo
  (nombre, tipo, unidad, medida_horas, bases_aplicables, prorratea_en_extra, notas)
values
  ('Plus de transporte', 'fijo', 'diario', null, null, false,
   'Fuente: convenios_categorias_salarios.plus_transporte (importe por dia trabajado).'),
  ('Plus de nocturnidad', 'fijo', 'por_hora', 'horas_nocturnas', null, false,
   'Fuente: convenios_categorias_salarios.plus_hora_nocturna. Se aplica sobre registros.horas_nocturnas (ver historiales_laborales.tiene_nocturnidad para saber si a la persona se le abona).'),
  ('Complemento de movilidad', 'porcentaje', null, null, array['salario_base'], false,
   'Fuente: convenios_categorias_salarios.complemento_movilidad_pct (10% confirmado). Base asumida: salario_base, a revisar.'),
  ('Complemento de dedicación', 'fijo', 'mensual', null, null, false,
   'Fuente: historiales_laborales.tiene_complemento_dedicacion (hoy sin importe propio) y convenios_categorias_salarios.complemento_dedicacion (importe fijo, p.ej. 36.29€).'),
  ('Complemento de antigüedad', 'fijo', 'mensual', null, null, false,
   'Fuente: personal_confidencial.com_antiguedad_04 (importe fijo mensual por persona).'),
  ('Complemento absorbible', 'fijo', 'mensual', null, null, false,
   'Fuente: personal_confidencial.com_absorbible_18 (importe fijo mensual por persona).')
on conflict (nombre) do nothing;

-- ============================================================================
-- RLS: admin-only, igual que el resto de tablas de tarifas/nomina.
-- ============================================================================

alter table public.nomina_complementos_catalogo enable row level security;

grant select, insert, update, delete on public.nomina_complementos_catalogo to authenticated;
grant usage, select on sequence public.nomina_complementos_catalogo_id_seq to authenticated;

drop policy if exists "nomina_complementos_catalogo_admin_can_read" on public.nomina_complementos_catalogo;
create policy "nomina_complementos_catalogo_admin_can_read"
on public.nomina_complementos_catalogo
for select
to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "nomina_complementos_catalogo_admin_can_insert" on public.nomina_complementos_catalogo;
create policy "nomina_complementos_catalogo_admin_can_insert"
on public.nomina_complementos_catalogo
for insert
to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "nomina_complementos_catalogo_admin_can_update" on public.nomina_complementos_catalogo;
create policy "nomina_complementos_catalogo_admin_can_update"
on public.nomina_complementos_catalogo
for update
to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "nomina_complementos_catalogo_admin_can_delete" on public.nomina_complementos_catalogo;
create policy "nomina_complementos_catalogo_admin_can_delete"
on public.nomina_complementos_catalogo
for delete
to authenticated
using (public.is_coordinacion_admin());

select setval(
  pg_get_serial_sequence('public.nomina_complementos_catalogo', 'id'),
  coalesce((select max(id) from public.nomina_complementos_catalogo), 1),
  true
);
