-- Fase 6 del modulo de nominas: PERSISTIR la nomina emitida.
--
-- Hasta ahora todo se calculaba al vuelo con calcular_nomina_persona. Eso hace
-- que una nomina "ya entregada" cambie sola si manana se corrige una tarifa de
-- convenio, un complemento o una regla del motor. Aqui se congela: al emitir se
-- guarda la cabecera con sus totales y TODAS las lineas del desglose tal cual
-- salieron ese dia, junto con los parametros usados para calcularla.
--
-- A partir de la emision, la nomina se LEE de estas tablas; el motor solo se
-- vuelve a tocar si se emite otra (reemplazando a la anterior, que queda
-- anulada con rastro).
--
-- Una persona puede tener VARIAS nominas en el mismo mes: dos vidas laborales
-- que no se solapan son dos nominas reales (ver p_historial_ids en
-- nomina_calculo_persona.sql). Por eso la clave de unicidad incluye el conjunto
-- de historiales, no solo persona + periodo.
--
-- NO ES SOLO EL RECIBO: una nomina emitida es tambien el REGISTRO LABORAL del
-- periodo. Ademas de las lineas de importe, se guarda:
--   * nomina_historiales -- una fila por periodo/puesto que entra en la nomina,
--     con la foto completa del contrato en ese momento (convenio y tarifas,
--     jornada, coeficiente, modalidad de pago, horas teoricas, flags de pluses,
--     tipos de cotizacion). Es lo que explica de donde sale cada importe.
--   * nomina_horas -- las horas realmente trabajadas por puesto, desglosadas
--     por tipo de hora y situacion, con los ids de los registros de origen.
--   * nomina_lineas -- ademas de la nomina de la persona (ambito 'persona'),
--     el desglose POR PUESTO (ambito 'puesto'), con cantidad y precio unitario
--     de cada plus y complemento.
-- Con eso, la nomina se sostiene sola aunque despues se corrijan registros,
-- tarifas o el propio historial laboral.

-- ============================================================================
-- Cabecera
-- ============================================================================

create table if not exists public.nominas (
  id bigint generated by default as identity primary key,
  personal_id integer not null references public.personal (id),
  empresa_id integer references public.empresas (id),
  periodo_desde date not null,
  periodo_hasta date not null,
  -- Periodos de historial laboral incluidos. Se guarda ordenado (trigger) para
  -- que el indice de unicidad no vea distintas dos listas con los mismos ids.
  historial_ids bigint[] not null default '{}'::bigint[],

  -- Mes natural al que corresponde, cuando el periodo cae entero dentro de uno.
  -- Nulo en rangos a caballo entre dos meses. Sirve para listar "las nominas de
  -- junio 2026" sin tener que adivinarlo desde las fechas.
  ejercicio integer generated always as (
    case when extract(year from periodo_desde) = extract(year from periodo_hasta)
          and extract(month from periodo_desde) = extract(month from periodo_hasta)
    then extract(year from periodo_desde)::integer end
  ) stored,
  mes integer generated always as (
    case when extract(year from periodo_desde) = extract(year from periodo_hasta)
          and extract(month from periodo_desde) = extract(month from periodo_hasta)
    then extract(month from periodo_desde)::integer end
  ) stored,

  -- Parametros con los que se calculo. No se usan para nada al leer: estan para
  -- poder auditar y reproducir el calculo (o repetirlo con los mismos ajustes).
  base_calculo text,
  ajuste_jornada text,
  manual_importe numeric(12, 2),
  manual_modo text,
  manual_pagas_incluidas boolean not null default false,
  manual_complementos bigint[],
  manual_transporte boolean not null default false,

  -- Totales congelados (se derivan de nomina_lineas al emitir).
  total_devengado numeric(12, 2) not null default 0,
  base_cc numeric(12, 2) not null default 0,
  base_cp numeric(12, 2) not null default 0,
  base_irpf numeric(12, 2) not null default 0,
  total_deducciones numeric(12, 2) not null default 0,
  liquido numeric(12, 2) not null default 0,

  estado text not null default 'emitida',
  -- Emitida con las lineas ajustadas a mano (p_lineas) en vez de con las que
  -- dio el motor. El expediente se congela igual: lo trabajado no se edita.
  editada boolean not null default false,
  notas text,
  anulada_motivo text,
  anulada_en timestamptz,
  -- Nomina anterior a la que reemplaza esta (al reemitir).
  sustituye_a bigint references public.nominas (id),

  emitida_en timestamptz not null default now(),
  emitida_por uuid default auth.uid(),
  emitida_por_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint nominas_periodo_valido_chk check (periodo_hasta >= periodo_desde),
  constraint nominas_estado_chk check (estado in ('emitida', 'anulada')),
  constraint nominas_manual_modo_chk
    check (manual_modo is null or manual_modo in ('periodo', 'diario', 'hora')),
  constraint nominas_manual_coherencia_chk
    check (manual_importe is not null or manual_modo is null)
);

comment on table public.nominas is
  'Nomina emitida y congelada: cabecera con totales y parametros de calculo. El desglose vive en nomina_lineas. Emitir de nuevo el mismo periodo anula la anterior (sustituye_a).';
comment on column public.nominas.historial_ids is
  'Periodos de historiales_laborales incluidos, ordenados. Dos vidas laborales que no se solapan dan DOS nominas del mismo mes, cada una con su lista.';
comment on column public.nominas.estado is
  'emitida = vigente; anulada = reemplazada o cancelada a mano (conserva sus lineas como historico).';

-- Una sola nomina viva por persona + empresa + periodo + conjunto de
-- historiales. Las anuladas quedan fuera para poder reemitir.
create unique index if not exists nominas_vigente_unica_idx
on public.nominas (personal_id, coalesce(empresa_id, 0), periodo_desde, periodo_hasta, historial_ids)
where estado = 'emitida';

create index if not exists nominas_personal_periodo_idx
on public.nominas (personal_id, periodo_desde desc, periodo_hasta desc);

create index if not exists nominas_periodo_idx
on public.nominas (ejercicio, mes);

-- ============================================================================
-- Lineas del desglose: copia literal de lo que devolvio calcular_nomina_persona
-- ============================================================================

create table if not exists public.nomina_lineas (
  id bigint generated by default as identity primary key,
  nomina_id bigint not null references public.nominas (id) on delete cascade,
  -- 'persona' = la nomina real (la que suma). 'puesto' = el desglose de UN
  -- historial, con historial_id relleno; es explicativo y NO suma a los totales.
  ambito text not null default 'persona',
  historial_id bigint,
  orden integer not null,
  seccion text not null,
  concepto text not null,
  detalle text,
  base numeric(14, 4),
  tipo numeric(10, 6),
  -- Unidades y precio unitario que produjeron el importe (dias x tarifa de
  -- transporte, horas x precio hora, 1 x importe fijo). El texto de `detalle` lo
  -- cuenta en prosa; esto es lo explotable.
  cantidad numeric(14, 4),
  precio numeric(14, 6),
  -- Codigo del programa de nominas externo (398 transporte, 93 disponibilidad,
  -- 60 complemento de puesto, 67 complementarias, 12 festivo...), cuando se
  -- conoce. Ver get_codigo_nomina_concepto.
  codigo_nomina integer,
  importe numeric(12, 2),
  -- Igual que en el motor: si viene relleno, esta linea DESGLOSA a la anterior
  -- sin detalle_de y por tanto NO suma (si sumara, se contaria dos veces).
  detalle_de text,
  constraint nomina_lineas_ambito_chk check (ambito in ('persona', 'puesto')),
  constraint nomina_lineas_historial_chk
    check (ambito = 'persona' or historial_id is not null)
);

comment on table public.nomina_lineas is
  'Desglose congelado de una nomina emitida. ambito=persona son las lineas de la nomina real; ambito=puesto es el desglose por historial (explicativo, no suma).';
comment on column public.nomina_lineas.detalle_de is
  'Si no es nulo, la linea desglosa a la anterior sin detalle_de y NO suma al bruto ni a las bases.';
comment on column public.nomina_lineas.ambito is
  'persona = suma en la nomina; puesto = detalle del historial indicado en historial_id, NO suma.';

create index if not exists nomina_lineas_nomina_idx
on public.nomina_lineas (nomina_id, ambito, orden);

create index if not exists nomina_lineas_historial_idx
on public.nomina_lineas (nomina_id, historial_id);

-- ============================================================================
-- Contexto laboral congelado: un registro por periodo/puesto de la nomina
-- ============================================================================

create table if not exists public.nomina_historiales (
  id bigint generated by default as identity primary key,
  nomina_id bigint not null references public.nominas (id) on delete cascade,
  historial_id bigint not null,
  -- El de mas dias en el periodo: de el salen los tipos de cotizacion y el
  -- numero de pagas de la nomina (limitacion conocida con dos convenios).
  predominante boolean not null default false,

  personal_id integer,
  empresa_id integer,
  empresa text,
  puesto_id integer,
  puesto text,
  convenio_categoria_id integer,
  convenio text,

  fecha_alta date,
  fecha_baja date,
  -- Ventana efectiva: interseccion del periodo del historial con el de la
  -- nomina. Es sobre la que se calculo todo.
  tramo_desde date,
  tramo_hasta date,
  dias_nomina integer,
  dias_trabajados integer,

  jornada numeric(8, 2),
  jornada_maxima numeric(8, 2),
  coeficiente_temporalidad_miles integer,
  horas_teoricas numeric(10, 4),
  modalidad_pago_id integer,
  modalidad_pago text,
  -- El resuelto de verdad ('ninguno'/'ambos'/'exceso'), no el pedido.
  ajuste_jornada text,
  base_calculo text,
  grupo_cotizacion smallint,

  salario_mensual numeric(12, 2),
  salario_convenio_mensual numeric(12, 2),
  salario_convenio_diario numeric(12, 4),
  salario_convenio_hora numeric(12, 4),
  pagas_anuales numeric(6, 2),
  pagas_extra integer,

  horas_reg numeric(10, 2),
  horas_pnr numeric(10, 2),
  horas_mont numeric(10, 2),
  horas_hcomp numeric(10, 2),
  horas_ftrab numeric(10, 2),
  horas_bolsa_salida numeric(10, 2),
  horas_bolsa_entrada numeric(10, 2),
  horas_nocturnas numeric(10, 2),

  tiene_plus_transporte boolean,
  tiene_nocturnidad boolean,
  tiene_complemento_movilidad boolean,
  tiene_complemento_dedicacion boolean,
  tarifa_plus_transporte numeric(10, 4),
  tarifa_hora_nocturna numeric(10, 4),
  tarifa_complemento_movilidad_pct numeric(8, 6),
  tarifa_complemento_dedicacion numeric(10, 4),
  precio_hora_montaje numeric(10, 4),
  precio_hora_complementaria numeric(10, 4),
  precio_hora_jornada_completa numeric(10, 4),

  cotizacion_comunes_pct numeric(8, 6),
  cotizacion_mei_pct numeric(8, 6),
  cotizacion_desempleo_pct numeric(8, 6),
  cotizacion_formacion_pct numeric(8, 6),

  total_devengado numeric(12, 2) not null default 0,

  constraint nomina_historiales_unico unique (nomina_id, historial_id)
);

comment on table public.nomina_historiales is
  'Foto del contrato de cada periodo/puesto incluido en la nomina: convenio y tarifas vigentes, jornada, horas teoricas, flags de pluses y tipos de cotizacion. Congelado al emitir: explica de donde sale cada importe aunque despues cambie el historial.';
comment on column public.nomina_historiales.ajuste_jornada is
  'Criterio realmente aplicado (ninguno/ambos/exceso), ya resuelto desde la modalidad de pago si no se forzo.';

create index if not exists nomina_historiales_nomina_idx
on public.nomina_historiales (nomina_id);

create index if not exists nomina_historiales_historial_idx
on public.nomina_historiales (historial_id);

-- ============================================================================
-- Horas trabajadas congeladas, por puesto x tipo de hora x situacion
-- ============================================================================

create table if not exists public.nomina_horas (
  id bigint generated by default as identity primary key,
  nomina_id bigint not null references public.nominas (id) on delete cascade,
  historial_id bigint not null,
  puesto_id integer,
  puesto text,
  tipo_hora_id integer,
  tipo_hora text,
  tipo_hora_codigo_nomina integer,
  situacion_id integer,
  situacion text,
  horas numeric(10, 2) not null default 0,
  horas_nocturnas numeric(10, 2) not null default 0,
  dias integer not null default 0,
  registros integer not null default 0,
  -- Ids de los registros que forman esta fila: permiten auditar la nomina
  -- contra el parte de horas aunque los registros cambien despues.
  registro_ids bigint[],
  -- CAMB (cubrio otra persona) y LG (larga duracion) no son trabajo de esta
  -- persona: se guardan para que el registro laboral este completo, pero el
  -- motor las cuenta como cero.
  excluida boolean not null default false,
  -- Suma a la jornada cumplida (REG, PNR y salidas de bolsa).
  cuenta_jornada boolean not null default false,
  -- Cuenta como dia efectivamente trabajado (transporte y complementos diarios).
  dia_efectivo boolean not null default false
);

comment on table public.nomina_horas is
  'Horas congeladas de la nomina, agregadas por historial x tipo de hora x situacion, con los ids de los registros de origen.';

create index if not exists nomina_horas_nomina_idx
on public.nomina_horas (nomina_id, historial_id);

-- ============================================================================
-- Triggers de mantenimiento
-- ============================================================================

create or replace function public.set_nominas_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_nominas_updated_at on public.nominas;
create trigger set_nominas_updated_at
before update on public.nominas
for each row
execute function public.set_nominas_updated_at();

-- Ordena historial_ids y quita duplicados/nulos: sin esto, {5863,5864} y
-- {5864,5863} serian dos nominas distintas para el indice de unicidad.
create or replace function public.normalize_nomina_historial_ids()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.historial_ids := coalesce((
    select array_agg(distinct x order by x)
    from unnest(coalesce(new.historial_ids, '{}'::bigint[])) as x
    where x is not null
  ), '{}'::bigint[]);
  return new;
end;
$$;

drop trigger if exists normalize_nomina_historial_ids on public.nominas;
create trigger normalize_nomina_historial_ids
before insert or update on public.nominas
for each row
execute function public.normalize_nomina_historial_ids();

-- ============================================================================
-- Codigo del programa de nominas externo para un concepto del motor
-- ============================================================================

-- Los complementos traen el suyo en el catalogo; los conceptos que genera el
-- propio motor (y no son complementos asignables) van en el mapa fijo. Sus
-- codigos los dio el usuario y estan documentados en nomina_complementos_codigos.sql.
create or replace function public.get_codigo_nomina_concepto(p_concepto text)
returns integer
language sql
stable
security invoker
set search_path = public
as $$
  select coalesce(
    (select c.codigo_nomina
       from public.nomina_complementos_catalogo c
      where lower(c.nombre) = lower(trim(p_concepto))
      limit 1),
    case lower(trim(coalesce(p_concepto, '')))
      when 'plus de disponibilidad' then 93
      when 'horas complementarias' then 67
      when 'plus festivo trabajado' then 12
      when 'descuento por absentismo' then 790
      when 'prorrateo pagas extra' then 30
      when 'p.p. pagas extra (solo cotiza)' then 30
      else null
    end);
$$;

revoke all on function public.get_codigo_nomina_concepto(text) from public;
grant execute on function public.get_codigo_nomina_concepto(text) to authenticated;

-- ============================================================================
-- Contexto laboral de un periodo: la foto que explica su calculo
-- ============================================================================

-- ACOPLAMIENTO DELIBERADO con calcular_nomina_devengos (nomina_calculo.sql):
-- reproduce su preambulo -- ventana efectiva, resolucion del ajuste de jornada
-- desde la modalidad de pago, modo de base_calculo y recuento de horas por tipo
-- con las mismas exclusiones (CAMB y LG). No calcula importes: solo describe el
-- contrato y lo trabajado. Si alli cambia alguna de esas reglas, cambiarla aqui.
create or replace function public.get_nomina_contexto_historial(
  p_historial_id bigint,
  p_desde date default null,
  p_hasta date default null,
  p_base_calculo text default null,
  p_ajuste_jornada text default null
)
returns table (
  historial_id bigint, personal_id integer, empresa_id integer, empresa text,
  puesto_id integer, puesto text, convenio_categoria_id integer, convenio text,
  fecha_alta date, fecha_baja date, tramo_desde date, tramo_hasta date,
  dias_nomina integer, dias_trabajados integer,
  jornada numeric, jornada_maxima numeric, coeficiente_temporalidad_miles integer,
  horas_teoricas numeric, modalidad_pago_id integer, modalidad_pago text,
  ajuste_jornada text, base_calculo text, grupo_cotizacion smallint,
  salario_mensual numeric, salario_convenio_mensual numeric,
  salario_convenio_diario numeric, salario_convenio_hora numeric,
  pagas_anuales numeric, pagas_extra integer,
  horas_reg numeric, horas_pnr numeric, horas_mont numeric, horas_hcomp numeric,
  horas_ftrab numeric, horas_bolsa_salida numeric, horas_bolsa_entrada numeric,
  horas_nocturnas numeric,
  tiene_plus_transporte boolean, tiene_nocturnidad boolean,
  tiene_complemento_movilidad boolean, tiene_complemento_dedicacion boolean,
  tarifa_plus_transporte numeric, tarifa_hora_nocturna numeric,
  tarifa_complemento_movilidad_pct numeric, tarifa_complemento_dedicacion numeric,
  precio_hora_montaje numeric, precio_hora_complementaria numeric,
  precio_hora_jornada_completa numeric,
  cotizacion_comunes_pct numeric, cotizacion_mei_pct numeric,
  cotizacion_desempleo_pct numeric, cotizacion_formacion_pct numeric
)
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  h public.historiales_laborales;
  v_conv public.convenios_categorias_salarios;
  v_sal record;
  v_desde date; v_hasta date; v_fecha_ref date;
  v_convenio_id integer; v_ajuste text; v_modalidad text; v_modo text;
  v_sit_excluidas integer[];
begin
  select * into h from public.historiales_laborales where id = p_historial_id;
  if h.id is null then return; end if;

  select coalesce(array_agg(s.id), '{}'::integer[]) into v_sit_excluidas
  from public.situaciones s where s.situacion in ('CAMB', 'LG');

  v_desde := greatest(h.fecha_alta, coalesce(p_desde, h.fecha_alta));
  v_hasta := least(
    coalesce(h.fecha_baja, coalesce(p_hasta, current_date)),
    coalesce(p_hasta, coalesce(h.fecha_baja, current_date))
  );
  if v_hasta < v_desde then return; end if;
  v_fecha_ref := v_desde;

  v_ajuste := nullif(trim(p_ajuste_jornada), '');
  if v_ajuste is null then
    select lower(mp.modalidad_pago) into v_modalidad
    from public.historiales_laborales_modalidades_pago mp
    where mp.id = h.modalidad_pago_id;
    v_ajuste := case when v_modalidad = 'horas totales' then 'ambos' else 'ninguno' end;
  end if;

  select pu.convenio_id into v_convenio_id from public.puestos pu where pu.id = h.puesto_id;
  if v_convenio_id is not null then
    select * into v_conv from public.get_convenio_salario_vigente(v_convenio_id, v_fecha_ref);
  end if;
  select * into v_sal from public.get_puesto_salario_efectivo(h.puesto_id, v_fecha_ref);

  v_modo := coalesce(nullif(trim(p_base_calculo), ''), v_conv.base_calculo, 'mensual');

  return query
  select
    h.id, h.personal_id, h.empresa_id,
    (select e.empresa from public.empresas e where e.id = h.empresa_id),
    h.puesto_id,
    coalesce((select pu.puesto from public.puestos pu where pu.id = h.puesto_id), h.puesto_texto),
    v_convenio_id,
    (select cc.convenio || coalesce(' · ' || cc.grupo_nivel, '')
       from public.convenios_categorias cc where cc.id = v_convenio_id),
    h.fecha_alta, h.fecha_baja, v_desde, v_hasta,
    public.dias_nomina(v_desde, v_hasta),
    (select count(distinct r.fecha)::integer
       from public.registros r
       join public.situaciones s on s.id = r.situacion_id
       left join public.tipo_horas th on th.id = r.tipo_hora_id
      where r.personal_id = h.personal_id and r.puesto_id = h.puesto_id
        and (h.empresa_id is null or r.empresa_id = h.empresa_id)
        and r.fecha >= v_desde and r.fecha <= v_hasta
        and (s.situacion in ('NORM','SUST') or (s.situacion = 'FEST' and th.tipo_hora = 'FTRAB'))),
    h.jornada, h.jornada_maxima, h.coeficiente_temporalidad_miles,
    public.horas_teoricas_jornada(v_desde, v_hasta, h.jornada),
    h.modalidad_pago_id,
    (select mp.modalidad_pago from public.historiales_laborales_modalidades_pago mp
      where mp.id = h.modalidad_pago_id),
    v_ajuste, v_modo, h.grupo_cotizacion,
    v_sal.salario_mensual, v_conv.salario_mensual, v_conv.salario_diario, v_conv.salario_hora,
    v_conv.pagas_anuales,
    greatest(coalesce(v_conv.pagas_anuales, 12)::integer - 12, 0),
    r.horas_reg, r.horas_pnr, r.horas_mont, r.horas_hcomp, r.horas_ftrab,
    r.horas_bout, r.horas_bin, r.horas_noct,
    h.tiene_plus_transporte, h.tiene_nocturnidad,
    h.tiene_complemento_movilidad, h.tiene_complemento_dedicacion,
    v_conv.plus_transporte, v_conv.plus_hora_nocturna,
    v_conv.complemento_movilidad_pct, v_conv.complemento_dedicacion,
    public.get_puesto_precio_hora(h.puesto_id, 3, v_fecha_ref),
    public.get_puesto_precio_hora(h.puesto_id, 2, v_fecha_ref),
    public.get_convenio_precio_hora_jc(v_convenio_id, h.jornada_maxima, v_fecha_ref),
    h.cotizacion_comunes_pct, h.cotizacion_mei_pct,
    h.cotizacion_desempleo_pct, h.cotizacion_formacion_pct
  from (
    -- Mismas exclusiones que el motor: CAMB y LG no son trabajo de esta persona.
    select
      coalesce(sum(rg.horas) filter (where rg.tipo_hora_id = 1), 0)::numeric as horas_reg,
      coalesce(sum(rg.horas) filter (where rg.tipo_hora_id = 5), 0)::numeric as horas_pnr,
      coalesce(sum(rg.horas) filter (where rg.tipo_hora_id = 3), 0)::numeric as horas_mont,
      coalesce(sum(rg.horas) filter (where rg.tipo_hora_id = 2), 0)::numeric as horas_hcomp,
      coalesce(sum(rg.horas) filter (where rg.tipo_hora_id = 4), 0)::numeric as horas_ftrab,
      coalesce(sum(rg.horas) filter (where rg.tipo_hora_id = 8), 0)::numeric as horas_bout,
      coalesce(sum(rg.horas) filter (where rg.tipo_hora_id = 7), 0)::numeric as horas_bin,
      coalesce(sum(rg.horas_nocturnas), 0)::numeric as horas_noct
    from public.registros rg
    where rg.personal_id = h.personal_id and rg.puesto_id = h.puesto_id
      and (h.empresa_id is null or rg.empresa_id = h.empresa_id)
      and coalesce(rg.situacion_id, -1) <> all(v_sit_excluidas)
      and rg.fecha >= v_desde and rg.fecha <= v_hasta
  ) r;
end;
$$;

revoke all on function public.get_nomina_contexto_historial(bigint, date, date, text, text) from public;
grant execute on function public.get_nomina_contexto_historial(bigint, date, date, text, text) to authenticated;

-- ============================================================================
-- Emitir: calcula y congela
-- ============================================================================

-- Espejo de la firma de calcular_nomina_persona mas p_notas, p_reemplazar y
-- p_lineas. Con p_reemplazar la nomina viva de ese periodo se marca anulada y
-- la nueva apunta a ella con sustituye_a; sin el, chocar con una existente da
-- error.
--
-- Se dropea la firma anterior (sin p_lineas): conviviendo las dos, PostgREST
-- daria "42725 function is not unique" (ya paso con calcular_nomina_persona).
drop function if exists public.emitir_nomina(integer, date, date, integer, text, text, bigint[], numeric, text, boolean, bigint[], boolean, text, boolean);

create or replace function public.emitir_nomina(
  p_personal_id integer,
  p_desde date,
  p_hasta date,
  p_empresa_id integer default null,
  p_base_calculo text default null,
  p_ajuste_jornada text default null,
  p_historial_ids bigint[] default null,
  p_manual_importe numeric default null,
  p_manual_modo text default null,
  p_manual_pagas_incluidas boolean default false,
  p_manual_complementos bigint[] default null,
  p_manual_transporte boolean default false,
  p_notas text default null,
  p_reemplazar boolean default false,
  -- Lineas ajustadas a mano desde el editor de Gestion. Nulo = las que calcule
  -- el motor. Cada elemento: {orden, seccion, concepto, detalle, base, tipo,
  -- cantidad, precio, importe}. El expediente (nomina_historiales y
  -- nomina_horas) se congela igual: lo trabajado no se edita, solo lo que se
  -- paga por ello.
  p_lineas jsonb default null
)
returns bigint
language plpgsql
volatile
security invoker
set search_path = public
as $$
declare
  v_id bigint;
  v_previa bigint;
  v_lineas integer;
  v_ids bigint[];
  v_editada boolean := p_lineas is not null;
begin
  if not public.is_coordinacion_admin() then
    raise exception 'Solo un administrador puede emitir nóminas.';
  end if;
  if p_desde is null or p_hasta is null then
    raise exception 'La nómina necesita un periodo (desde y hasta).';
  end if;
  if v_editada and jsonb_typeof(p_lineas) <> 'array' then
    raise exception 'Las líneas editadas deben venir como una lista.';
  end if;

  -- Se normaliza aqui tambien para poder buscar la nomina previa con la misma
  -- lista de historiales que guardara el trigger.
  v_ids := coalesce((
    select array_agg(distinct x order by x)
    from unnest(coalesce(p_historial_ids, '{}'::bigint[])) as x
    where x is not null
  ), '{}'::bigint[]);

  select n.id into v_previa
  from public.nominas n
  where n.personal_id = p_personal_id
    and coalesce(n.empresa_id, 0) = coalesce(p_empresa_id, 0)
    and n.periodo_desde = p_desde
    and n.periodo_hasta = p_hasta
    and n.historial_ids = v_ids
    and n.estado = 'emitida';

  if v_previa is not null then
    if not p_reemplazar then
      raise exception 'Ya hay una nómina emitida para este periodo (#%). Anúlala o emite reemplazándola.', v_previa;
    end if;
    update public.nominas
    set estado = 'anulada', anulada_en = now(),
        anulada_motivo = coalesce(anulada_motivo, 'Reemplazada al reemitir el periodo')
    where id = v_previa;
  end if;

  insert into public.nominas (
    personal_id, empresa_id, periodo_desde, periodo_hasta, historial_ids,
    base_calculo, ajuste_jornada,
    manual_importe, manual_modo, manual_pagas_incluidas,
    manual_complementos, manual_transporte,
    notas, sustituye_a, editada, emitida_por_email
  ) values (
    p_personal_id, p_empresa_id, p_desde, p_hasta, v_ids,
    p_base_calculo, p_ajuste_jornada,
    p_manual_importe, p_manual_modo, coalesce(p_manual_pagas_incluidas, false),
    p_manual_complementos, coalesce(p_manual_transporte, false),
    -- El nullif exterior evita reventar cuando el claim no viene (cadena vacia
    -- no es jsonb valido).
    p_notas, v_previa, v_editada,
    nullif(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'email', '')
  )
  returning id into v_id;

  -- 1) La nomina de la persona: las lineas que suman. Si vienen editadas se
  --    guardan tal cual; si no, las que calcule el motor.
  if v_editada then
    insert into public.nomina_lineas (
      nomina_id, ambito, orden, seccion, concepto, detalle,
      base, tipo, cantidad, precio, codigo_nomina, importe, detalle_de)
    select v_id, 'persona',
           coalesce((l->>'orden')::integer, 0),
           coalesce(nullif(l->>'seccion', ''), 'devengo'),
           coalesce(nullif(l->>'concepto', ''), 'Sin concepto'),
           nullif(l->>'detalle', ''),
           (l->>'base')::numeric, (l->>'tipo')::numeric,
           (l->>'cantidad')::numeric, (l->>'precio')::numeric,
           public.get_codigo_nomina_concepto(l->>'concepto'),
           round(coalesce((l->>'importe')::numeric, 0), 2),
           nullif(l->>'detalle_de', '')
    from jsonb_array_elements(p_lineas) l;
  else
    insert into public.nomina_lineas (
      nomina_id, ambito, orden, seccion, concepto, detalle,
      base, tipo, cantidad, precio, codigo_nomina, importe, detalle_de)
    select v_id, 'persona', c.orden, c.seccion, c.concepto, c.detalle,
           c.base, c.tipo, c.cantidad, c.precio,
           public.get_codigo_nomina_concepto(c.concepto), c.importe, c.detalle_de
    from public.calcular_nomina_persona(
      p_personal_id, p_desde, p_hasta, p_empresa_id, p_base_calculo, p_ajuste_jornada,
      nullif(v_ids, '{}'::bigint[]), p_manual_importe, p_manual_modo,
      coalesce(p_manual_pagas_incluidas, false), p_manual_complementos,
      coalesce(p_manual_transporte, false)
    ) c;
  end if;

  get diagnostics v_lineas = row_count;
  if v_lineas = 0 then
    raise exception 'El cálculo no devuelve ninguna línea para este periodo: no hay nada que emitir.';
  end if;

  -- 2) El contexto laboral de cada periodo/puesto que entra en la nomina.
  --    c.* se expande en el orden del returns table de la funcion, que es el
  --    mismo en el que se listan las columnas destino.
  insert into public.nomina_historiales (
    nomina_id,
    historial_id, personal_id, empresa_id, empresa, puesto_id, puesto,
    convenio_categoria_id, convenio, fecha_alta, fecha_baja,
    tramo_desde, tramo_hasta, dias_nomina, dias_trabajados,
    jornada, jornada_maxima, coeficiente_temporalidad_miles, horas_teoricas,
    modalidad_pago_id, modalidad_pago, ajuste_jornada, base_calculo, grupo_cotizacion,
    salario_mensual, salario_convenio_mensual, salario_convenio_diario,
    salario_convenio_hora, pagas_anuales, pagas_extra,
    horas_reg, horas_pnr, horas_mont, horas_hcomp, horas_ftrab,
    horas_bolsa_salida, horas_bolsa_entrada, horas_nocturnas,
    tiene_plus_transporte, tiene_nocturnidad,
    tiene_complemento_movilidad, tiene_complemento_dedicacion,
    tarifa_plus_transporte, tarifa_hora_nocturna,
    tarifa_complemento_movilidad_pct, tarifa_complemento_dedicacion,
    precio_hora_montaje, precio_hora_complementaria, precio_hora_jornada_completa,
    cotizacion_comunes_pct, cotizacion_mei_pct,
    cotizacion_desempleo_pct, cotizacion_formacion_pct)
  select v_id, c.*
  from public.historiales_laborales h
  cross join lateral public.get_nomina_contexto_historial(
    h.id, p_desde, p_hasta, p_base_calculo, p_ajuste_jornada) c
  where h.personal_id = p_personal_id
    and (p_empresa_id is null or h.empresa_id = p_empresa_id)
    and (v_ids = '{}'::bigint[] or h.id = any(v_ids))
    and h.fecha_alta <= p_hasta and (h.fecha_baja is null or h.fecha_baja >= p_desde);

  -- El predominante (mas dias en el periodo) aporta los tipos de cotizacion y
  -- el numero de pagas del total, igual que hace calcular_nomina_persona.
  update public.nomina_historiales nh
  set predominante = true
  where nh.id = (
    select nh2.id from public.nomina_historiales nh2
    where nh2.nomina_id = v_id
    order by (least(coalesce(nh2.fecha_baja, p_hasta), p_hasta)
              - greatest(nh2.fecha_alta, p_desde)) desc, nh2.historial_id
    limit 1);

  -- 3) El desglose por puesto: explica de donde sale cada importe del total.
  --    NO suma (ambito 'puesto'); los totales se calculan solo con 'persona'.
  insert into public.nomina_lineas (
    nomina_id, ambito, historial_id, orden, seccion, concepto, detalle,
    base, tipo, cantidad, precio, codigo_nomina, importe, detalle_de)
  select v_id, 'puesto', h.id, d.orden, 'devengo', d.concepto, d.detalle,
         d.base, null::numeric, d.cantidad, d.precio,
         public.get_codigo_nomina_concepto(d.concepto), d.importe, d.detalle_de
  from public.historiales_laborales h
  cross join lateral public.calcular_nomina_devengos(
    h.id, p_desde, p_hasta, p_base_calculo, p_ajuste_jornada) d
  where h.personal_id = p_personal_id
    and (p_empresa_id is null or h.empresa_id = p_empresa_id)
    and (v_ids = '{}'::bigint[] or h.id = any(v_ids))
    and h.fecha_alta <= p_hasta and (h.fecha_baja is null or h.fecha_baja >= p_desde);

  update public.nomina_historiales nh
  set total_devengado = coalesce((
    select sum(l.importe) from public.nomina_lineas l
    where l.nomina_id = v_id and l.ambito = 'puesto'
      and l.historial_id = nh.historial_id and l.detalle_de is null), 0)
  where nh.nomina_id = v_id;

  -- 4) Las horas realmente trabajadas, por puesto x tipo de hora x situacion.
  --    Se guardan TAMBIEN las excluidas (CAMB/LG) para que el registro laboral
  --    este completo; van marcadas para que se vea que cuentan cero.
  insert into public.nomina_horas (
    nomina_id, historial_id, puesto_id, puesto,
    tipo_hora_id, tipo_hora, tipo_hora_codigo_nomina,
    situacion_id, situacion, horas, horas_nocturnas, dias, registros,
    registro_ids, excluida, cuenta_jornada, dia_efectivo)
  select v_id, h.id, h.puesto_id, pu.puesto,
         r.tipo_hora_id, th.tipo_hora, th.codigo_nomina,
         r.situacion_id, s.situacion,
         coalesce(sum(r.horas), 0)::numeric,
         coalesce(sum(r.horas_nocturnas), 0)::numeric,
         count(distinct r.fecha)::integer,
         count(*)::integer,
         array_agg(r.id order by r.fecha, r.id),
         coalesce(s.situacion in ('CAMB', 'LG'), false),
         r.tipo_hora_id in (1, 5, 8) and coalesce(s.situacion not in ('CAMB', 'LG'), true),
         coalesce(s.situacion in ('NORM', 'SUST')
                  or (s.situacion = 'FEST' and th.tipo_hora = 'FTRAB'), false)
  from public.historiales_laborales h
  join public.registros r
    on r.personal_id = h.personal_id and r.puesto_id = h.puesto_id
   and (h.empresa_id is null or r.empresa_id = h.empresa_id)
   and r.fecha >= greatest(h.fecha_alta, p_desde)
   and r.fecha <= least(coalesce(h.fecha_baja, p_hasta), p_hasta)
  left join public.tipo_horas th on th.id = r.tipo_hora_id
  left join public.situaciones s on s.id = r.situacion_id
  left join public.puestos pu on pu.id = h.puesto_id
  where h.personal_id = p_personal_id
    and (p_empresa_id is null or h.empresa_id = p_empresa_id)
    and (v_ids = '{}'::bigint[] or h.id = any(v_ids))
    and h.fecha_alta <= p_hasta and (h.fecha_baja is null or h.fecha_baja >= p_desde)
  group by h.id, h.puesto_id, pu.puesto, r.tipo_hora_id, th.tipo_hora,
           th.codigo_nomina, r.situacion_id, s.situacion;

  -- Los totales se derivan de las lineas, no se copian de las lineas-resumen del
  -- motor: asi la cabecera cuadra con su propio desglose. Las filas con
  -- detalle_de quedan fuera porque desglosan a otra que ya suma. Las bases no
  -- son sumables (son magnitudes, no conceptos), asi que se toman de su linea
  -- por `orden`: 600 comunes, 601 profesionales, 602 IRPF (ver
  -- nomina_calculo_persona.sql; si cambian alli, cambiar aqui).
  -- OJO: solo las lineas de ambito 'persona'. Las de 'puesto' son el mismo
  -- dinero explicado por contrato; sumarlas duplicaria el bruto.
  update public.nominas n set
    total_devengado = coalesce((
      select sum(l.importe) from public.nomina_lineas l
      where l.nomina_id = n.id and l.ambito = 'persona'
        and l.seccion = 'devengo' and l.detalle_de is null), 0),
    total_deducciones = coalesce((
      select sum(l.importe) from public.nomina_lineas l
      where l.nomina_id = n.id and l.ambito = 'persona'
        and l.seccion = 'deduccion' and l.detalle_de is null), 0),
    base_cc = coalesce((
      select l.importe from public.nomina_lineas l
      where l.nomina_id = n.id and l.ambito = 'persona' and l.orden = 600), 0),
    base_cp = coalesce((
      select l.importe from public.nomina_lineas l
      where l.nomina_id = n.id and l.ambito = 'persona' and l.orden = 601), 0),
    base_irpf = coalesce((
      select l.importe from public.nomina_lineas l
      where l.nomina_id = n.id and l.ambito = 'persona' and l.orden = 602), 0)
  where n.id = v_id;

  update public.nominas
  set liquido = round(total_devengado - total_deducciones, 2)
  where id = v_id;

  return v_id;
end;
$$;

revoke all on function public.emitir_nomina(integer, date, date, integer, text, text, bigint[], numeric, text, boolean, bigint[], boolean, text, boolean, jsonb) from public;
grant execute on function public.emitir_nomina(integer, date, date, integer, text, text, bigint[], numeric, text, boolean, bigint[], boolean, text, boolean, jsonb) to authenticated;

-- ============================================================================
-- Anular: no se borra, se marca. Las lineas se conservan como historico.
-- ============================================================================

create or replace function public.anular_nomina(p_id bigint, p_motivo text default null)
returns void
language plpgsql
volatile
security invoker
set search_path = public
as $$
begin
  if not public.is_coordinacion_admin() then
    raise exception 'Solo un administrador puede anular nóminas.';
  end if;
  update public.nominas
  set estado = 'anulada', anulada_en = now(),
      anulada_motivo = coalesce(nullif(trim(p_motivo), ''), 'Anulada a mano')
  where id = p_id and estado = 'emitida';
  if not found then
    raise exception 'La nómina #% no existe o ya estaba anulada.', p_id;
  end if;
end;
$$;

revoke all on function public.anular_nomina(bigint, text) from public;
grant execute on function public.anular_nomina(bigint, text) to authenticated;

-- ============================================================================
-- RLS: admin-only, igual que personal_complementos y personal_confidencial.
-- Son importes salariales reales por persona.
-- ============================================================================

alter table public.nominas enable row level security;
alter table public.nomina_lineas enable row level security;
alter table public.nomina_historiales enable row level security;
alter table public.nomina_horas enable row level security;

grant select, insert, update, delete on public.nominas to authenticated;
grant select, insert, update, delete on public.nomina_lineas to authenticated;
grant select, insert, update, delete on public.nomina_historiales to authenticated;
grant select, insert, update, delete on public.nomina_horas to authenticated;
grant usage, select on sequence public.nominas_id_seq to authenticated;
grant usage, select on sequence public.nomina_lineas_id_seq to authenticated;
grant usage, select on sequence public.nomina_historiales_id_seq to authenticated;
grant usage, select on sequence public.nomina_horas_id_seq to authenticated;

drop policy if exists "nominas_admin_can_read" on public.nominas;
create policy "nominas_admin_can_read"
on public.nominas for select to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "nominas_admin_can_insert" on public.nominas;
create policy "nominas_admin_can_insert"
on public.nominas for insert to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "nominas_admin_can_update" on public.nominas;
create policy "nominas_admin_can_update"
on public.nominas for update to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "nominas_admin_can_delete" on public.nominas;
create policy "nominas_admin_can_delete"
on public.nominas for delete to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "nomina_lineas_admin_can_read" on public.nomina_lineas;
create policy "nomina_lineas_admin_can_read"
on public.nomina_lineas for select to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "nomina_lineas_admin_can_insert" on public.nomina_lineas;
create policy "nomina_lineas_admin_can_insert"
on public.nomina_lineas for insert to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "nomina_lineas_admin_can_update" on public.nomina_lineas;
create policy "nomina_lineas_admin_can_update"
on public.nomina_lineas for update to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "nomina_lineas_admin_can_delete" on public.nomina_lineas;
create policy "nomina_lineas_admin_can_delete"
on public.nomina_lineas for delete to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "nomina_historiales_admin_can_read" on public.nomina_historiales;
create policy "nomina_historiales_admin_can_read"
on public.nomina_historiales for select to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "nomina_historiales_admin_can_insert" on public.nomina_historiales;
create policy "nomina_historiales_admin_can_insert"
on public.nomina_historiales for insert to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "nomina_historiales_admin_can_update" on public.nomina_historiales;
create policy "nomina_historiales_admin_can_update"
on public.nomina_historiales for update to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "nomina_historiales_admin_can_delete" on public.nomina_historiales;
create policy "nomina_historiales_admin_can_delete"
on public.nomina_historiales for delete to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "nomina_horas_admin_can_read" on public.nomina_horas;
create policy "nomina_horas_admin_can_read"
on public.nomina_horas for select to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "nomina_horas_admin_can_insert" on public.nomina_horas;
create policy "nomina_horas_admin_can_insert"
on public.nomina_horas for insert to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "nomina_horas_admin_can_update" on public.nomina_horas;
create policy "nomina_horas_admin_can_update"
on public.nomina_horas for update to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "nomina_horas_admin_can_delete" on public.nomina_horas;
create policy "nomina_horas_admin_can_delete"
on public.nomina_horas for delete to authenticated
using (public.is_coordinacion_admin());
