-- ============================================================================
--  Bajas médicas / IT del personal: enfermedad, accidente y las situaciones
--  de salud asimiladas (riesgo durante el embarazo o la lactancia), migradas
--  desde Tbl_Personal_Bajas / _Tipo / _Lugar (Access).
-- ----------------------------------------------------------------------------
--  Es el expediente administrativo del parte, independiente de `registros`:
--  la situación IT/LG de los registros de jornada se sigue marcando a mano
--  como hasta ahora (ver situaciones.sql), esta tabla no los genera.
--
--  Los dos riesgos (embarazo/lactancia) comparten aquí catálogo con las
--  bajas por enfermedad/accidente porque son una situación de salud
--  asimilada a la IT (parte a la Seguridad Social, la persona sigue de alta,
--  no trabaja); se diferencian con `sin_nomina_empresa`: en esos dos tipos el
--  INSS paga el 100% y la empresa no calcula nada. En el resto (enfermedad y
--  accidente) sigue pendiente diseñar el cálculo del complemento de IT (ver
--  memoria nominas-incapacidad-transitoria-pendiente).
--
--  Maternidad/paternidad y lactancia (el permiso propiamente dicho, no el
--  riesgo) NO viven aquí: se movieron a `personal_permisos` el 2026-09-04
--  (ver personal_permisos.sql) porque, aunque se tramiten igual que una
--  baja, no son una situación de salud sino un permiso con tratamiento de
--  nómina propio (maternidad suspende el contrato, lactancia la sigue
--  pagando la empresa) — cada uno distinto entre sí, cosa que el flag
--  binario sin_nomina_empresa no podía expresar. El tipo 6
--  (Maternidad/paternidad) se deja en el catálogo con `activo = false` por
--  si algún export histórico lo referencia; ningún `personal_bajas` vivo lo
--  usa ya.
--
--  No se guarda `periodo`/días como columna: en el Excel origen no cuadraba
--  con fecha_fin - fecha_inicio en ~1 de cada 6 filas (recaídas o tecleo).
--  Se calcula en la vista, igual que dias_periodo en historiales_laborales.
--
--  No se enlaza con historial_laboral_id: el historial/contrato vigente se
--  resuelve por fecha cuando haga falta, no se fija al crear la baja.
-- ============================================================================

create table if not exists public.personal_bajas_tipo (
  id integer primary key,
  tipo text not null,
  sin_nomina_empresa boolean not null default false,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on column public.personal_bajas_tipo.sin_nomina_empresa is
  'true = el INSS paga el 100% y la empresa no genera nómina por el periodo (maternidad/paternidad, riesgo embarazo/lactancia). false = enfermedad o accidente, pendiente el cálculo del complemento de IT.';

insert into public.personal_bajas_tipo (id, tipo, sin_nomina_empresa, activo) values
  (1, 'Enfermedad común', false, true),
  (2, 'Accidente laboral', false, true),
  (3, 'Accidente no laboral', false, true),
  (4, 'Enfermedad profesional', false, true),
  (5, 'Incidente', false, true),
  (6, 'Maternidad/paternidad', true, false),
  (7, 'Riesgo durante el embarazo', true, true),
  (8, 'Riesgo durante la lactancia', true, true)
on conflict (id) do update set
  tipo = excluded.tipo,
  sin_nomina_empresa = excluded.sin_nomina_empresa,
  updated_at = now();

create table if not exists public.personal_bajas_lugar (
  id integer primary key,
  lugar text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.personal_bajas_lugar (id, lugar) values
  (1, 'In itinere'),
  (2, 'Centro de trabajo')
on conflict (id) do update set
  lugar = excluded.lugar,
  updated_at = now();

create table if not exists public.personal_bajas (
  id bigint generated by default as identity primary key,
  personal_id integer not null references public.personal (id),
  tipo_id integer not null references public.personal_bajas_tipo (id),
  lugar_id integer references public.personal_bajas_lugar (id),
  fecha_inicio date not null,
  fecha_fin date,
  con_parte_baja boolean not null default true,
  ingreso_hospitalario boolean not null default false,
  observacion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint personal_bajas_fechas_validas
    check (fecha_fin is null or fecha_fin >= fecha_inicio)
);

comment on table public.personal_bajas is
  'Expediente administrativo de bajas médicas/IT y situaciones asimiladas. No genera por sí solo registros de jornada.';
comment on column public.personal_bajas.lugar_id is
  'Solo aplica a accidente laboral (in itinere / centro de trabajo); se deja sin restricción dura, se valida en el formulario.';
comment on column public.personal_bajas.con_parte_baja is
  'false = incidencia sin baja médica oficial (p.ej. consulta médica sin ausencia real). true = baja con parte.';
comment on column public.personal_bajas.fecha_fin is
  'null = baja en curso, todavía sin alta médica.';

create index if not exists personal_bajas_personal_id_idx
on public.personal_bajas (personal_id);

create index if not exists personal_bajas_tipo_id_idx
on public.personal_bajas (tipo_id);

create index if not exists personal_bajas_fecha_inicio_idx
on public.personal_bajas (fecha_inicio);

create index if not exists personal_bajas_fecha_fin_idx
on public.personal_bajas (fecha_fin);

create or replace function public.set_personal_bajas_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_personal_bajas_updated_at on public.personal_bajas;
create trigger set_personal_bajas_updated_at
before update on public.personal_bajas
for each row
execute function public.set_personal_bajas_updated_at();

drop view if exists public.personal_bajas_detalle;

create or replace view public.personal_bajas_detalle as
select
  b.id,
  b.personal_id,
  p.personal,
  p.dni,
  b.tipo_id,
  bt.tipo,
  bt.sin_nomina_empresa,
  b.lugar_id,
  bl.lugar,
  b.fecha_inicio,
  b.fecha_fin,
  case
    when b.fecha_fin is not null then (b.fecha_fin - b.fecha_inicio) + 1
    else null
  end as dias,
  (b.fecha_fin is null) as en_curso,
  b.con_parte_baja,
  b.ingreso_hospitalario,
  b.observacion,
  b.created_at,
  b.updated_at
from public.personal_bajas b
left join public.personal p
  on p.id = b.personal_id
left join public.personal_bajas_tipo bt
  on bt.id = b.tipo_id
left join public.personal_bajas_lugar bl
  on bl.id = b.lugar_id;

alter view public.personal_bajas_detalle set (security_invoker = true);

grant select on public.personal_bajas_detalle to authenticated;

select setval(
  pg_get_serial_sequence('public.personal_bajas', 'id'),
  coalesce((select max(id) from public.personal_bajas), 1),
  true
);
