-- Fase 3 del modulo de nominas: asignacion de complementos a personas.
--
-- Cada fila es "esta persona tiene este complemento, con este importe/porcentaje,
-- vigente en este rango de fechas". La vigencia es propia de la asignacion,
-- desacoplada de historiales_laborales (decision tomada en la Fase 1: un
-- movimiento contractual menor no debe obligar a reasignar complementos).
--
-- Para complementos con tipo fijo en el catalogo (unidad/bases_aplicables ya
-- definidos alli), el trigger copia esos campos automaticamente: solo hace
-- falta indicar complemento + persona + fechas + importe/porcentaje.
-- Solo "Complemento salarial" (catalogo tipo='variable', confirmado por el
-- usuario que puede ser fijo o % segun la persona) exige indicar aqui el tipo
-- (y unidad/bases_aplicables si aplica), porque el catalogo no lo fija.

create table if not exists public.personal_complementos (
  id bigint generated by default as identity primary key,
  personal_id integer not null references public.personal (id),
  complemento_id bigint not null references public.nomina_complementos_catalogo (id),
  fecha_desde date not null,
  fecha_hasta date,
  tipo text,
  unidad text,
  medida_horas text,
  bases_aplicables text[],
  importe numeric(12, 2),
  porcentaje numeric(6, 4),
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint personal_complementos_fechas_validas_chk
    check (fecha_hasta is null or fecha_hasta >= fecha_desde),
  constraint personal_complementos_tipo_chk
    check (tipo in ('fijo', 'porcentaje')),
  constraint personal_complementos_unidad_chk
    check (unidad is null or unidad in ('mensual', 'diario', 'por_hora')),
  constraint personal_complementos_medida_horas_chk
    check (unidad is distinct from 'por_hora' or medida_horas is not null),
  constraint personal_complementos_bases_validas_chk
    check (
      bases_aplicables is null
      or bases_aplicables <@ array['salario_base', 'pluses', 'complementos']::text[]
    ),
  constraint personal_complementos_coherencia_chk
    check (
      (tipo = 'fijo' and unidad is not null and bases_aplicables is null
        and importe is not null and porcentaje is null)
      or
      (tipo = 'porcentaje' and unidad is null and medida_horas is null
        and bases_aplicables is not null and cardinality(bases_aplicables) > 0
        and porcentaje is not null and importe is null)
    )
);

comment on table public.personal_complementos is
  'Asignacion de un complemento del catalogo a una persona, con importe/porcentaje real y vigencia por fecha propia (independiente de historiales_laborales).';
comment on column public.personal_complementos.tipo is
  'Resuelto por trigger desde nomina_complementos_catalogo.tipo cuando este no es "variable". Si el catalogo es "variable" (hoy solo "Complemento salarial"), lo fija esta asignacion.';
comment on column public.personal_complementos.importe is
  'Importe fijo en euros (segun unidad: mensual, por dia trabajado o por hora de medida_horas). Solo cuando tipo=fijo.';
comment on column public.personal_complementos.porcentaje is
  'Fraccion (0.10 = 10%) aplicada sobre bases_aplicables. Solo cuando tipo=porcentaje.';

create index if not exists personal_complementos_personal_id_idx
on public.personal_complementos (personal_id, fecha_desde desc);

create index if not exists personal_complementos_complemento_id_idx
on public.personal_complementos (complemento_id);

create or replace function public.set_personal_complementos_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_personal_complementos_updated_at on public.personal_complementos;
create trigger set_personal_complementos_updated_at
before update on public.personal_complementos
for each row
execute function public.set_personal_complementos_updated_at();

-- Resuelve tipo/unidad/medida_horas/bases_aplicables desde el catalogo cuando
-- este los fija (tipo != 'variable'), ignorando lo que venga en la fila para
-- evitar que una asignacion quede incoherente con su propio complemento.
-- Cuando el catalogo es 'variable', exige que la asignacion indique el tipo.
create or replace function public.set_personal_complemento_tipo()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_catalogo public.nomina_complementos_catalogo;
begin
  select * into v_catalogo
  from public.nomina_complementos_catalogo
  where id = new.complemento_id;

  if v_catalogo.id is null then
    raise exception 'complemento_id % no existe en nomina_complementos_catalogo', new.complemento_id;
  end if;

  if v_catalogo.tipo = 'variable' then
    if new.tipo is null then
      raise exception
        '"%" es un complemento de tipo variable: indica si esta asignacion es fija o porcentual.',
        v_catalogo.nombre;
    end if;
  else
    new.tipo := v_catalogo.tipo;
    new.unidad := v_catalogo.unidad;
    new.medida_horas := v_catalogo.medida_horas;
    new.bases_aplicables := v_catalogo.bases_aplicables;
  end if;

  return new;
end;
$$;

drop trigger if exists set_personal_complemento_tipo on public.personal_complementos;
create trigger set_personal_complemento_tipo
before insert or update on public.personal_complementos
for each row
execute function public.set_personal_complemento_tipo();

-- Complementos vigentes de una persona en una fecha dada, con los datos del
-- catalogo (nombre, codigo, prorrateo, orden) para no tener que resolverlos
-- aparte en el motor de calculo (Fase 5).
create or replace function public.get_personal_complementos_vigentes(
  p_personal_id integer,
  p_fecha date default current_date
)
returns table (
  id bigint,
  complemento_id bigint,
  nombre text,
  codigo_nomina integer,
  tipo text,
  unidad text,
  medida_horas text,
  bases_aplicables text[],
  importe numeric,
  porcentaje numeric,
  prorratea_en_extra boolean,
  orden_calculo integer,
  fecha_desde date,
  fecha_hasta date
)
language sql
stable
set search_path = public
as $$
  select
    pc.id,
    pc.complemento_id,
    c.nombre,
    c.codigo_nomina,
    pc.tipo,
    pc.unidad,
    pc.medida_horas,
    pc.bases_aplicables,
    pc.importe,
    pc.porcentaje,
    c.prorratea_en_extra,
    c.orden_calculo,
    pc.fecha_desde,
    pc.fecha_hasta
  from public.personal_complementos pc
  join public.nomina_complementos_catalogo c on c.id = pc.complemento_id
  where pc.personal_id = p_personal_id
    and pc.fecha_desde <= p_fecha
    and (pc.fecha_hasta is null or pc.fecha_hasta >= p_fecha)
  order by c.orden_calculo, c.nombre;
$$;

revoke all on function public.get_personal_complementos_vigentes(integer, date) from public;
grant execute on function public.get_personal_complementos_vigentes(integer, date) to authenticated;

-- ============================================================================
-- RLS: admin-only, igual que personal_confidencial (son importes salariales
-- reales por persona).
-- ============================================================================

alter table public.personal_complementos enable row level security;

grant select, insert, update, delete on public.personal_complementos to authenticated;
grant usage, select on sequence public.personal_complementos_id_seq to authenticated;

drop policy if exists "personal_complementos_admin_can_read" on public.personal_complementos;
create policy "personal_complementos_admin_can_read"
on public.personal_complementos
for select
to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "personal_complementos_admin_can_insert" on public.personal_complementos;
create policy "personal_complementos_admin_can_insert"
on public.personal_complementos
for insert
to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "personal_complementos_admin_can_update" on public.personal_complementos;
create policy "personal_complementos_admin_can_update"
on public.personal_complementos
for update
to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "personal_complementos_admin_can_delete" on public.personal_complementos;
create policy "personal_complementos_admin_can_delete"
on public.personal_complementos
for delete
to authenticated
using (public.is_coordinacion_admin());
