begin;

create temporary table import_personal_source (
  id integer,
  activo boolean,
  pert_empresa boolean,
  vinculacion_id integer,
  personal text,
  genero text,
  antiguedad date,
  dni text,
  fecha_nacimiento date,
  ss text,
  email text,
  movil text,
  telefono text,
  direccion text,
  codigo_postal integer,
  localidad text,
  municipio text,
  provincia text,
  cuenta_corriente text,
  foto text,
  contrato_id text,
  observacion text,
  desplazamiento boolean,
  enviar boolean,
  carpeta text,
  pago boolean,
  cv boolean,
  da boolean,
  ds boolean,
  prev_riesgos date,
  epi boolean,
  titulos boolean,
  ig_ac boolean,
  uniforme boolean,
  med_emerg boolean,
  ens boolean,
  com_antiguedad_04 numeric,
  com_absorbible_18 numeric,
  porcent_complemento_18 numeric,
  prorrateo_pagas boolean,
  num_pagas_extra integer,
  tipo_contrato integer,
  grupo integer,
  nivel integer,
  grupo_cotizacion text,
  contacto_urgencia text,
  telefono_urgencia text,
  persona boolean,
  irpf numeric,
  nombre text,
  apellido text
) on commit drop;

insert into import_personal_source (id, activo, pert_empresa, vinculacion_id, personal, genero, antiguedad, dni, fecha_nacimiento, ss, email, movil, telefono, direccion, codigo_postal, localidad, municipio, provincia, cuenta_corriente, foto, contrato_id, observacion, desplazamiento, enviar, carpeta, pago, cv, da, ds, prev_riesgos, epi, titulos, ig_ac, uniforme, med_emerg, ens, com_antiguedad_04, com_absorbible_18, porcent_complemento_18, prorrateo_pagas, num_pagas_extra, tipo_contrato, grupo, nivel, grupo_cotizacion, contacto_urgencia, telefono_urgencia, persona, irpf, nombre, apellido)
select id, activo, pert_empresa, vinculacion_id, personal, genero, antiguedad, dni, fecha_nacimiento, ss, email, movil, telefono, direccion, codigo_postal, localidad, municipio, provincia, cuenta_corriente, foto, contrato_id, observacion, desplazamiento, enviar, carpeta, pago, cv, da, ds, prev_riesgos, epi, titulos, ig_ac, uniforme, med_emerg, ens, com_antiguedad_04, com_absorbible_18, porcent_complemento_18, prorrateo_pagas, num_pagas_extra, tipo_contrato, grupo, nivel, grupo_cotizacion, contacto_urgencia, telefono_urgencia, persona, irpf, nombre, apellido
from jsonb_to_recordset($personal$
[
  {
    "id": 1739,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Patricia Herrera Guerra",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71729838Z",
    "fecha_nacimiento": "2004-06-15",
    "ss": null,
    "email": null,
    "movil": null,
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "˭",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Patricia Herrera Guerra - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Patricia",
    "apellido": "Herrera Guerra"
  },
  {
    "id": 1740,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Irene Alonso García",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "32894863X",
    "fecha_nacimiento": "1999-12-16",
    "ss": "33/1052639711",
    "email": "irealogar99@gmail.com",
    "movil": null,
    "telefono": null,
    "direccion": "Avenida La Reguera, 53 - Urb. la Palomar,19",
    "codigo_postal": 33930,
    "localidad": "Langreo",
    "municipio": "Langreo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES4230590074412032279818",
    "foto": null,
    "contrato_id": "ˮ",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Irene Alonso García - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.0199999995529652",
    "nombre": "Irene",
    "apellido": "Alonso García"
  },
  {
    "id": 1741,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Claudia Reguera García",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71784479F",
    "fecha_nacimiento": "2006-05-06",
    "ss": "391023291451",
    "email": "clauudiarg06@gmail.com",
    "movil": "622817127",
    "telefono": null,
    "direccion": "C/ Augusto Junquera 12, 3A",
    "codigo_postal": 33012,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES7730590031193615196122",
    "foto": null,
    "contrato_id": "˯",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Claudia Reguera García - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": true,
    "med_emerg": true,
    "ens": true,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.0199999995529652",
    "nombre": "Claudia",
    "apellido": "Reguera García"
  },
  {
    "id": 1742,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Sara Entrialgo Sirviente",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "58442526D",
    "fecha_nacimiento": "2004-01-20",
    "ss": "331065771891",
    "email": "entrialgosirvente@gmail.com",
    "movil": "684629421",
    "telefono": null,
    "direccion": "Calle Cirujeda número 30",
    "codigo_postal": 33205,
    "localidad": "Gijón",
    "municipio": "Gijón",
    "provincia": "Asturias",
    "cuenta_corriente": "ES6700493222702414134766",
    "foto": null,
    "contrato_id": "˰",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Sara Entrialgo Sirviente - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.0199999995529652",
    "nombre": "Sara",
    "apellido": "Entrialgo Sirviente"
  },
  {
    "id": 1743,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Lía Álvarez Ortiz",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "26787247K",
    "fecha_nacimiento": "2007-08-26",
    "ss": "331050558655",
    "email": "liaalvarezortiz4@gmail.com",
    "movil": "646619181",
    "telefono": null,
    "direccion": "Calle Tigre Juan, Portal N2, Piso 3ºD",
    "codigo_postal": 33011,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES1300495518122810010178",
    "foto": null,
    "contrato_id": "˱",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Lía Álvarez Ortiz - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": true,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": true,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.0199999995529652",
    "nombre": "Lía",
    "apellido": "Álvarez Ortiz"
  },
  {
    "id": 1745,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Sara Martínez Asperilla",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71675572m",
    "fecha_nacimiento": null,
    "ss": "33 10560913 92",
    "email": "mtnzsara@gmail.com",
    "movil": null,
    "telefono": null,
    "direccion": "José Manuel Bobes 13,2A",
    "codigo_postal": 33690,
    "localidad": "Lugo de Llanera",
    "municipio": "Llanera",
    "provincia": "Oviedo",
    "cuenta_corriente": "ES5930590037933254387925",
    "foto": null,
    "contrato_id": "˳",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Sara Martínez Asperilla - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": false,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.0199999995529652",
    "nombre": "Sara",
    "apellido": "Martínez Asperilla"
  },
  {
    "id": 1746,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Carmen Vegas Herranz",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71803219W",
    "fecha_nacimiento": "2002-02-11",
    "ss": "33 10617316 41",
    "email": "carmenvegasherranz@gmail.com",
    "movil": "634597585",
    "telefono": null,
    "direccion": "Santa Susana  7 4º B",
    "codigo_postal": 33007,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES2321005857290100211181",
    "foto": null,
    "contrato_id": "˴",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Carmen Vegas Herranz - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.0199999995529652",
    "nombre": "Carmen",
    "apellido": "Vegas Herranz"
  },
  {
    "id": 1748,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Ana Alonso Rodriguez",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71648602Z",
    "fecha_nacimiento": "1984-02-08",
    "ss": "33 10326396 24",
    "email": "ana.alro45@gmail.com",
    "movil": "699899947",
    "telefono": null,
    "direccion": "General Elorza 63, 4L",
    "codigo_postal": 33002,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES2800815323310006193525",
    "foto": null,
    "contrato_id": "˶",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Ana Alonso Rodriguez - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.0199999995529652",
    "nombre": "Ana",
    "apellido": "Alonso Rodriguez"
  },
  {
    "id": 1749,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Shaida Paula Smaili García",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71803879H",
    "fecha_nacimiento": "2000-07-19",
    "ss": "331043531007",
    "email": "shaidapedagogia@gmail.com",
    "movil": "722315125",
    "telefono": null,
    "direccion": "Fuertes Acevedo, 124, 2G",
    "codigo_postal": 33006,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES1230590085652872661315",
    "foto": null,
    "contrato_id": "˷",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Shaida Paula Smaili García - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.0199999995529652",
    "nombre": "Shaida Paula",
    "apellido": "Smaili García"
  },
  {
    "id": 1752,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Alba Sánchez Sánchez",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71824651K",
    "fecha_nacimiento": "2009-04-08",
    "ss": "41 11813740 36",
    "email": "albasanchezsa2009@gmail.com",
    "movil": "684635768",
    "telefono": null,
    "direccion": "Buenaventura Paredez 22 1 dcha",
    "codigo_postal": 33001,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": "ES1430590104714015178124",
    "foto": null,
    "contrato_id": "˺",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Alba Sánchez Sánchez - AFD Pequecampus",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Alba",
    "apellido": "Sánchez Sánchez"
  },
  {
    "id": 1753,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Lorena Basols Fernández",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "76919813Q",
    "fecha_nacimiento": "1984-06-09",
    "ss": "33 10395714 84",
    "email": "lore27ast@hotmail.com",
    "movil": "653327423",
    "telefono": null,
    "direccion": "Instituto Aramo, n°9, 5D",
    "codigo_postal": 33011,
    "localidad": "Oviedo",
    "municipio": "Oviedo",
    "provincia": "Asturias",
    "cuenta_corriente": null,
    "foto": null,
    "contrato_id": "˻",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Lorena Basols Fernández - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.0199999995529652",
    "nombre": "Lorena",
    "apellido": "Basols Fernández"
  },
  {
    "id": 1754,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Yolanda Fernández González",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71748887L",
    "fecha_nacimiento": null,
    "ss": "33 0047410 92",
    "email": "yolanda.fdez.gonz@gmail.com",
    "movil": "660989336",
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": "ES4421006618250200100797",
    "foto": null,
    "contrato_id": "˼",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Yolanda Fernández González - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": false,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Yolanda",
    "apellido": "Fernández González"
  },
  {
    "id": 1755,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Ruth Rodríguez Rivaya",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "53777840E",
    "fecha_nacimiento": null,
    "ss": "33 10727826 68",
    "email": "deruthtito@icloud.com",
    "movil": null,
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": "ES5821005638550200190852",
    "foto": null,
    "contrato_id": "˽",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Ruth Rodríguez Rivaya - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Ruth",
    "apellido": "Rodríguez Rivaya"
  },
  {
    "id": 1756,
    "activo": true,
    "pert_empresa": true,
    "vinculacion_id": 1,
    "personal": "Olaya Fernández Álvarez",
    "genero": "M",
    "antiguedad": "2026-06-22",
    "dni": "71748519L",
    "fecha_nacimiento": null,
    "ss": "33 10668267",
    "email": "Olayafenal@gmail.com",
    "movil": null,
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": "ES9421037001670030128295",
    "foto": null,
    "contrato_id": "˾",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Olaya Fernández Álvarez - Concilia Oviedo Apertura",
    "pago": false,
    "cv": true,
    "da": false,
    "ds": true,
    "prev_riesgos": null,
    "epi": false,
    "titulos": true,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Olaya",
    "apellido": "Fernández Álvarez"
  },
  {
    "id": 1757,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Diego García Bravo",
    "genero": "H",
    "antiguedad": "2026-06-22",
    "dni": "71668088L",
    "fecha_nacimiento": null,
    "ss": "28 13012879 75",
    "email": "diegogb130190@gmail.com",
    "movil": null,
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": "ES1900730100540807246436",
    "foto": null,
    "contrato_id": "˿",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Diego García Bravo - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": true,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0.0199999995529652",
    "nombre": "Diego",
    "apellido": "García Bravo"
  },
  {
    "id": 1758,
    "activo": false,
    "pert_empresa": false,
    "vinculacion_id": 1,
    "personal": "Mateo Villa Díaz",
    "genero": "H",
    "antiguedad": "2026-06-22",
    "dni": "71790487N",
    "fecha_nacimiento": null,
    "ss": "33 10664467 50",
    "email": "mateovilladiaz5@gmail.com",
    "movil": null,
    "telefono": null,
    "direccion": null,
    "codigo_postal": null,
    "localidad": null,
    "municipio": null,
    "provincia": null,
    "cuenta_corriente": "ES8401823460250201557674",
    "foto": null,
    "contrato_id": "̀",
    "observacion": null,
    "desplazamiento": false,
    "enviar": false,
    "carpeta": "Y:\\PERSONAL\\ACTIVO\\Mateo Villa Díaz - Concilia Oviedo Apertura",
    "pago": false,
    "cv": false,
    "da": false,
    "ds": false,
    "prev_riesgos": null,
    "epi": false,
    "titulos": false,
    "ig_ac": false,
    "uniforme": false,
    "med_emerg": false,
    "ens": false,
    "com_antiguedad_04": "0",
    "com_absorbible_18": "0",
    "porcent_complemento_18": "0",
    "prorrateo_pagas": false,
    "num_pagas_extra": 2,
    "tipo_contrato": 0,
    "grupo": 0,
    "nivel": 0,
    "grupo_cotizacion": null,
    "contacto_urgencia": null,
    "telefono_urgencia": null,
    "persona": true,
    "irpf": "0",
    "nombre": "Mateo",
    "apellido": "Villa Díaz"
  }
]
$personal$::jsonb) as source (
  id integer,
  activo boolean,
  pert_empresa boolean,
  vinculacion_id integer,
  personal text,
  genero text,
  antiguedad date,
  dni text,
  fecha_nacimiento date,
  ss text,
  email text,
  movil text,
  telefono text,
  direccion text,
  codigo_postal integer,
  localidad text,
  municipio text,
  provincia text,
  cuenta_corriente text,
  foto text,
  contrato_id text,
  observacion text,
  desplazamiento boolean,
  enviar boolean,
  carpeta text,
  pago boolean,
  cv boolean,
  da boolean,
  ds boolean,
  prev_riesgos date,
  epi boolean,
  titulos boolean,
  ig_ac boolean,
  uniforme boolean,
  med_emerg boolean,
  ens boolean,
  com_antiguedad_04 numeric,
  com_absorbible_18 numeric,
  porcent_complemento_18 numeric,
  prorrateo_pagas boolean,
  num_pagas_extra integer,
  tipo_contrato integer,
  grupo integer,
  nivel integer,
  grupo_cotizacion text,
  contacto_urgencia text,
  telefono_urgencia text,
  persona boolean,
  irpf numeric,
  nombre text,
  apellido text
);

create temporary table import_personal_matches on commit drop as
with existing_dni as (
  select upper(btrim(dni)) as dni_key, min(id) as id, count(*) as total
  from public.personal
  where nullif(btrim(dni), '') is not null
  group by upper(btrim(dni))
)
select
  s.*,
  coalesce(p_by_id.id, case when existing_dni.total = 1 then existing_dni.id end) as match_id,
  p_by_id.id is not null as matched_by_id,
  p_by_id.id is null and existing_dni.total = 1 as matched_by_dni,
  p_by_id.id is null and existing_dni.total > 1 as ambiguous_dni
from import_personal_source s
left join public.personal p_by_id
  on p_by_id.id = s.id
left join existing_dni
  on existing_dni.dni_key = upper(btrim(s.dni));

create temporary table import_personal_updated (id integer) on commit drop;

with updated as (
update public.personal p
set
  vinculacion_id = coalesce(p.vinculacion_id, s.vinculacion_id),
  personal = case when nullif(btrim(p.personal), '') is null then s.personal else p.personal end,
  genero = case when nullif(btrim(p.genero), '') is null then s.genero else p.genero end,
  antiguedad = coalesce(p.antiguedad, s.antiguedad),
  dni = case when nullif(btrim(p.dni), '') is null then s.dni else p.dni end,
  fecha_nacimiento = coalesce(p.fecha_nacimiento, s.fecha_nacimiento),
  ss = case when nullif(btrim(p.ss), '') is null then s.ss else p.ss end,
  email = case when nullif(btrim(p.email), '') is null then s.email else p.email end,
  movil = case when nullif(btrim(p.movil), '') is null then s.movil else p.movil end,
  telefono = case when nullif(btrim(p.telefono), '') is null then s.telefono else p.telefono end,
  direccion = case when nullif(btrim(p.direccion), '') is null then s.direccion else p.direccion end,
  codigo_postal = coalesce(p.codigo_postal, s.codigo_postal),
  localidad = case when nullif(btrim(p.localidad), '') is null then s.localidad else p.localidad end,
  municipio = case when nullif(btrim(p.municipio), '') is null then s.municipio else p.municipio end,
  provincia = case when nullif(btrim(p.provincia), '') is null then s.provincia else p.provincia end,
  cuenta_corriente = case when nullif(btrim(p.cuenta_corriente), '') is null then s.cuenta_corriente else p.cuenta_corriente end,
  foto = case when nullif(btrim(p.foto), '') is null then s.foto else p.foto end,
  contrato_id = case when nullif(btrim(p.contrato_id), '') is null then s.contrato_id else p.contrato_id end,
  observacion = case when nullif(btrim(p.observacion), '') is null then s.observacion else p.observacion end,
  carpeta = case when nullif(btrim(p.carpeta), '') is null then s.carpeta else p.carpeta end,
  prev_riesgos = coalesce(p.prev_riesgos, s.prev_riesgos),
  com_antiguedad_04 = coalesce(p.com_antiguedad_04, s.com_antiguedad_04),
  com_absorbible_18 = coalesce(p.com_absorbible_18, s.com_absorbible_18),
  porcent_complemento_18 = coalesce(p.porcent_complemento_18, s.porcent_complemento_18),
  num_pagas_extra = coalesce(p.num_pagas_extra, s.num_pagas_extra),
  tipo_contrato = coalesce(p.tipo_contrato, s.tipo_contrato),
  grupo = coalesce(p.grupo, s.grupo),
  nivel = coalesce(p.nivel, s.nivel),
  grupo_cotizacion = case when nullif(btrim(p.grupo_cotizacion), '') is null then s.grupo_cotizacion else p.grupo_cotizacion end,
  contacto_urgencia = case when nullif(btrim(p.contacto_urgencia), '') is null then s.contacto_urgencia else p.contacto_urgencia end,
  telefono_urgencia = case when nullif(btrim(p.telefono_urgencia), '') is null then s.telefono_urgencia else p.telefono_urgencia end,
  irpf = coalesce(p.irpf, s.irpf),
  nombre = case when nullif(btrim(p.nombre), '') is null then s.nombre else p.nombre end,
  apellido = case when nullif(btrim(p.apellido), '') is null then s.apellido else p.apellido end
from import_personal_matches s
where p.id = s.match_id
returning p.id
)
insert into import_personal_updated (id)
select id
from updated;

create temporary table import_personal_inserted (id integer) on commit drop;

with inserted as (
insert into public.personal (id, activo, pert_empresa, vinculacion_id, personal, genero, antiguedad, dni, fecha_nacimiento, ss, email, movil, telefono, direccion, codigo_postal, localidad, municipio, provincia, cuenta_corriente, foto, contrato_id, observacion, desplazamiento, enviar, carpeta, pago, cv, da, ds, prev_riesgos, epi, titulos, ig_ac, uniforme, med_emerg, ens, com_antiguedad_04, com_absorbible_18, porcent_complemento_18, prorrateo_pagas, num_pagas_extra, tipo_contrato, grupo, nivel, grupo_cotizacion, contacto_urgencia, telefono_urgencia, persona, irpf, nombre, apellido)
select s.id, s.activo, s.pert_empresa, s.vinculacion_id, s.personal, s.genero, s.antiguedad, s.dni, s.fecha_nacimiento, s.ss, s.email, s.movil, s.telefono, s.direccion, s.codigo_postal, s.localidad, s.municipio, s.provincia, s.cuenta_corriente, s.foto, s.contrato_id, s.observacion, s.desplazamiento, s.enviar, s.carpeta, s.pago, s.cv, s.da, s.ds, s.prev_riesgos, s.epi, s.titulos, s.ig_ac, s.uniforme, s.med_emerg, s.ens, s.com_antiguedad_04, s.com_absorbible_18, s.porcent_complemento_18, s.prorrateo_pagas, s.num_pagas_extra, s.tipo_contrato, s.grupo, s.nivel, s.grupo_cotizacion, s.contacto_urgencia, s.telefono_urgencia, s.persona, s.irpf, s.nombre, s.apellido
from import_personal_matches s
where s.match_id is null
  and not s.ambiguous_dni
on conflict (id) do nothing
returning id
)
insert into import_personal_inserted (id)
select id
from inserted;

select
  (select count(*) from import_personal_source) as filas_origen,
  (select count(*) from import_personal_matches where matched_by_id) as existentes_por_id,
  (select count(*) from import_personal_matches where matched_by_dni) as existentes_por_dni,
  (select count(*) from import_personal_updated) as filas_revisadas_para_rellenar,
  (select count(*) from import_personal_inserted) as filas_insertadas,
  (select count(*) from import_personal_matches where ambiguous_dni) as dni_ambiguos_no_insertados;

select id, personal, dni
from import_personal_matches
where ambiguous_dni
order by personal;

commit;
