do $$
begin
  if to_regclass('public.programacion_conserjes') is null
     and to_regclass('public."tbl_programacionConserjes"') is not null then
    alter table public."tbl_programacionConserjes" rename to programacion_conserjes;
  elsif to_regclass('public.programacion_conserjes') is null
     and to_regclass('public.findesemana') is not null then
    alter table public.findesemana rename to programacion_conserjes;
  end if;
end $$;

create table if not exists public.programacion_conserjes (
  id bigint generated by default as identity primary key,
  personal text not null,
  instalacion text not null,
  fecha date not null,
  hora_inicio time not null,
  hora_fin time,
  hora_evento time,
  deporte text,
  actividad text,
  source_file text,
  sort_order integer not null default 0,
  tipo_programacion text not null default 'fin_semana',
  archived_at timestamp with time zone,
  created_at timestamp with time zone not null default timezone('utc', now()),
  constraint programacion_conserjes_tipo_check
    check (tipo_programacion in ('fin_semana', 'semanal'))
);

alter table public.programacion_conserjes
add column if not exists tipo_programacion text not null default 'fin_semana';

alter table public.programacion_conserjes
add column if not exists archived_at timestamp with time zone;

alter table public.programacion_conserjes
add column if not exists created_at timestamp with time zone not null default timezone('utc', now());

alter table public.programacion_conserjes
drop constraint if exists programacion_conserjes_tipo_check;

alter table public.programacion_conserjes
add constraint programacion_conserjes_tipo_check
check (tipo_programacion in ('fin_semana', 'semanal'));

update public.programacion_conserjes
set tipo_programacion = 'semanal'
where source_file = 'planning_completo_revisado.csv';

drop index if exists idx_findesemana_loaded_at;
drop index if exists idx_findesemana_fecha;
drop index if exists idx_findesemana_instalacion;
drop index if exists idx_findesemana_personal;
drop index if exists idx_findesemana_archived_at;

alter table public.programacion_conserjes
drop column if exists loaded_at;

create index if not exists idx_programacion_conserjes_tipo_fecha
on public.programacion_conserjes (tipo_programacion, fecha);

create index if not exists idx_programacion_conserjes_instalacion
on public.programacion_conserjes (instalacion);

create index if not exists idx_programacion_conserjes_personal
on public.programacion_conserjes (personal);

create index if not exists idx_programacion_conserjes_archived_at
on public.programacion_conserjes (archived_at);

notify pgrst, 'reload schema';
