-- Fase 1 del modulo de nominas: tarifas salariales por puesto.
--
-- Dos tablas con vigencia por fecha (el convenio cambia tarifas con el tiempo,
-- y una nomina pasada debe poder recalcularse con la tarifa que estaba vigente
-- entonces, no con la actual):
--   - puestos_salarios: salario anual/mensual/diario/hora "normal" del puesto.
--   - puestos_tarifas_hora: precio de hora por tipo_hora (para fijar el precio
--     real de horas complementarias/montaje en vez de depender solo del
--     multiplicador generico de tipo_horas).
--
-- Ambas son confidenciales (son tarifas salariales reales): RLS admin-only,
-- mismo patron que personal_confidencial.

create table if not exists public.puestos_salarios (
  id bigint generated by default as identity primary key,
  puesto_id integer not null references public.puestos (id),
  vigente_desde date not null,
  salario_anual numeric(12, 2),
  salario_mensual numeric(12, 2),
  salario_diario numeric(12, 2),
  precio_hora numeric(10, 4),
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint puestos_salarios_puesto_vigencia_unique unique (puesto_id, vigente_desde)
);

comment on table public.puestos_salarios is
  'Tarifas salariales por puesto con vigencia por fecha. Varias filas por puesto_id: una por cada cambio de tarifa.';
comment on column public.puestos_salarios.vigente_desde is
  'Fecha desde la que aplica esta tarifa. La tarifa vigente en una fecha es la de mayor vigente_desde <= esa fecha.';
comment on column public.puestos_salarios.precio_hora is
  'Precio de la hora normal (tipo_hora REG). Base para calcular horas complementarias/montaje cuando no hay override en puestos_tarifas_hora.';

create index if not exists puestos_salarios_puesto_id_idx
on public.puestos_salarios (puesto_id, vigente_desde desc);

create table if not exists public.puestos_tarifas_hora (
  id bigint generated by default as identity primary key,
  puesto_id integer not null references public.puestos (id),
  tipo_hora_id integer not null references public.tipo_horas (id),
  vigente_desde date not null,
  precio_hora numeric(10, 4) not null,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint puestos_tarifas_hora_puesto_tipo_vigencia_unique
    unique (puesto_id, tipo_hora_id, vigente_desde)
);

comment on table public.puestos_tarifas_hora is
  'Override del precio/hora de un puesto para un tipo_hora concreto (p.ej. hora complementaria o de montaje), con vigencia por fecha. Si no hay fila aplicable, el precio se calcula desde puestos_salarios.precio_hora * tipo_horas.multiplicador.';

create index if not exists puestos_tarifas_hora_puesto_tipo_idx
on public.puestos_tarifas_hora (puesto_id, tipo_hora_id, vigente_desde desc);

create or replace function public.set_puestos_salarios_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_puestos_salarios_updated_at on public.puestos_salarios;
create trigger set_puestos_salarios_updated_at
before update on public.puestos_salarios
for each row
execute function public.set_puestos_salarios_updated_at();

drop trigger if exists set_puestos_tarifas_hora_updated_at on public.puestos_tarifas_hora;
create trigger set_puestos_tarifas_hora_updated_at
before update on public.puestos_tarifas_hora
for each row
execute function public.set_puestos_salarios_updated_at();

-- Tarifa base vigente de un puesto en una fecha dada (la ultima con vigente_desde <= fecha).
create or replace function public.get_puesto_salario_vigente(
  p_puesto_id integer,
  p_fecha date default current_date
)
returns public.puestos_salarios
language sql
stable
set search_path = public
as $$
  select s.*
  from public.puestos_salarios s
  where s.puesto_id = p_puesto_id
    and s.vigente_desde <= p_fecha
  order by s.vigente_desde desc
  limit 1;
$$;

-- Precio/hora efectivo de un puesto para un tipo_hora en una fecha dada:
-- usa el override de puestos_tarifas_hora si existe: si no, precio_hora base * multiplicador del tipo_hora.
create or replace function public.get_puesto_precio_hora(
  p_puesto_id integer,
  p_tipo_hora_id integer,
  p_fecha date default current_date
)
returns numeric
language sql
stable
set search_path = public
as $$
  select coalesce(
    (
      select t.precio_hora
      from public.puestos_tarifas_hora t
      where t.puesto_id = p_puesto_id
        and t.tipo_hora_id = p_tipo_hora_id
        and t.vigente_desde <= p_fecha
      order by t.vigente_desde desc
      limit 1
    ),
    (
      select s.precio_hora * th.multiplicador
      from public.puestos_salarios s
      cross join public.tipo_horas th
      where s.puesto_id = p_puesto_id
        and th.id = p_tipo_hora_id
        and s.vigente_desde <= p_fecha
      order by s.vigente_desde desc
      limit 1
    )
  );
$$;

revoke all on function public.get_puesto_salario_vigente(integer, date) from public;
revoke all on function public.get_puesto_precio_hora(integer, integer, date) from public;
grant execute on function public.get_puesto_salario_vigente(integer, date) to authenticated;
grant execute on function public.get_puesto_precio_hora(integer, integer, date) to authenticated;

alter table public.puestos_salarios enable row level security;
alter table public.puestos_tarifas_hora enable row level security;

grant select, insert, update, delete on public.puestos_salarios to authenticated;
grant select, insert, update, delete on public.puestos_tarifas_hora to authenticated;
grant usage, select on sequence public.puestos_salarios_id_seq to authenticated;
grant usage, select on sequence public.puestos_tarifas_hora_id_seq to authenticated;

drop policy if exists "puestos_salarios_admin_can_read" on public.puestos_salarios;
create policy "puestos_salarios_admin_can_read"
on public.puestos_salarios
for select
to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "puestos_salarios_admin_can_insert" on public.puestos_salarios;
create policy "puestos_salarios_admin_can_insert"
on public.puestos_salarios
for insert
to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "puestos_salarios_admin_can_update" on public.puestos_salarios;
create policy "puestos_salarios_admin_can_update"
on public.puestos_salarios
for update
to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "puestos_salarios_admin_can_delete" on public.puestos_salarios;
create policy "puestos_salarios_admin_can_delete"
on public.puestos_salarios
for delete
to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "puestos_tarifas_hora_admin_can_read" on public.puestos_tarifas_hora;
create policy "puestos_tarifas_hora_admin_can_read"
on public.puestos_tarifas_hora
for select
to authenticated
using (public.is_coordinacion_admin());

drop policy if exists "puestos_tarifas_hora_admin_can_insert" on public.puestos_tarifas_hora;
create policy "puestos_tarifas_hora_admin_can_insert"
on public.puestos_tarifas_hora
for insert
to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "puestos_tarifas_hora_admin_can_update" on public.puestos_tarifas_hora;
create policy "puestos_tarifas_hora_admin_can_update"
on public.puestos_tarifas_hora
for update
to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "puestos_tarifas_hora_admin_can_delete" on public.puestos_tarifas_hora;
create policy "puestos_tarifas_hora_admin_can_delete"
on public.puestos_tarifas_hora
for delete
to authenticated
using (public.is_coordinacion_admin());
