-- ============================================================================
-- RD 723/2026 (condiciones laborales transparentes y previsibles): modelo de
-- datos para poder generar el anexo informativo obligatorio por contrato,
-- llamamiento o variacion. Fase "solo BD" (ver memoria rd723-condiciones-
-- laborales-anexo): esto NO crea todavia ningun formulario ni PDF, solo deja
-- el sitio donde vivira cada dato.
--
-- El anexo modelo (18 apartados) se cruzo con lo que ya existe en la app:
--   - Puesto, funciones, centros de trabajo, horario, salario jornada
--     completa, tipo de contratacion -> ya en `puestos`/`contratos`/
--     `contrato_instalaciones`/`historiales_laborales`, no se toca aqui.
--   - Convenio como entidad legal (codigo BOE, jornada maxima, periodo de
--     prueba, vacaciones, preavisos) -> no existia, se crea `convenios`.
--   - Mutua, Plan de Igualdad, protocolos de acoso/LGTBI, sistemas
--     algoritmicos -> son por EMPRESA (EDP/INTECA), no por contrato: columnas
--     nuevas en `empresas`.
--   - Periodos estimados de actividad/inactividad, % horas complementarias,
--     medio de llamamiento, entrega del anexo -> cambian en cada llamamiento/
--     alta: tabla nueva 1:1 `historiales_laborales_rd723`, para no meter 10
--     columnas mas en `historiales_laborales` (tabla ya grande y usada por el
--     motor de nominas).
--   - Distribucion irregular de jornada, si aplica -> es una politica del
--     contrato de servicio: tabla nueva 1:1 `contratos_rd723`.
--
-- Tabla A/B salarial del IV Convenio de Ocio educativo (art. 44): decision
-- expresa del usuario (23/09/2026) de NO modelar la dualidad en
-- `convenios_categorias_salarios` -- EDP usa la Tabla A en todos sus
-- contratos actuales. `contratos_rd723.tabla_salarial` queda como campo
-- informativo de texto para el anexo, sin ningun efecto en el calculo de
-- nominas.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Convenios (entidad legal). convenios_categorias.convenio ya guardaba el
--    nombre repetido en ~20 filas; se normaliza sin borrar esa columna
--    (mismo patron de retirada en 2 fases que "servicio": BD primero, UI
--    despues, borrado del duplicado al final).
-- ----------------------------------------------------------------------------

create table if not exists public.convenios (
  id integer generated by default as identity primary key,
  nombre text not null unique,
  codigo text,
  boe_numero text,
  boe_fecha date,
  fecha_publicacion date,
  vigente_hasta date,
  articulo_prorroga text,
  jornada_maxima_anual_horas numeric,
  jornada_maxima_semanal_horas numeric,
  periodo_prueba_texto text,
  vacaciones_dias integer,
  vacaciones_notas text,
  preaviso_llamamiento_dias integer,
  preaviso_llamamiento_articulo text,
  preaviso_cese_dias integer,
  preaviso_cese_notas text,
  notas text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.convenios is
  'Convenio colectivo como entidad legal (codigo BOE, vigencia, jornada maxima, periodo de prueba, vacaciones, preavisos). convenios_categorias.convenio_id referencia esta tabla; convenios_categorias.convenio (texto) se mantiene por compatibilidad con la UI actual.';
comment on column public.convenios.preaviso_cese_dias is
  'Preaviso general de cese voluntario en dias, cuando el convenio no lo diferencia por grupo profesional. Si varia por grupo, dejar NULL y detallarlo en preaviso_cese_notas (ver V Convenio Instalaciones Deportivas, art. 17.3: grupos 1-2 dos meses, grupos 3-5 quince dias).';

create or replace function public.set_convenios_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_convenios_updated_at on public.convenios;
create trigger set_convenios_updated_at
before update on public.convenios
for each row
execute function public.set_convenios_updated_at();

insert into public.convenios (
  nombre, codigo, boe_numero, boe_fecha, fecha_publicacion, vigente_hasta, articulo_prorroga,
  jornada_maxima_anual_horas, jornada_maxima_semanal_horas, periodo_prueba_texto,
  vacaciones_dias, vacaciones_notas, preaviso_llamamiento_dias, preaviso_llamamiento_articulo,
  preaviso_cese_dias, preaviso_cese_notas, notas
) values
(
  'IV Convenio Colectivo Marco Estatal de Ocio Educativo y Animación Sociocultural',
  '99100055012011', '62', '2026-03-11', '2026-03-11', '2027-12-31', 'artículo 3',
  1742, 38.5, '1 mes, salvo que por las circunstancias concretas de la contratación no proceda establecerlo o exista una regla válida más favorable/aplicable.',
  30, '30 días naturales por año completo de servicios, o la parte proporcional que corresponda.',
  15, 'artículo 25',
  15, 'Para los grupos III a VI, 15 días conforme al IV Convenio, salvo norma más favorable o supuesto específico aplicable.',
  'Datos tomados del anexo informativo modelo (Anexo_informativo_EDP_completado_RD723_IV_Ocio.docx) y de la Resolución de 25 de enero de 2026. Verificar contra el texto íntegro del convenio antes de dar por definitivos los datos de vigencia/prórroga.'
),
(
  'V Convenio Colectivo Estatal de Instalaciones Deportivas y Gimnasios',
  '99015105012005', '23', '2024-01-26', '2024-01-26', '2025-12-31', 'artículo 3.2 (prórroga tácita anual salvo denuncia con 1 mes de antelación)',
  1752, 40, 'Grupos 1 y 2: tres meses. Grupos 3, 4 y 5: dos meses. Contratos de duración determinada por circunstancias de la producción ocasionales/previsibles (art. 15.2 ET): quince días.',
  23, '23 días laborables por año completo, en un máximo de tres bloques (uno de 15 días laborables consecutivos entre el 1 de junio y el 30 de septiembre, y otros dos de al menos 3 días consecutivos cada uno). Proporcional para quien ingrese o cese durante el año.',
  15, 'artículo 22',
  null, 'Cese voluntario (art. 17.3): grupos 1 y 2, dos meses; grupos 3, 4 y 5, quince días. El incumplimiento del preaviso faculta a la empresa a descontar un día de salario por cada día de retraso.',
  'Resolución de 16 de enero de 2024, BOE núm. 23 de 26/01/2024 (código de convenio 99015105012005). Vigencia desde el 22/06/2023 (efectos económicos desde 01/05/2023) hasta 31/12/2025, con prórroga tácita anual salvo denuncia.'
)
on conflict (nombre) do nothing;

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'convenios_categorias' and column_name = 'convenio_id'
  ) then
    alter table public.convenios_categorias add column convenio_id integer references public.convenios (id);
  end if;
end $$;

update public.convenios_categorias cc
set convenio_id = c.id
from public.convenios c
where cc.convenio_id is null
  and (
    (cc.convenio like 'IV Convenio colectivo estatal de instalaciones deportivas%' and c.nombre = 'V Convenio Colectivo Estatal de Instalaciones Deportivas y Gimnasios')
    or (cc.convenio like 'Convenio Colectivo de Sector de OCIO EDUCATIVO%' and c.nombre = 'IV Convenio Colectivo Marco Estatal de Ocio Educativo y Animación Sociocultural')
  );

comment on column public.convenios_categorias.convenio_id is
  'FK a convenios (entidad legal). La columna de texto convenio se mantiene por compatibilidad con la UI actual hasta que se migre a leer de aquí.';

alter table public.convenios enable row level security;
grant select on public.convenios to authenticated;
grant insert, update, delete on public.convenios to authenticated;
grant usage, select on sequence public.convenios_id_seq to authenticated;

drop policy if exists "authenticated_can_read_convenios" on public.convenios;
create policy "authenticated_can_read_convenios"
on public.convenios
for select
to authenticated
using (true);

drop policy if exists "authenticated_can_insert_convenios" on public.convenios;
create policy "authenticated_can_insert_convenios"
on public.convenios
for insert
to authenticated
with check (public.is_coordinacion_admin());

drop policy if exists "authenticated_can_update_convenios" on public.convenios;
create policy "authenticated_can_update_convenios"
on public.convenios
for update
to authenticated
using (public.is_coordinacion_admin())
with check (public.is_coordinacion_admin());

drop policy if exists "authenticated_can_delete_convenios" on public.convenios;
create policy "authenticated_can_delete_convenios"
on public.convenios
for delete
to authenticated
using (public.is_coordinacion_admin());

-- ----------------------------------------------------------------------------
-- 2. Empresas: Mutua, Plan de Igualdad, protocolos y sistemas algorítmicos.
--    RLS ya existente en empresas (lectura para authenticated, escritura
--    admin) cubre estas columnas nuevas sin cambios.
-- ----------------------------------------------------------------------------

alter table public.empresas add column if not exists mutua_nombre text;
alter table public.empresas add column if not exists mutua_numero text;
alter table public.empresas add column if not exists plan_igualdad_vigente boolean not null default false;
alter table public.empresas add column if not exists plan_igualdad_nombre text;
alter table public.empresas add column if not exists plan_igualdad_acceso text;
alter table public.empresas add column if not exists protocolo_acoso_texto text;
alter table public.empresas add column if not exists medidas_lgtbi_texto text;
alter table public.empresas add column if not exists lugar_consulta_documentos text;
alter table public.empresas add column if not exists usa_sistemas_algoritmicos boolean not null default false;
alter table public.empresas add column if not exists sistemas_algoritmicos_detalle text;

comment on column public.empresas.lugar_consulta_documentos is
  'Apartado 13 del anexo RD723: lugar o medio en que la persona trabajadora puede consultar el Plan de Igualdad, protocolos, etc.';
comment on column public.empresas.sistemas_algoritmicos_detalle is
  'Descripción, finalidad y pautas/criterios de los sistemas algorítmicos o automatizados usados para decisiones laborales, cuando usa_sistemas_algoritmicos = true.';

-- ----------------------------------------------------------------------------
-- 3. historiales_laborales_rd723: lo que cambia en cada llamamiento/alta.
--    1:1 con historiales_laborales, RLS calcada de historiales_laborales_scope.sql
--    (misma persona -> mismo alcance por contrato).
-- ----------------------------------------------------------------------------

create table if not exists public.historiales_laborales_rd723 (
  historial_id bigint primary key references public.historiales_laborales (id) on delete cascade,
  periodo_actividad_estimado text,
  periodo_inactividad_estimado text,
  duracion_estimada_periodo_actividad text,
  jornada_anual_estimada_horas numeric,
  horas_complementarias_pct numeric,
  horas_complementarias_preaviso text,
  llamamiento_medio text,
  llamamiento_contacto text,
  formacion_obligatoria_texto text,
  medio_entrega text check (medio_entrega in ('papel', 'electronico')),
  fecha_entrega date,
  entregado boolean not null default false,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.historiales_laborales_rd723 is
  'Datos del anexo informativo RD723 específicos de cada periodo/llamamiento (historiales_laborales), separados de esa tabla para no acoplar el anexo al motor de nóminas.';

create or replace function public.set_historiales_laborales_rd723_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_historiales_laborales_rd723_updated_at on public.historiales_laborales_rd723;
create trigger set_historiales_laborales_rd723_updated_at
before update on public.historiales_laborales_rd723
for each row
execute function public.set_historiales_laborales_rd723_updated_at();

alter table public.historiales_laborales_rd723 enable row level security;
grant select, insert, update, delete on public.historiales_laborales_rd723 to authenticated;

drop policy if exists "historiales_laborales_rd723_can_read" on public.historiales_laborales_rd723;
create policy "historiales_laborales_rd723_can_read"
on public.historiales_laborales_rd723
for select
to authenticated
using (
  public.can_access_coordinacion_personal(
    (select hl.personal_id from public.historiales_laborales hl where hl.id = historial_id)
  )
);

drop policy if exists "historiales_laborales_rd723_can_write" on public.historiales_laborales_rd723;
create policy "historiales_laborales_rd723_can_write"
on public.historiales_laborales_rd723
as permissive
for all
to authenticated
using (
  public.can_manage_coordinacion_historial(
    (select hl.personal_id from public.historiales_laborales hl where hl.id = historial_id)
  )
)
with check (
  public.can_manage_coordinacion_historial(
    (select hl.personal_id from public.historiales_laborales hl where hl.id = historial_id)
  )
);

drop policy if exists "coordinacion_solo_usuarios_rd723_historial" on public.historiales_laborales_rd723;
create policy "coordinacion_solo_usuarios_rd723_historial"
on public.historiales_laborales_rd723
as restrictive
for all
to authenticated
using (public.is_coordinacion_user())
with check (public.is_coordinacion_user());

-- ----------------------------------------------------------------------------
-- 4. contratos_rd723: distribución irregular de jornada (si aplica) y tabla
--    salarial de referencia para el anexo. 1:1 con contratos, RLS calcada
--    de contrato_instalaciones (lectura/gestión por contrato asignado).
-- ----------------------------------------------------------------------------

create table if not exists public.contratos_rd723 (
  contrato_id integer primary key references public.contratos (id) on delete cascade,
  distribucion_irregular boolean not null default false,
  distribucion_irregular_sistema text,
  distribucion_irregular_referencia text,
  distribucion_irregular_preaviso_inicio text,
  distribucion_irregular_preaviso_cancelacion text,
  tabla_salarial text,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.contratos_rd723 is
  'Datos del anexo informativo RD723 propios de cada contrato de servicio: distribución irregular de jornada y tabla salarial de referencia (solo informativa para el anexo, sin efecto en el motor de nóminas).';
comment on column public.contratos_rd723.tabla_salarial is
  'Texto libre (p.ej. "Tabla A"). No condiciona get_convenio_salario_vigente ni el resto del motor de nóminas: EDP usa hoy la Tabla A en todos sus contratos (decisión 23/09/2026), no se modeló la dualidad A/B en convenios_categorias_salarios.';

create or replace function public.set_contratos_rd723_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_contratos_rd723_updated_at on public.contratos_rd723;
create trigger set_contratos_rd723_updated_at
before update on public.contratos_rd723
for each row
execute function public.set_contratos_rd723_updated_at();

alter table public.contratos_rd723 enable row level security;
grant select, insert, update, delete on public.contratos_rd723 to authenticated;

drop policy if exists "contratos_rd723_can_read" on public.contratos_rd723;
create policy "contratos_rd723_can_read"
on public.contratos_rd723
for select
to authenticated
using (public.can_access_coordinacion_contrato(contrato_id));

drop policy if exists "contratos_rd723_can_write" on public.contratos_rd723;
create policy "contratos_rd723_can_write"
on public.contratos_rd723
as permissive
for all
to authenticated
using (public.can_manage_coordinacion_contrato(contrato_id))
with check (public.can_manage_coordinacion_contrato(contrato_id));

drop policy if exists "coordinacion_solo_usuarios_rd723_contrato" on public.contratos_rd723;
create policy "coordinacion_solo_usuarios_rd723_contrato"
on public.contratos_rd723
as restrictive
for all
to authenticated
using (public.is_coordinacion_user())
with check (public.is_coordinacion_user());
