do $$
begin
  if to_regclass('public.registros_horarios') is null
     and to_regclass('public.registros') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'registros'
         and column_name = 'dni'
     ) then
    alter table public.registros rename to registros_horarios;
  end if;

  if to_regclass('public.registros') is null
     and to_regclass('public.horas') is not null then
    alter table public.horas rename to registros;
  end if;
end $$;
create table if not exists public.registros (
  id bigint generated by default as identity primary key,
  fecha date,
  actividad_id bigint,
  servicio_id bigint,
  empresa_id integer default 1,
  contrato_id integer,
  personal_id integer,
  titular_personal_id integer,
  sustituto_personal_id integer,
  instalacion_id integer,
  categoria_id integer,
  puesto_id integer,
  funcion_id integer,
  modalidad_id integer,
  nivel_id integer,
  grupo_id integer,
  nota text,
  dia_id integer,
  hora_inicio time,
  hora_fin time,
  horas real default 0,
  hc real default 0,
  hf real default 0,
  hm real default 0,
  hd real default 0,
  bolsa_horas real default 0,
  horas_diurnas real,
  horas_nocturnas real,
  clases real default 0,
  horas_2 real default 0,
  descanso boolean default false,
  activo boolean default true,
  festivo boolean default false,
  sustitucion boolean default false,
  facturar boolean default true,
  abonar boolean default true,
  tipo_hora_id integer,
  situacion_id integer default 1,
  anio integer default 0,
  observacion text,
  control timestamp with time zone default now(),
  factura varchar(10)
);

create index if not exists registros_fecha_hora_id_idx
on public.registros (fecha desc, hora_inicio asc, id asc);

create index if not exists registros_actividad_id_idx
on public.registros (actividad_id);

create index if not exists registros_servicio_id_idx
on public.registros (servicio_id);

create index if not exists registros_empresa_id_idx
on public.registros (empresa_id);

create index if not exists registros_contrato_fecha_idx
on public.registros (contrato_id, fecha desc);

create index if not exists registros_personal_fecha_idx
on public.registros (personal_id, fecha desc);

create index if not exists registros_titular_personal_fecha_idx
on public.registros (titular_personal_id, fecha desc);

create index if not exists registros_sustituto_personal_fecha_idx
on public.registros (sustituto_personal_id, fecha desc);

create index if not exists registros_instalacion_fecha_idx
on public.registros (instalacion_id, fecha desc);

create index if not exists registros_puesto_fecha_idx
on public.registros (puesto_id, fecha desc);

create index if not exists registros_funcion_id_idx
on public.registros (funcion_id);

create index if not exists registros_modalidad_id_idx
on public.registros (modalidad_id);

create index if not exists registros_tipo_hora_id_idx
on public.registros (tipo_hora_id);

create index if not exists registros_situacion_id_idx
on public.registros (situacion_id);

do $$
begin
  alter table public.registros
    add column if not exists servicio_id bigint;

  alter table public.registros
    drop column if exists institucion_id;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_actividad_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_actividad_id_fkey
      foreign key (actividad_id)
      references public.actividades (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_servicio_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_servicio_id_fkey
      foreign key (servicio_id)
      references public.servicios (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_empresa_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_empresa_id_fkey
      foreign key (empresa_id)
      references public.empresas (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_contrato_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_contrato_id_fkey
      foreign key (contrato_id)
      references public.contratos (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_personal_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_personal_id_fkey
      foreign key (personal_id)
      references public.personal (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_titular_personal_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_titular_personal_id_fkey
      foreign key (titular_personal_id)
      references public.personal (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_sustituto_personal_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_sustituto_personal_id_fkey
      foreign key (sustituto_personal_id)
      references public.personal (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_instalacion_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_instalacion_id_fkey
      foreign key (instalacion_id)
      references public.instalaciones (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_puesto_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_puesto_id_fkey
      foreign key (puesto_id)
      references public.puestos (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_funcion_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_funcion_id_fkey
      foreign key (funcion_id)
      references public.funciones (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_modalidad_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_modalidad_id_fkey
      foreign key (modalidad_id)
      references public.modalidades (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_tipo_hora_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_tipo_hora_id_fkey
      foreign key (tipo_hora_id)
      references public.tipo_horas (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'registros_situacion_id_fkey'
      and conrelid = 'public.registros'::regclass
  ) then
    alter table public.registros
      add constraint registros_situacion_id_fkey
      foreign key (situacion_id)
      references public.situaciones (id)
      on update cascade
      on delete set null
      not valid;
  end if;
end $$;

comment on table public.registros is
  'Detalle diario/horario generado desde actividades. Cada fila puede enlazarse con actividad, contrato, personal, instalacion, puesto y catalogos horarios.';

comment on column public.registros.actividad_id is
  'Actividad de planificacion que origino el registro.';

comment on column public.registros.servicio_id is
  'Servicio asociado al registro. Se copia desde la actividad generadora cuando existe.';

comment on column public.registros.personal_id is
  'Personal principal asignado al registro.';

comment on column public.registros.titular_personal_id is
  'Personal titular cuando el registro representa una sustitucion.';

comment on column public.registros.sustituto_personal_id is
  'Personal sustituto cuando el registro representa una sustitucion.';

drop view if exists public.registros_detalle;

create or replace view public.registros_detalle as
select
  r.id,
  r.fecha,
  r.actividad_id,
  r.servicio_id,
  se.servicio,
  r.empresa_id,
  e.empresa,
  r.contrato_id,
  c.contrato,
  r.personal_id,
  p.personal,
  p.dni,
  r.titular_personal_id,
  titular.personal as titular_personal,
  r.sustituto_personal_id,
  sustituto.personal as sustituto_personal,
  r.instalacion_id,
  i.instalacion,
  r.categoria_id,
  r.puesto_id,
  pu.puesto,
  r.funcion_id,
  f.funcion,
  r.modalidad_id,
  m.modalidad,
  r.nivel_id,
  r.grupo_id,
  r.nota,
  r.dia_id,
  r.hora_inicio,
  r.hora_fin,
  r.horas,
  r.hc,
  r.hf,
  r.hm,
  r.hd,
  r.bolsa_horas,
  r.horas_diurnas,
  r.horas_nocturnas,
  r.clases,
  r.horas_2,
  r.descanso,
  r.activo,
  r.festivo,
  r.sustitucion,
  r.facturar,
  r.abonar,
  r.tipo_hora_id,
  th.tipo_hora,
  r.situacion_id,
  s.situacion,
  r.anio,
  r.observacion,
  r.control,
  r.factura
from public.registros r
left join public.actividades a
  on a.id = r.actividad_id
left join public.servicios se
  on se.id = r.servicio_id
left join public.empresas e
  on e.id = r.empresa_id
left join public.contratos c
  on c.id = r.contrato_id
left join public.personal p
  on p.id = r.personal_id
left join public.personal titular
  on titular.id = r.titular_personal_id
left join public.personal sustituto
  on sustituto.id = r.sustituto_personal_id
left join public.instalaciones i
  on i.id = r.instalacion_id
left join public.puestos pu
  on pu.id = r.puesto_id
left join public.funciones f
  on f.id = r.funcion_id
left join public.modalidades m
  on m.id = r.modalidad_id
left join public.tipo_horas th
  on th.id = r.tipo_hora_id
left join public.situaciones s
  on s.id = r.situacion_id;

alter view public.registros_detalle set (security_invoker = true);

grant select on public.registros_detalle to authenticated;
