-- ============================================================================
--  registro_apuntes  —  Eje 4: movimientos economicos de una jornada.
-- ----------------------------------------------------------------------------
--  Una fila de `registros` (la jornada: persona, fecha, franja, situacion)
--  genera UNO O VARIOS apuntes. El apunte es el hecho economico real:
--  cuantas horas (con signo), a que tarifa (concepto), que clase de movimiento
--  y a quien impacta (abonar al trabajador / facturar al cliente).
--
--  Lo que antes eran columnas (hd, bolsa_horas, ...) pasa a ser apuntes con
--  signo, de modo que el saldo de bolsa y el rastro del PRN son consultas,
--  no campos a mantener.
--
--  Ejemplos:
--    Dia normal 8h          -> 1 apunte  DEVENGO     NORMAL  +8  abonar facturar
--    Festivo 4h             -> 1 apunte  DEVENGO     HF      +4  (x1.75)
--    Montaje 3h             -> 1 apunte  DEVENGO     HM      +3
--    PRN de 2h              -> 2 apuntes DEVENGO +2  y  DEVOLUCION_HD -2 (neto 0)
--    Guarda 3h en bolsa     -> 1 apunte  BOLSA_ENTRA NORMAL  +3  abonar=false
--    Gasta 3h de bolsa      -> 1 apunte  BOLSA_SALE  NORMAL  -3
-- ============================================================================
create table if not exists public.registro_apuntes (
  id bigint generated by default as identity primary key,
  registro_id bigint not null,
  cantidad real not null default 0,            -- horas con signo (+ devenga, - resta)
  concepto_id integer,                          -- tarifa: FK a tipo_horas (NORMAL/HC/HM/HF)
  movimiento text not null default 'DEVENGO',
  abonar boolean not null default true,         -- impacta nomina del trabajador
  facturar boolean not null default true,       -- impacta factura al cliente
  compensa_apunte_id bigint,                     -- el apunte de devolucion (HD) apunta a su devengo
  nota text,
  control timestamp with time zone default now(),
  constraint registro_apuntes_movimiento_chk
    check (movimiento in ('DEVENGO', 'DEVOLUCION_HD', 'BOLSA_ENTRA', 'BOLSA_SALE'))
);

create index if not exists registro_apuntes_registro_id_idx
  on public.registro_apuntes (registro_id);

create index if not exists registro_apuntes_concepto_id_idx
  on public.registro_apuntes (concepto_id);

create index if not exists registro_apuntes_movimiento_idx
  on public.registro_apuntes (movimiento);

create index if not exists registro_apuntes_compensa_idx
  on public.registro_apuntes (compensa_apunte_id);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'registro_apuntes_registro_id_fkey'
      and conrelid = 'public.registro_apuntes'::regclass
  ) then
    alter table public.registro_apuntes
      add constraint registro_apuntes_registro_id_fkey
      foreign key (registro_id)
      references public.registros (id)
      on update cascade
      on delete cascade;          -- si la jornada desaparece, sus apuntes tambien
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'registro_apuntes_concepto_id_fkey'
      and conrelid = 'public.registro_apuntes'::regclass
  ) then
    alter table public.registro_apuntes
      add constraint registro_apuntes_concepto_id_fkey
      foreign key (concepto_id)
      references public.tipo_horas (id)
      on update cascade
      on delete set null
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'registro_apuntes_compensa_apunte_id_fkey'
      and conrelid = 'public.registro_apuntes'::regclass
  ) then
    alter table public.registro_apuntes
      add constraint registro_apuntes_compensa_apunte_id_fkey
      foreign key (compensa_apunte_id)
      references public.registro_apuntes (id)
      on update cascade
      on delete set null
      not valid;
  end if;
end $$;

comment on table public.registro_apuntes is
  'Movimientos economicos (eje 4) de cada jornada de registros. Cantidad con signo + concepto/tarifa + clase de movimiento + destino (abonar/facturar).';
comment on column public.registro_apuntes.cantidad is
  'Horas del apunte con signo: positivo devenga/entra, negativo resta/sale.';
comment on column public.registro_apuntes.movimiento is
  'DEVENGO (hora trabajada), DEVOLUCION_HD (resta por PRN), BOLSA_ENTRA, BOLSA_SALE.';
comment on column public.registro_apuntes.compensa_apunte_id is
  'En una devolucion HD, apunta al apunte DEVENGO que compensa (par PRN: pagar + devolver).';

-- ----------------------------------------------------------------------------
--  Vista de detalle: cada apunte enriquecido con su jornada, persona y tarifa.
--  horas_ponderadas = cantidad * multiplicador del concepto.
-- ----------------------------------------------------------------------------
drop view if exists public.registro_apuntes_detalle;
create or replace view public.registro_apuntes_detalle as
select
  a.id,
  a.registro_id,
  r.fecha,
  r.personal_id,
  p.personal,
  r.contrato_id,
  r.instalacion_id,
  r.situacion_id,
  s.situacion,
  a.cantidad,
  a.concepto_id,
  th.tipo_hora as concepto,
  th.multiplicador,
  a.cantidad * coalesce(th.multiplicador, 1.0) as horas_ponderadas,
  a.movimiento,
  a.abonar,
  a.facturar,
  a.compensa_apunte_id,
  a.nota,
  a.control
from public.registro_apuntes a
join public.registros r on r.id = a.registro_id
left join public.personal p on p.id = r.personal_id
left join public.tipo_horas th on th.id = a.concepto_id
left join public.situaciones s on s.id = r.situacion_id;

alter view public.registro_apuntes_detalle set (security_invoker = true);
grant select on public.registro_apuntes_detalle to authenticated;

-- ----------------------------------------------------------------------------
--  Saldo VIVO de bolsa de horas por persona = suma de los apuntes BOLSA_*.
--  (BOLSA_ENTRA suma, BOLSA_SALE resta, porque la cantidad ya lleva signo.)
-- ----------------------------------------------------------------------------
drop view if exists public.bolsa_horas_saldo;
create or replace view public.bolsa_horas_saldo as
select
  r.personal_id,
  p.personal,
  sum(a.cantidad) as saldo,
  count(*) as movimientos,
  max(a.control) as ultimo_movimiento
from public.registro_apuntes a
join public.registros r on r.id = a.registro_id
left join public.personal p on p.id = r.personal_id
where a.movimiento in ('BOLSA_ENTRA', 'BOLSA_SALE')
group by r.personal_id, p.personal;

alter view public.bolsa_horas_saldo set (security_invoker = true);
grant select on public.bolsa_horas_saldo to authenticated;
