do $$
begin
  if to_regclass('public."tbl_programacionConserjes"') is null
     and to_regclass('public.findesemana') is not null then
    alter table public.findesemana rename to "tbl_programacionConserjes";
  end if;
end $$;

create table if not exists public."tbl_programacionConserjes" (
  id bigint generated by default as identity primary key,
  personal text not null,
  instalacion text not null,
  fecha date not null,
  hora_inicio time not null,
  hora_fin time,
  hora_evento time,
  deporte text,
  actividad text,
  source_file text,
  sort_order integer not null default 0,
  tipo_programacion text not null default 'fin_semana',
  archived_at timestamp with time zone,
  created_at timestamp with time zone not null default timezone('utc', now()),
  constraint tbl_programacion_conserjes_tipo_check
    check (tipo_programacion in ('fin_semana', 'semanal'))
);

alter table public."tbl_programacionConserjes"
add column if not exists tipo_programacion text not null default 'fin_semana';

alter table public."tbl_programacionConserjes"
add column if not exists archived_at timestamp with time zone;

alter table public."tbl_programacionConserjes"
add column if not exists created_at timestamp with time zone not null default timezone('utc', now());

alter table public."tbl_programacionConserjes"
drop constraint if exists tbl_programacion_conserjes_tipo_check;

alter table public."tbl_programacionConserjes"
add constraint tbl_programacion_conserjes_tipo_check
check (tipo_programacion in ('fin_semana', 'semanal'));

update public."tbl_programacionConserjes"
set tipo_programacion = 'semanal'
where source_file = 'planning_completo_revisado.csv';

drop index if exists idx_findesemana_loaded_at;
drop index if exists idx_findesemana_fecha;
drop index if exists idx_findesemana_instalacion;
drop index if exists idx_findesemana_personal;
drop index if exists idx_findesemana_archived_at;

alter table public."tbl_programacionConserjes"
drop column if exists loaded_at;

create index if not exists idx_tbl_programacion_conserjes_tipo_fecha
on public."tbl_programacionConserjes" (tipo_programacion, fecha);

create index if not exists idx_tbl_programacion_conserjes_instalacion
on public."tbl_programacionConserjes" (instalacion);

create index if not exists idx_tbl_programacion_conserjes_personal
on public."tbl_programacionConserjes" (personal);

create index if not exists idx_tbl_programacion_conserjes_archived_at
on public."tbl_programacionConserjes" (archived_at);

notify pgrst, 'reload schema';
