create table if not exists public.tbl_personal (
  id_personal integer primary key,
  activo boolean not null default false,
  pert_empresa boolean not null default false,
  vinculacion_id integer,
  personal text not null,
  genero text,
  antiguedad date,
  dni text,
  fecha_nacimiento date,
  ss text,
  email text,
  movil text,
  telefono text,
  direccion text,
  codigo_postal integer,
  localidad text,
  municipio text,
  provincia text,
  cuenta_corriente text,
  foto text,
  contrato_id text,
  observacion text,
  desplazamiento boolean not null default false,
  enviar boolean not null default false,
  carpeta text,
  pago boolean not null default false,
  cv boolean not null default false,
  da boolean not null default false,
  ds boolean not null default false,
  prev_riesgos date,
  epi boolean not null default false,
  titulos boolean not null default false,
  ig_ac boolean not null default false,
  uniforme boolean not null default false,
  med_emerg boolean not null default false,
  ens boolean not null default false,
  com_antiguedad_04 numeric(12, 2),
  com_absorbible_18 numeric(12, 2),
  porcent_complemento_18 numeric(12, 2),
  prorrateo_pagas boolean not null default false,
  num_pagas_extra integer,
  tipo_contrato integer,
  grupo integer,
  nivel integer,
  grupo_cotizacion text,
  contacto_urgencia text,
  telefono_urgencia text,
  persona boolean not null default false,
  irpf numeric(7, 4),
  nombre text,
  apellido text
);
